### ISSUE TITLE
Change DIVIDE to protect against division-by-zero

### ISSUE THREAD

**Issue by antw** [quintel/etengine#1025]
As @DorinevanderVlies documents in quintel/etmodel#2862, it is possible to divide a value by zero in a query or input, and guarding against these errors is cumbersome. `DIVIDE` already protects against some invalid operations:

```ruby
DIVIDE(0, 0)     # => 0.0 (instead of NaN)
DIVIDE(nil, 0)   # => 0.0 (instead of error)
DIVIDE(nil, nil) # => 0.0 (instead of error)
DIVIDE(1 , 0)    # => Infinity
```

By comparison, Ruby-style division does this:

```ruby
0 / 0     # => error
0.0 / 0   # => NaN
nil / 0   # => error
nil / nil # => error
1 / 0     # => error
1.0 / 0   # => Infinity
```

The question is what should we do about the fourth `DIVIDE` example: `DIVIDE(1, 0)`? The current result – `Infinity` – is rarely helpful. Returning zero may be the more useful outcome, even though it is mathematically incorrect.

Alternatively, we might add a new `SAFE_DIVIDE` function which converts the `Infinity` to zero. This has the advantage of signalling that the query author made a conscious decision to allow division-by-zero; that it is acceptable – and expected – for the divisor to be zero. The downside is that it means adding a new function, which authors may forget exists.

@ChaelKruip @DorinevanderVlies @michieldenhaan Do you have any preference, or perhaps an alternative idea?

**Comment by michieldenhaan** [comment]
I think I prefer ``DIVIDE(1 , 0)    # => 0.0`` rather than a new function. So far I've only come across instances of 'unacceptable and unexpected' division by zero, so we might never use a separate 'not-so-safe' ``DIVIDE``. Or can someone think of cases in which it can be useful?

**Comment by ChaelKruip** [comment]
> The current result – Infinity – is rarely helpful. Returning zero may be the more useful outcome, even though it is mathematically incorrect.

Can you elaborate @antw ?

My feeling is that returning zero could be confusing. Infinity let's me know that I'm dividing by zero somewhere and therefore should be aware. If I get 'zero' as a result I might be tempted to either ignore the problem or look for the nominator to be zero for some reason instead of the denominator...

I'll think about how to deal with the original issue as well

**Comment by antw** [comment]
> My feeling is that returning zero could be confusing. Infinity let's me know that I'm dividing by zero somewhere and therefore should be aware.

My reasoning for this change is that `DIVIDE` already hides *some* cases of division-by-zero:

```ruby
DIVIDE(0, 0)     # => 0.0 (instead of NaN)
DIVIDE(nil, 0)   # => 0.0 (instead of error)
DIVIDE(nil, nil) # => 0.0 (instead of error)
```

The only change I'm suggesting is that perhaps `DIVIDE(1, 0)` should return `0.0` instead of `Infinity`. Ruby-style division (`a / b`) would continue to return `Infinity` and `NaN` when dividing by zero.

My question is: is it useful that `DIVIDE` returns infinity? If so we can leave it, but we need to figure out some alternative for quintel/etmodel#2862; for example a separate method such as `SAFE_DIVIDE` or `INFINITY_TO_ZERO`.

My concern is that returning infinity can lead to obviously incorrect queries:

```ruby
UPDATE(AREA(), areable_land, 0)

DIVIDE(GRAPH(area_footprint), AREA(areable_land))
# => Infinity
```

([the real bio_footprint query](https://github.com/quintel/etsource/blob/57a55c77523676a1aca13bb06758db016ff1a435/gqueries/general/area/bio_footprint.gql) uses Ruby-style division, so it will remain broken if areable_land is zero)

**Comment by ChaelKruip** [comment]
> My question is: is it useful that DIVIDE returns infinity? 

My answer would be a tentative "yes" but...

> If so we can leave it, but we need to figure out some alternative for quintel/etmodel#2862; for example a separate method such as SAFE_DIVIDE or INFINITY_TO_ZERO.

... not useful enough to warrant the creation of new methods or use spending a lot of energy on  quintel/etmodel#2862 if it can be solved straightforwardly with the proposed change.

In short: let's do it! 😄
