### ISSUE TITLE
'Old' insulation migration on BETA results in very high insulation for buildings

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1042]
The 'old' migration for buildings insulation has resulted in very high values for ``buildings_insulation_level``. For some scenarios the value is 200,000+ (while the slider max is 74). @ChaelKruip and I checked this for multiple areas and found very high values. One scenario initially had an RC value of around 0.6 (out of 3) and now has ``buildings_insulation_level: 236682.94745370373``

We've checked the migration script but everything looks fine. Do you know what could have happened @antw?

See for example: 
https://beta-engine.energytransitionmodel.com/data/latest/scenarios/990249/
https://beta-engine.energytransitionmodel.com/data/latest/scenarios/821823

**Comment by ChaelKruip** [comment]
NOTE: This issue has not been resolved by the last deploy.

**Comment by michieldenhaan** [comment]
Closing as it is outdated
(feel free to reopen if someone disagrees)
