### ISSUE TITLE
Typo in primary demand method for torrefied biomass pellets

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1061]
Recently we fixed a typo in the torrefied biomass carrier. However, the corresponding primary demand method still uses the old carrier name (torr-**i**-fied)

![beta-engine energytransitionmodel com - EnergyTransitionModel 2019-07-11 17-29-14(1)](https://user-images.githubusercontent.com/32056448/61064170-8d0ef100-a401-11e9-8fb1-906b5a49bcf5.png)

**Comment by antw** [comment]
I think this is because [a node still has the old name](https://github.com/quintel/etsource/blob/5ac64f8d8afa4b660ecf2452ac9e26675fe0a077/nodes/industry/industry_chp_ultra_supercritical_coal.central_producer.ad#L5).

**Comment by michieldenhaan** [comment]
Thanks! The typo was still in a bunch of Excels on ETDataset so it reappeared when running ``rake import:node``
