### ISSUE TITLE
Imported electricity doesn't fill the gap between total production and total demand

### ISSUE THREAD

**Issue by redekok** [quintel/etengine#1071]
In an electrification [scenario](https://pro.energytransitionmodel.com/scenarios/404433) for Muide Meulestede (Gent), we expected that whenever the total electricity production doesn't meet the total electricity demand, imported electricity would be used to fill this gap. This didn't seem to be the case though. As can be seen in the screenshot below, we observed that at least 9 kW of electricity can be imported per hour (see black circle). However, at the spot where the red circle is drawn, the total electricity demand is 7 kW per hour but only 2 kW of electricity is imported.

@antw Would you have any idea why this is the case?

![screenshot 2019-03-04 at 10 45 00](https://user-images.githubusercontent.com/5946498/53726110-94c7f300-3e6d-11e9-933b-743209d29594.png)

**Comment by antw** [comment]
At long last: fixed!

> If a user wants to build a more moderate scenario (e.g. a 2030 scenario in which only limited H2 is available) the issue can also arise for a city like Amsterdam (450k residences). 15% H2 HHPs in Amsterdam [...]

![Screenshot 2020-02-14 at 16 22 23](https://user-images.githubusercontent.com/4383/74548781-66400c80-4f46-11ea-84a4-6402d1d17568.png)

> Is this the same issue. This case seems a bit more extreme than I see above. I have opened Elburg.

![Screenshot 2020-02-14 at 16 23 06](https://user-images.githubusercontent.com/4383/74548748-558f9680-4f46-11ea-8083-537fd5b6c93d.png)

> Even when adding all series (not just the ones displayed) it doesn't sum up to the total

As an added bonus, this is now also fixed. `Q` will no longer return a curve with rounded values when used as part of another query:

```
SUM(
  SUM(Q(merit_households_other_demand)),
  SUM(Q(merit_buildings_other_demand)),
  SUM(Q(merit_ev_demand)),
  SUM(Q(merit_households_hot_water_demand)),
  SUM(Q(merit_households_space_heating_demand)),
  SUM(Q(merit_industry_metals_demand)),
  SUM(Q(merit_industry_chemical_demand)),
  SUM(Q(merit_buildings_space_heating_demand)),
  SUM(Q(merit_agriculture_demand)),
  SUM(Q(merit_industry_other_demand)),
  SUM(Q(merit_transport_other_demand)),
  SUM(Q(merit_other_demand)), 
  SUM(Q(merit_hv_network_loss)),
  SUM(Q(merit_other_flexibility_demand))
)

Region:     om_elburg
Production: 89,552.57702782296
Beta:       44,351
```
