### ISSUE TITLE
Is the new P2H feature working as intended?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1075]
For scenario 1195420 (BETA) I tried to test the new P2H feature by comparing the hourly curves. Using the sandbox, I've queried the network_gas input curve of ``industry_chemicals_other_burner_network_gas`` and the electricity_input_curve of ``industry_chemicals_other_flexibility_p2h_network_gas_electricity``. Multiplying these curves with 3600 (MWh -> MJ) and their heat output efficiencies (0.9 and 0.995 respectively) should give heat production per hour. 

When comparing the outcomes I've noticed a couple of things:
- Total heat demand of ``industry_chemicals_other_network_gas_hybrid_heat`` is 80.62 PJ in this scenario (according to the graph). Total heat production of the burner and P2H combined is 82.9 PJ (when summing the curves) => a 2 PJ mismatch
- According to the graph, ``industry_chemicals_other_burner_network_gas`` has a gas input of 37.2 PJ. Summing the input curve results in 40 PJ input. For P2H this is 46.91 PJ (graph) and 47.15 PJ (curves)
- For the first hour of the year the P2H output is 21 TJ (i.e. the maximum capacity of 5945 MW), whereas heat demand is 9 TJ. Does this mean that 12 TJ is stored in the P2H buffer?
- For every hour of the year total heat production is either equal to total heat demand in that hour or larger than total heat demand in that hour -> Could it be that no heat is drawn from the buffer? I would expect that if production > demand in a certain hour, it will be the case that demand > production a few hours later as the heat in the buffer is used.

Discussed this with @marliekeverweij and we find it hard to explain these results. @antw Do you have time to take a look at this?

**Comment by michieldenhaan** [comment]
My calculations can be found here btw: https://docs.google.com/spreadsheets/d/1yA7u36sUaHM0bit8a3M9KiM1LKLQaJTs0P6-htXkZ2s/edit?usp=sharing

**Comment by antw** [comment]
> @antw Do you have time to take a look at this?

I'll check it out today.

**Comment by antw** [comment]
I suspect my mistake has been using the electricity input for P2H to determine heat output. The two aren't necessarily correlated due to the buffer. I expect I'll have a solution for that shortly.

> For scenario 1195420 (BETA)

Would you mind double-checking this scenario ID? On beta it's a blank scenario with no inputs.

**Comment by marliekeverweij** [comment]
Okay! Initially we wanted to model P2H in industry without a buffer, but you told me that that was not possible with the current modelling. If it makes it easier for you to model no buffer, then we could go for that solution as well!

@michieldenhaan has checked the scenario ID and it is: 1195388

**Comment by antw** [comment]
> but you told me that that was not possible with the current modelling

Indeed, the P2H implementation adds energy to a buffer, then subtracts energy from that buffer based on demand. If there's no buffer, then there's nothing from which to subtract the demand, and the P2H ends up doing nothing.

I intend to add a heat_output_curve to the P2H node, which will tell us precisely how much heat is output and _when_.

**Comment by antw** [comment]
[I have this fixed locally](https://docs.google.com/spreadsheets/d/106jUHDdPoWVG0BFZCaRqw_sj_g5fGQEqW_jlfnq8mGE/edit?usp=sharing). I should have a final version on beta by the end of the day.

**Comment by michieldenhaan** [comment]
Nice! Does this mean that P2H no longer has a buffer? Judging from the Excel it looks like the electricity input of the P2H never exceeds direct demand in that hour (so no excess heat to fill the buffer)

**Comment by antw** [comment]
It still has a buffer, I just failed to update the column headers in the CSV file. "P2H e input (MW) output from sandbox" should have been "P2H heat output (MW)".
