### ISSUE TITLE
Some scenarios did not survive previous migrations

### ISSUE THREAD

**Issue by noracato** [quintel/etengine#1094]
While migrating all protected scenarios from production for the heat changes (using etm-tools query-scenario) there were about a 100 scenarios ETE wasn't able to query or load.

After some digging by @michieldenhaan we found these scenarios still carried old (2018) names for sliders, contained sliders that were no longer present, or contained strange values. It seems these scenarios did not survive previous migrations.

We are unsure about the cause, and will probably leave it like it is. Very very strange...

These are all the id's of the scenarios that won't load: [still_broken.txt](https://github.com/quintel/etengine/files/4267131/still_broken.txt) Maybe there are scenarios in there that are valueable to any of you?

notifying @antw @ChaelKruip @redekok @jorisberkhout @marliekeverweij @DorinevanderVlies @MartLubben @AlexanderWirtz

**Comment by DorinevanderVlies** [comment]
Can it be that we protected these scenario's after they were originally made?

So that it is possible that there was a migration between the moment that the scenario was made and that the scenario was protected?

**Comment by michieldenhaan** [comment]
F
