### ISSUE TITLE
Heat demand is zero in first hour?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1099]
When checking the data dumps of several scenarios I noticed that the heat demand (and hence electricity/gas/h2 demand of heaters) is zero in the first hour in all of them.

Not sure if this is a bug or that my interpretation of the data dump is not correct?

**Comment by antw** [comment]
This looks to be correct. [The heat demand profiles](https://github.com/quintel/etsource/tree/master/datasets/nl/curves/weather/default) (`insulation_TYPE_LEVEL.csv`) files in ETSource do indeed all have zero demand in the first hour of the year.

**Comment by michieldenhaan** [comment]
Thanks, I could have checked that myself 😅 Most heat demand profiles are 0 every 24th hour (first hour of the day), except for some 'high insulation' ones which are 0 in the first hour of the year but not necessarily every day. That's why I was triggered by the 0 demand in the first hour, as in many scenarios its the only hour during Winter with no demand at all.. Anyway, this will change soon as we are planning to smooth all heating demand curves
