### ISSUE TITLE
Some data exports show error page for admin users

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1123]
For a while now an error shows up for admin users when trying to download some of the curves in the data export. The download does start and you can simply hit 'Refresh and try again' to get rid of it, but it's still a bit annoying sometimes.

I've had this happen for:
- Energy flows
- Production capacity and costs
- Households heat
- Gas
- Hydrogen

It's a minor issue and not deploy critical I think as it only affects admins (presumably).

![Specifications heat and electricity production - Data export - Energy Transition Model - beta-pro energytransitionmodel com 2020-06-10 17-30-44](https://user-images.githubusercontent.com/32056448/84287521-4d381880-ab40-11ea-8294-869e0323b629.png)

**Comment by redekok** [comment]
Hmm interesting.. I've never faced this issue before (and I suppose I'm an admin user?).

**Comment by michieldenhaan** [comment]
Blank NL 2015 scenario on Firefox:
![screencast 2020-06-11 12-23-45-min](https://user-images.githubusercontent.com/32056448/84375416-d05c7b80-abdf-11ea-9421-ad56869b9593.gif)

**Comment by redekok** [comment]
I guess it's a firefox thing then? 🤔

**Comment by antw** [comment]
It's because the CSVs open in the current window. If you have an ongoing request to ETEngine (to fetch queries, apply an input, etc), the browser cancels the request when navigating away to the CSV.

I've updated the links to open the CSVs in a new window.
