### ISSUE TITLE
Cannot inspect energy_hydrogen wind and solar nodes in graph

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1169]
Trying to inspect `energy_hydrogen_solar_pv_solar_radiation` or `energy_hydrogen_wind_turbine_offshore` in the graph results in:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/32056448/117977572-43f79300-b331-11eb-9f0a-ca5020da6269.png">

Local machine:
```
NoMethodError - undefined method `*' for nil:NilClass:
  (eval):1:in `format_value'
  app/serializers/node_serializer.rb:70:in `format_value'
  app/serializers/node_serializer.rb:55:in `present_value'
  app/views/inspect/nodes/show.html.haml:128:in `block (2 levels) in _app_views_inspect_nodes_show_html_haml___1513111634239114735_2451420100'
  app/views/inspect/nodes/show.html.haml:123:in `block in _app_views_inspect_nodes_show_html_haml___1513111634239114735_2451420100'
  app/views/inspect/nodes/show.html.haml:119:in `_app_views_inspect_nodes_show_html_haml___1513111634239114735_2451420100'
  app/controllers/inspect/nodes_controller.rb:37:in `block (2 levels) in show'
  app/controllers/inspect/nodes_controller.rb:36:in `show'
```

<img width="777" alt="image" src="https://user-images.githubusercontent.com/32056448/117977731-6db0ba00-b331-11eb-9b23-6f306c0b80d7.png">

Do you know what's wrong here @antw? I would expect that `typical_input_capacity` can be derived from `electricity_output_capacity` and `output.electricity`, NoU calculated based on FLHs (given by dataset)?

**Comment by antw** [comment]
`typical_input_capacity` is an attribute taken straight from the node file. `input_capacity` is the attribute used when you want to allow ETEngine to calculate the capacity (from electricity, heat, or cooling capacity) when there's no valid in the node file.

https://github.com/quintel/etengine/blob/fbec0018d420360186b4cb9baa24ed3108c2dfba/app/models/qernel/node_api/cost.rb#L10-L26

I see that attributes [in NodeSerializerData](https://github.com/quintel/etengine/blob/11a2a90a632efed6670dc171ddb0ad2ef3dd5722/app/serializers/node_serializer_data.rb) are all based on `typical_input_capacity`, which means the'll only work on nodes where this attribute is defined in the node document (or set by an input).  I can see two possibilities:

1. Change references in NodeSerialzierData to always use `input_capacity` (and make [a minor change](https://github.com/quintel/etengine/blob/fbec0018d420360186b4cb9baa24ed3108c2dfba/app/models/qernel/node_api/conversion.rb#L133-L134) to support `something_per(:mw_input_capacity)`.
2. Make `typical_input_capacity` an alias of `input_capacity`, such that the two can be used interchangeably.

I prefer the first option.

**Comment by michieldenhaan** [comment]
Thanks! Option 1 sounds good. Not very urgent btw

**Comment by antw** [comment]
Fixed in https://github.com/quintel/etengine/commit/5d547815b8212c72b0842e7921ca27a944c50cd0 and https://github.com/quintel/etmodel/commit/bb81119784ec3b065b978e5cdb16f8c179c4148d.
