### ISSUE TITLE
Wrong primary demand with efficiencies > 100%?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1172]
Scenario on BETA: 1435024. Very simple region with only Household demand (other sectors are 0).

The `energy_production_wood_pellets` node has an output of wood pellets (= primary demand) of 1.55 PJ.
The `primary_demand_of_wood_pellets` of `households_final_demand_steam_hot_water`, `households_final_demand_electricity` and `energy_heat_dumped_steam_hot_water` combined is 1.73 PJ, more than the total primary production of wood pellets.

The culprit seems to be `energy_chp_local_wood_pellets`. This node has a combined heat and electricity efficiency of 111%. When setting CHP capacity to zero and supplying heat with a wood pellet heater instead (total efficiency 90%) the mismatch disappears.

My guess of what is going on here is that the individual carrier efficiencies of the CHP are both < 100% (heat efficiency 82%, electricity efficiency 29%). However, the combined efficiency is > 100%. Suppose wood pellet input is 100 MJ. Then heat output is 82 MJ and electricity output is 29 MJ. The primary demand of the heat output should be 74 MJ, the primary demand of electricity output 26 MJ because 74% of output is heat and 26% of output is electricity. However, because both individual outputs are < 100%, my guess is that 82 MJ primary demand is assigned to heat and 29 MJ to electricity, leading to an overestimate of total primary demand.

@antw Do you know if this is indeed the case? And if this could be fixed with the current implementation of the primary demand method?

Notifying @ChaelKruip, @marliekeverweij 
Revisit of https://github.com/quintel/etengine/issues/936.

**Comment by antw** [comment]
> And if this could be fixed with the current implementation of the primary demand method?

I think your intuition is correct, and that total output efficiencies greater than 100% distort recursive factor results.

However, what it not obvious is why this would be fixed within the calculation for primary demand. Would this issue not affect *all* recursive factor methods? It seems like this rule should also apply to primary_co2_emissions, bio demand / emissions, and final demand. I'm less certain how changing it would affect cost calculations (e.g. `weighted_carrier_cost_per_mj`) or factors (`sustainability_share`).

**Comment by michieldenhaan** [comment]
> However, what it not obvious is why this would be fixed within the calculation for primary demand

Yes you're right, this applies to all recursive methods. For some reason in my mind all other recursive methods are based on/derived from the primary demand one but that's probably not the case.

My gut feeling is that this also applies to weighted_carrier_cost and sustainability.

**Comment by antw** [comment]
I've spent a while working on a fix for this, and it seems to work nicely. However, I have some doubts that a code change is the way to resolve this. It may be that the fix is needed to ensure correct results around transport nodes (which use outputs to convert from MJ to passenger/freight kms), but I'm less certain for other nodes.

I'm not too clued-up on how these technologies work in the real-world, but I don't understand why they have output efficiencies exceeding 1.0. If I put in 1MJ of wood pellets, how can I get out 1.11MJ of energy? For example with [energy_chp_local_wood_pellets](https://engine.energytransitionmodel.com/inspect/839442/graphs/energy/nodes/energy_chp_local_wood_pellets) would the extra energy not come from something like [environment_air_ambient_heat](https://engine.energytransitionmodel.com/inspect/839442/graphs/energy/nodes/environment_air_ambient_heat) or some other ambient source?

I realise you've probably thought of this already, but for my own understanding I'm curious why we don't model this with an extra input carrier to make up the difference and have outputs that sum to 1.0?

**Comment by michieldenhaan** [comment]
Thanks! Good to hear that it's working nicely.

> I realise you've probably thought of this already, but for my own understanding I'm curious why we don't model this with an extra input carrier to make up the difference and have outputs that sum to 1.0?

This has to do with statistical definitions/conventions. The energy content of a fuel is not one single number but can be higher or lower depending on what is or isn't included in your definition/way of measuring (enthalpy). You can either use the 'higher heating value' (HHV) method, which takes into account the heat content of water vapour that is produced during combustion, or 'lower heating value' (LHV) method which doesn't. The latter is picked by the ETM and is typically the standard in statistics and energy modelling. LHV ignores the (latent) heat of water vapour because in many applications this heat goes to waste (machines, cars etc.). One exception is a condensing boiler which can recover this heat by condensing the water vapour. 

This is the case for the nodes with an efficiency > 100%. E.g. according to LHV conventions the energy content of 1m3 natural gas is 31.7 MJ. Using the HHV method it's 35.2 MJ. A condensing boiler can turn 1m3 of gas into 34 MJ of heat. From an LHV perspective this means an efficieny of 107%. For biomass and hydrogen this can be even larger because more water vapour is produced during combustion.

See https://en.wikipedia.org/wiki/Heat_of_combustion#Ways_of_determination for some more background.

**Comment by antw** [comment]
Thanks! So this "missing" energy _is_ in the fuel (wood pellets); we just don't include it in the model until the fuel is actually used. I'll include some of this in the documentation.
