### ISSUE TITLE
Small mismatch in primary demand when using CHPs and Merit

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1175]
Scenario: 1435329 (BETA)

I am testing whether:

```
SUM(V(G(primary_energy_demand),primary_demand)) - 
SUM(V(G(final_demand_group),G(energy_export), energy_flexibility_curtailment_electricity, industry_locally_available_refinery_gas_for_chemical, primary_demand))
```
is zero. I.e. total primary demand should either be traceable to final demand or export. Curtailment and refinery gas are also included in the query because these nodes currently are 'dead ends' in the graph but are not considered final demand or export.

For the present (NL2015) the above query does not return zero because of the biomass CHP with an efficiency of 111% (see: https://github.com/quintel/etengine/issues/1172).

In 1435329 I have turned this CHP off and tried to decrease all energy carriers except electricity, gas and heat as much as possible to simplify the analysis. When running the query, I get a result of 27,196,895 MJ. So 27 TJ primary demand is not account for by final demand, export, curtailment and refinery gas. My suspicion is that this is caused by CHPs, Merit and possibly the interaction between Merit and time-resolved heat: 
- When turning off the "[Large-scale gas plant for district heat (CHP)](https://beta-pro.energytransitionmodel.com/scenario/supply/electricity/gas-plants)" the difference drops to 0.00048828125 MJ. 
- When turning Merit off, the difference disappears completely: 0.0. 
- When swapping the gas CHP for a coal CHP (6 GW) the difference is 9,520,412 MJ.
- When switching on an industry CHP (where heat demand is not time-resolved) the different is again 0.00048828125 MJ.

Could this have something to do with CHP heat being available one hour after electricity production? Maybe heat produced in the final hour of the year 'disappears'/is not registered in the graph but the input fuel is? Resulting in a small mismatch in primary demand (input fuels) and final demand (heat demand) in the graph?

**Comment by michieldenhaan** [comment]
Thanks! Part of the difference is maybe that the 27.196 TJ is primary demand and the hourly heat output 'final' demand?

**Comment by antw** [comment]
Out of curiosity I checked the primary demand of all the nodes in the query with and without the large-scale CHP. I had hoped to find a node where the missing (or surplus) 27.2TJ would be... but no such luck. I'm not sure how to investigate this further, so I'll need to consider this a bit more.

### Primary demand differences for final demand nodes

```ruby
SUM(V(G(final_demand_group),G(energy_export), energy_flexibility_curtailment_electricity, industry_locally_available_refinery_gas_for_chemical, primary_demand))
```

| Node | PD w/ CHP off | PD w/ CHP on | Diff |
| :-- | --: | --: | --: |
| agriculture_final_demand_electricity | 63,792,926,019 | 56,956,193,787 | -6,836,732,232 |
| buildings_final_demand_steam_hot_water | 79,460,143,121 | 82,183,518,885 | +2,723,375,764 |
| buildings_final_demand_electricity | 146,694,520,238 | 130,973,166,518 | -15,721,353,720 |
| transport_final_demand_electricity | 456,157,303,592 | 407,270,608,234 | -48,886,695,358 |
| energy_power_sector_own_use_electricity | 32,405,689,234 | 28,932,748,989 | -3,472,940,244 |
| other_final_demand_electricity | 107,985,046 | 96,412,213 | -11,572,832 |
| households_final_demand_steam_hot_water | 178,024,471,276 | 184,125,989,740 | +6,101,518,464 |
| households_final_demand_electricity | 441,501,920,315 | 394,185,852,572 | -47,316,067,743 |
| **Total** | | | **-113,420,467,902** |

### Primary demand differences for primary demand nodes

```ruby
SUM(V(G(primary_energy_demand),primary_demand))
```

| Node | PD w/ CHP off | PD w/ CHP on | Diff |
| :-- | --: | --: | --: |
| energy_import_natural_gas | 1,141,330,535,222 | 1,258,260,881,607 | +116,930,346,385 |
| energy_production_wood_pellets | 257,572,786,405 | 27,249,169,014 | -230,323,617,391 |
| **Total** | | | **-113,393,271,006** |

### Primary demand differences for all nodes

| Node | PD w/ CHP off | PD w/ CHP on | Diff |
| :-- | --: | --: | --: |
| agriculture_final_demand_electricity | 63,792,926,019 | 56,956,193,787 | -6,836,732,232 |
| agriculture_heatpump_water_water_ts_electricity | 8,364,197,750 | 7,467,800,862 | -896,396,888 |
| agriculture_useful_demand_electricity | 55,428,728,269 | 49,488,392,925 | -5,940,335,344 |
| agriculture_useful_demand_useable_heat | 8,364,197,750 | 7,467,800,862 | -896,396,888 |
| buildings_appliances_electricity | 14,948,762,159 | 13,346,692,926 | -1,602,069,233 |
| buildings_cooling_airconditioning_electricity | 29,911,661,414 | 26,706,007,864 | -3,205,653,549 |
| buildings_cooling_collective_heatpump_water_water_ts_electricity | 425,282,964 | 379,705,093 | -45,577,871 |
| buildings_final_demand_electricity | 146,694,520,238 | 130,973,166,518 | -15,721,353,720 |
| buildings_final_demand_for_appliances_electricity | 14,948,762,159 | 13,346,692,926 | -1,602,069,233 |
| buildings_final_demand_for_cooling_electricity | 30,336,944,377 | 27,085,712,957 | -3,251,231,420 |
| buildings_final_demand_for_lighting_electricity | 67,896,970,749 | 60,620,405,190 | -7,276,565,559 |
| buildings_final_demand_for_space_heating_electricity | 33,511,842,952 | 29,920,355,444 | -3,591,487,507 |
| buildings_final_demand_for_space_heating_steam_hot_water | 79,460,143,121 | 82,183,518,885 | +2,723,375,764 |
| buildings_final_demand_steam_hot_water | 79,460,143,121 | 82,183,518,885 | +2,723,375,764 |
| buildings_lighting_efficient_fluorescent_electricity | 3,630,859,006 | 3,241,737,322 | -389,121,684 |
| buildings_lighting_led_electricity | 385,512,340 | 344,196,714 | -41,315,625 |
| buildings_lighting_standard_fluorescent_electricity | 63,880,599,403 | 57,034,471,154 | -6,846,128,249 |
| buildings_local_production_electricity | 146,694,520,238 | 130,973,166,518 | -15,721,353,720 |
| buildings_space_heater_collective_heatpump_water_water_ts_electricity | 33,511,842,952 | 29,920,355,444 | -3,591,487,507 |
| buildings_space_heater_collective_heatpump_water_water_ts_electricity_aggregator | 33,511,842,952 | 29,920,355,444 | -3,591,487,507 |
| buildings_space_heater_district_heating_steam_hot_water | 79,460,143,121 | 82,183,518,885 | +2,723,375,764 |
| buildings_space_heater_district_heating_steam_hot_water_aggregator | 79,460,143,121 | 82,183,518,885 | +2,723,375,764 |
| buildings_useful_demand_after_insulation_cooling | 30,336,944,377 | 27,085,712,957 | -3,251,231,420 |
| buildings_useful_demand_after_motion_detection_daylight_control_light | 67,896,970,749 | 60,620,405,190 | -7,276,565,559 |
| buildings_useful_demand_after_motion_detection_light | 67,896,970,749 | 60,620,405,190 | -7,276,565,559 |
| buildings_useful_demand_cooling | 30,336,944,377 | 27,085,712,957 | -3,251,231,420 |
| buildings_useful_demand_for_appliances | 16,700,791,145 | 15,098,721,912 | -1,602,069,233 |
| buildings_useful_demand_for_space_heating | 112,971,986,073 | 112,103,874,329 | -868,111,744 |
| buildings_useful_demand_for_space_heating_after_insulation | 112,971,986,073 | 112,103,874,329 | -868,111,744 |
| buildings_useful_demand_for_space_heating_after_insulation_and_solar_thermal | 112,971,986,073 | 112,103,874,329 | -868,111,744 |
| buildings_useful_demand_light | 67,896,970,749 | 60,620,405,190 | -7,276,565,559 |
| energy_chp_combined_cycle_network_gas | -0 | 501,130,055,935 | +501,130,055,935 |
| energy_distribution_steam_hot_water | 257,484,614,398 | 266,309,508,625 | +8,824,894,228 |
| energy_distribution_wood_pellets | 257,572,786,405 | 27,249,169,014 | -230,323,617,391 |
| energy_heat_burner_wood_pellets | 257,484,614,398 | 27,160,997,006 | -230,323,617,391 |
| energy_heat_network_storage | -0 | 73,944,023,594 | +73,944,023,594 |
| energy_import_natural_gas | 1,141,330,535,222 | 1,258,260,881,607 | +116,930,346,385 |
| energy_national_gas_network_natural_gas | 1,141,330,535,222 | 1,258,260,881,607 | +116,930,346,385 |
| energy_power_combined_cycle_network_gas | 1,140,660,344,442 | 756,460,634,892 | -384,199,709,550 |
| energy_power_hv_network_electricity | 1,140,660,344,442 | 1,018,414,982,313 | -122,245,362,130 |
| energy_power_lv_network_electricity | 588,304,425,598 | 525,255,431,303 | -63,048,994,295 |
| energy_power_mv_distribution_network_electricity | 1,108,254,655,209 | 989,482,233,323 | -118,772,421,885 |
| energy_power_mv_transport_network_electricity | 1,108,254,655,209 | 989,482,233,323 | -118,772,421,885 |
| energy_power_sector_own_use_electricity | 32,405,689,234 | 28,932,748,989 | -3,472,940,244 |
| energy_power_transformer_lv_mv_electricity | 588,304,425,598 | 525,255,431,303 | -63,048,994,295 |
| energy_power_transformer_mv_hv_electricity | 1,108,254,655,209 | 989,482,233,323 | -118,772,421,885 |
| energy_production_aggregator_steam_hot_water | 257,484,614,398 | 266,336,705,521 | +8,852,091,123 |
| energy_production_wood_pellets | 257,572,786,405 | 27,249,169,014 | -230,323,617,391 |
| energy_transmission_steam_hot_water | -0 | 239,175,708,515 | +239,175,708,515 |
| energy_treatment_natural_gas | 1,141,330,535,222 | 1,258,260,881,607 | +116,930,346,385 |
| households_apartments_useful_demand_for_space_heating | 92,409,367,439 | 87,484,764,140 | -4,924,603,299 |
| households_apartments_useful_demand_for_space_heating_after_insulation | 92,409,367,439 | 87,484,764,140 | -4,924,603,299 |
| households_appliances_clothes_dryer_electricity | 8,848,625,763 | 7,900,312,388 | -948,313,375 |
| households_appliances_computer_media_electricity | 11,798,167,684 | 10,533,749,851 | -1,264,417,833 |
| households_appliances_dishwasher_electricity | 7,373,854,802 | 6,583,593,657 | -790,261,146 |
| households_appliances_fridge_freezer_electricity | 26,545,877,289 | 23,700,937,164 | -2,844,940,124 |
| households_appliances_other_electricity | 10,323,396,723 | 9,217,031,119 | -1,106,365,604 |
| households_appliances_television_electricity | 11,798,167,684 | 10,533,749,851 | -1,264,417,833 |
| households_appliances_vacuum_cleaner_electricity | 5,899,083,842 | 5,266,874,925 | -632,208,917 |
| households_appliances_washing_machine_electricity | 7,373,854,802 | 6,583,593,657 | -790,261,146 |
| households_cooker_resistive_electricity | 30,464,406,188 | 27,199,514,597 | -3,264,891,591 |
| households_cooling_airconditioning_electricity | 11,540,635,906 | 10,303,817,932 | -1,236,817,973 |
| households_cooling_heatpump_ground_water_electricity | 257,531,778 | 229,931,918 | -27,599,860 |
| households_corner_houses_useful_demand_for_space_heating | 57,617,300,840 | 54,546,807,473 | -3,070,493,367 |
| households_corner_houses_useful_demand_for_space_heating_after_insulation | 57,617,300,840 | 54,546,807,473 | -3,070,493,367 |
| households_detached_houses_useful_demand_for_space_heating | 92,358,861,481 | 87,436,949,704 | -4,921,911,777 |
| households_detached_houses_useful_demand_for_space_heating_after_insulation | 92,358,861,481 | 87,436,949,704 | -4,921,911,777 |
| households_final_demand_electricity | 441,501,920,315 | 394,185,852,572 | -47,316,067,743 |
| households_final_demand_for_appliances_electricity | 89,961,028,589 | 80,319,842,612 | -9,641,185,977 |
| households_final_demand_for_cooking_electricity | 30,464,406,188 | 27,199,514,597 | -3,264,891,591 |
| households_final_demand_for_cooling_electricity | 11,798,167,684 | 10,533,749,851 | -1,264,417,833 |
| households_final_demand_for_hot_water_electricity | 45,137,237,742 | 40,299,848,593 | -4,837,389,149 |
| households_final_demand_for_hot_water_steam_hot_water | 26,384,782,616 | 27,289,080,981 | +904,298,365 |
| households_final_demand_for_lighting_electricity | 17,697,251,526 | 15,800,624,776 | -1,896,626,750 |
| households_final_demand_for_space_heating_electricity | 246,443,828,587 | 220,032,272,143 | -26,411,556,444 |
| households_final_demand_for_space_heating_steam_hot_water | 151,639,688,661 | 156,836,908,760 | +5,197,220,099 |
| households_final_demand_steam_hot_water | 178,024,471,276 | 184,125,989,740 | +6,101,518,464 |
| households_lighting_efficient_fluorescent_electricity | 2,889,955,215 | 2,580,236,706 | -309,718,510 |
| households_lighting_incandescent_electricity | 14,747,709,605 | 13,167,187,313 | -1,580,522,291 |
| households_lighting_led_electricity | 59,586,705 | 53,200,757 | -6,385,949 |
| households_locally_available_electricity | 441,501,920,315 | 394,185,852,572 | -47,316,067,743 |
| households_semi_detached_houses_useful_demand_for_space_heating | 45,779,469,513 | 43,339,828,026 | -2,439,641,487 |
| households_semi_detached_houses_useful_demand_for_space_heating_after_insulation | 45,779,469,513 | 43,339,828,026 | -2,439,641,487 |
| households_space_heater_district_heating_steam_hot_water | 151,639,688,661 | 156,836,908,760 | +5,197,220,099 |
| households_space_heater_district_heating_steam_hot_water_aggregator | 151,639,688,661 | 156,836,908,760 | +5,197,220,099 |
| households_space_heater_electricity | 246,443,828,587 | 220,032,272,143 | -26,411,556,444 |
| households_space_heater_electricity_aggregator | 246,443,828,587 | 220,032,272,143 | -26,411,556,444 |
| households_terraced_houses_useful_demand_for_space_heating | 109,918,517,975 | 104,060,831,560 | -5,857,686,414 |
| households_terraced_houses_useful_demand_for_space_heating_after_insulation | 109,918,517,975 | 104,060,831,560 | -5,857,686,414 |
| households_useful_demand_cooking_useable_heat | 30,464,406,188 | 27,199,514,597 | -3,264,891,591 |
| households_useful_demand_for_cooling | 11,798,167,684 | 10,533,749,851 | -1,264,417,833 |
| households_useful_demand_for_hot_water_after_solar_heater | 71,522,020,358 | 67,588,929,573 | -3,933,090,784 |
| households_useful_demand_for_space_heating_after_insulation | 398,083,517,247 | 376,869,180,903 | -21,214,336,345 |
| households_useful_demand_hot_water | 71,522,020,358 | 67,588,929,573 | -3,933,090,784 |
| households_useful_demand_light | 17,697,251,526 | 15,800,624,776 | -1,896,626,750 |
| households_water_heater_district_heating_steam_hot_water | 26,384,782,616 | 27,289,080,981 | +904,298,365 |
| households_water_heater_district_heating_steam_hot_water_aggregator | 26,384,782,616 | 27,289,080,981 | +904,298,365 |
| households_water_heater_resistive_electricity | 45,137,237,742 | 40,299,848,593 | -4,837,389,149 |
| households_water_heater_resistive_electricity_aggregator | 45,137,237,742 | 40,299,848,593 | -4,837,389,149 |
| other_electricity_for_electricity | 107,985,046 | 96,412,213 | -11,572,832 |
| other_final_demand_electricity | 107,985,046 | 96,412,213 | -11,572,832 |
| other_useful_demand_electricity | 107,985,046 | 96,412,213 | -11,572,832 |
| transport_car_using_electricity | 171,973,880,423 | 153,543,320,098 | -18,430,560,326 |
| transport_final_demand_electricity | 456,157,303,592 | 407,270,608,234 | -48,886,695,358 |
| transport_final_demand_for_road_electricity | 456,157,303,592 | 407,270,608,234 | -48,886,695,358 |
| transport_truck_using_electricity | 284,183,423,169 | 253,727,288,136 | -30,456,135,032 |
| transport_useful_demand_cars | 171,973,880,423 | 153,543,320,098 | -18,430,560,326 |
| transport_useful_demand_freight_tonne_kms | 284,183,423,169 | 253,727,288,136 | -30,456,135,032 |
| transport_useful_demand_passenger_kms | 171,973,880,423 | 153,543,320,098 | -18,430,560,326 |
| transport_useful_demand_trucks | 284,183,423,169 | 253,727,288,136 | -30,456,135,032 |

**Comment by michieldenhaan** [comment]
I modified the scenario a bit to use coal power plants / CHPs instead of gas. This simplifies the analysis a bit because coal doesn't have distribution losses (so final demand = primary demand, except if conversion took place). ID: 1436077.

Running the above query results in a diff of 32,488,799.49243164 MJ.

Looking at all the positive steam hot water final demand nodes I get these numbers. (Note: there are no heat distribution or storage losses in this scenario):
| key                                     | demand            | primary_demand_of_coal | 
|-----------------------------------------|-------------------|------------------------|
| households_final_demand_steam_hot_water | 83315452557.35037 | 149319264285.63873
| buildings_final_demand_steam_hot_water  | 71514128809.02356 | 128168746277.18398

There is only one heater with coal input supplying steam hot water: `energy_chp_ultra_supercritical_coal`. This node has an electricity efficiency of 0.4 and heat efficiency of 0.15.

| key                                 | input_of_coal      | primary_demand_of_coal | 
|-------------------------------------|---------------------------|--------------------|
| energy_chp_ultra_supercritical_coal  | 1017574118854.3531 | 1017574118854.3531     | 

I would expect that `0.15 / (0.15 + 0.4) = 0.272727272727273` of the coal input of the CHP is assigned as primary demand to the steam hot water output. Households and buildings are the only sectors using this heat and there are no losses, so this should correspond to the primary demand of coal for these nodes. However,  `0.272727272727273*1017574118854.3531 = 277520214233.0057` and, as the first table shows, the primary demand returned by the model is `149319264285.638 + 128168746277.183 = 277488010562.821`. The diff is 32,203,670.1840, which is earily close to 32,488,799.49243164 (maybe lack of precision plays a role here?).

**Comment by antw** [comment]
> Could this have something to do with CHP heat being available one hour after electricity production?

Pleasingly, this does appear to be the explanation. In the period around the beginning of the calculated year (April 1st), the electricity and heat output of the CHP is constant: 13.3 GW electricity output to 4.9 GW heat output. In the first hour of the calculated year, however, the heat output is zero.

| Time | Electricity output (MW) | Heat output (MW) |
| :-- | --: | --: |
| 31 March 22:00 | 13,310.1 | 4,991.2875 |
| 31 March 23:00 | 13,310.1 | 4,991.2875 |
| **1 April 00:00 (Start of calculated year)** | **13,310.1** | **0.0** |
| 1 April 01:00 | 13,310.1 | 4,991.2875 |
| 1 April 02:00 | 13,310.1 | 4,991.2875 |

Try it yourself by using to Ruby in the sandbox:

```ruby
future:EACH(
  V(energy_chp_ultra_supercritical_coal, electricity_output_curve).rotate(2155).take(10),
  V(energy_chp_ultra_supercritical_coal, steam_hot_water_output_curve).rotate(2155).take(10)
)
```

The heat output is zero for this hour because the CHP depends on the electricity output load to determine the amount of heat generated. Heat in hour _n_ is based on the electricity load in hour _n-1_. In the first hour of the calculation, there is no _n-1_, therefore the heat load is zero.

**This is 17.97 TJ of "missing" heat:** 4,991.2875 MW × 3600 = 17,968,635 MJ

The heat curve is missing 17.968 TJ of heat due to the first hour of heat depending on the electricity curve. The node demand _isn't_ missing this heat. Essentially, the node outputs this 17.9 TJ heat – as the node demand is based on the merit order, which knows nothing about the missing heat – even though this heat doesn't exist in the hourly heat network calculation. In the _hourly_ heat network calculation, this 17.9 TJ is presumably generated by something else (likely [the wood pellet burner](https://beta-engine.energytransitionmodel.com/inspect/1436077/graphs/energy/nodes/energy_heat_burner_wood_pellets), which is dispatchable).

In our meeting earlier today, we also noted that the [energy_production_aggregator_steam_hot_water](https://beta-engine.energytransitionmodel.com/inspect/1436077/graphs/energy/nodes/energy_production_aggregator_steam_hot_water) node has a slight mismatch between input and output. The node receives 17,968,634.979 MJ more energy than it outputs (all through reversed flexible edges). This is exactly the amount of surplus heat output by the CHP.

---

If we move left by one node to [energy_transmission_steam_hot_water](https://beta-engine.energytransitionmodel.com/inspect/1436077/graphs/energy/nodes/energy_transmission_steam_hot_water), we can calculate the ratio of demand to primary demand:

```ruby
future:DIVIDE(
  V(energy_transmission_steam_hot_water, primary_demand_of_coal),
  V(energy_transmission_steam_hot_water, demand)
)
# => 1.8181818181818181
```

Every 1 MJ of demand on the transmission node increases the primary demand of coal by 1.81MJ.

17.97 TJ heat equates to **32.67 TJ primary demand for coal**. This is not exactly the missing amount (32.48 TJ), but it is _very_ close.

---

### Fix

I don't really know. 🤷‍♂️

In theory we could adjust the heat output share down very slightly to ensure this extra energy doesn't leave the node. Maybe we'd increase loss to compensate – to ensure `output == input` – but doing so relies on all affected nodes having a loss output. This approach feels hacky.

A longer-term, but perhaps better, fix would be to calculate Fever/Merit/Heat for 8761 hours instead of 8760, essentially calculating 1st April 00:00 twice, discarding the first hour after the calculation is complete. However this might have fallout for flexibility, and storage in particular: excess energy from the first hour could be used/stored, but never accounted for. I think this may also be an imperfect solution.

**Comment by ChaelKruip** [comment]
Thanks for the excellent investigation and write up @antw! And kudos to @michieldenhaan for the idea to investigate the 'n-1 hour hypothesis' 😄 

> This approach feels hacky.

I agree.

> A longer-term, but perhaps better, fix would be to calculate Fever/Merit/Heat for 8761 hours instead of 8760, essentially calculating 1st April 00:00 twice, discarding the first hour after the calculation is complete. However this might have fallout for flexibility, and storage in particular: excess energy from the first hour could be used/stored, but never accounted for. This might be just as bad (or worse) than what we're trying to fix.

This still seems to be the more promising solution direction IMO. 

My memory is a but fuzzy on why it was necessary to only make the heat available in the next hour anyways (although I recall being convinced at the time). Synchronising the heat and electricity output curves is something that I'd like to revisit as it would be the elegant way to fix this right?

**Comment by antw** [comment]
> My memory is a but fuzzy on why it was necessary to only make the heat available in the next hour anyways

In each hour, heat network loads are computed before electricity. This means any heat network participant which depends on electricity has a heat load which lags one hour behind electricity.

```
calculate heat network for hour 0
calculate merit for hour 0

calculate heat network for hour 1
calculate merit for hour 1

...
```

There are two occasions in the model where is the case:

1. Heat is generated for the network as a result of excess electricity (P2H).
2. The participant has a heat output curve based on the electricity curve. This is the case for the CHP.

The CHP has:

```
- merit_order.type = producer
- merit_order.subtype = dispatchable

- heat_network.type = producer
- heat_network.subtype = must_run
- heat_network.group = self: electricity_output_curve
```

The CHP is dispatchable in the merit order, which means when the heat network is calculated for hour 0 it doesn't know what the electricity load will be for hour 0. In hour 1, the heat network doesn't know the electricity load of hour 1, etc.

The solution is that participants look at the electricity load for the _previous_ hour when calculating their heat output. The heat load in hour 1 is based on the electricity load in hour 0 (which _is_ known), the heat in hour 2 uses the electricity load from hour 1, and so on. Ultimately this means we cannot calculate a heat load for hour 0, because there is no such hour as -1.

**Comment by michieldenhaan** [comment]
Thanks @antw! Great work 🎉 

> A longer-term, but perhaps better, fix would be to calculate Fever/Merit/Heat for 8761 hours instead of 8760, essentially calculating 1st April 00:00 twice, discarding the first hour after the calculation is complete. However this might have fallout for flexibility, and storage in particular: excess energy from the first hour could be used/stored, but never accounted for. This might be just as bad (or worse) than what we're trying to fix.

I agree with your worries, it could prove to be very tricky to get this right and possibly lead to new problems.

> We could adjust the heat output share down very slightly to ensure this extra energy doesn't leave the node. Maybe we'd increase loss to compensate – to ensure output == input – but doing so relies on all affected nodes having a loss output. This approach feels hacky.

I agree this isn't ideal, but it does sounds like a relatively 'simple' fix. Also, I don't see that many alternatives that don't require fundamentally rethinking our hourly setup.. We could maybe add a spec to ensure that all nodes with both electricity and heat output also have a loss output?

If I understand this correctly, we basically have two options:
- Adjust efficiencies in the graph to match the hourly production in hour 1-8760 (as proposed by @antw)
- Adjust the hourly calculations to ensure production is in line with the efficiencies in the graph

The second could mean running the whole hourly calculation, then checking if there is any 'missed' heat in the 8761th hour and if this is the case transfer this heat to the 8760th hour (i.e. post process the hourly production curve). This additional heat will (by definition?) end up getting dumped (`energy_heat_dumped_steam_hot_water`) because we already calculated the 8760th hour and hence dispatched a dispatchable heater if there was a deficit. This would ensure that the primary demand of `buildings_final_demand_steam_hot_water` + `households_final_demand_steam_hot_water` + `energy_heat_dumped_steam_hot_water` =  `energy_chp_ultra_supercritical_coal` in the graph. Also the hourly heat production curve is consistent with annual production in the graph. The 8760th hour would be a bit odd, but given that its significance is small I could live with that. (Please tell me if this option doesn't make sense)

To me, this second option doesn't sound less hacky than the first. Still, I would prefer to have some sort of short-term fix in place to guarantee that the numbers in the graph are consistent. Otherwise it is very hard to test if something else might be wrong. What do you think @ChaelKruip @antw?

**Comment by ChaelKruip** [comment]
> What do you think @ChaelKruip @antw?

I agree with what you say @michieldenhaan!

I would prefer option 2 and possibly a quick(er) fix for now in line with option 1.
