### ISSUE TITLE
Weighted_carrier_co2_per_mj broken on BETA?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1178]
Query:
```
TXT_TABLE(  V(
                transport_ship_using_lng_mix,
                transport_freight_train_using_electricity,
                transport_truck_using_hydrogen,
                transport_truck_using_electricity,
                transport_truck_using_lng_mix,
                transport_truck_using_compressed_natural_gas,
                  transport_ship_using_diesel_mix,
                  transport_freight_train_using_diesel_mix,
                  transport_truck_using_diesel_mix,
                  transport_truck_using_gasoline_mix), key, weighted_carrier_co2_per_mj)
```

BETA:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/32056448/119491238-fbdb6600-bd5d-11eb-92e8-70fd6113be8c.png">

PRO:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/32056448/119491271-03027400-bd5e-11eb-8d1a-fae356b147f7.png">

Edit: Same goes for `weighted_carrier_cost_per_mj`. It seems to occur for nodes with a 'mixed' carrier like diesel mix, network gas etc.

**Comment by marliekeverweij** [comment]
This could be the reason for the change in marginal costs for gas power plants:

![Screenshot 2021-05-25 at 14 02 53](https://user-images.githubusercontent.com/32833996/119496364-b7eb5f80-bd63-11eb-95c1-23597293dd5c.png)
