### ISSUE TITLE
Update costs calculation methods

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etengine#1187]
For [the new categories in the costs chart](https://github.com/quintel/etmodel/issues/3779) we have to revise our cost calculation methods. Additionally, there are some other issues that have to be picked up. I am writing them all here as they are related. Feel free to split them up when necessary.

**Split up the total costs**
At the moment fuel costs, CO2 costs and CCUS costs are included in the total costs calculation. With the new categories these should be split up.
For example for a industrial burner:
- the fuel costs should be part of the "Energy sources & import"
- the investment and O&M costs should be part of the "Buildings/installations" category
- the CO2 ETS costs and CCUS investment should be part of the "CO2-infrastructure, CCUS, compenation"

For this we need the following methods:
- investment costs excluding CCS
- variable costs excluding fuel costs

**Avoid double-counting of fuel costs for produced carriers**
We should avoid the double-counting of fuel costs. For example hydrogen that is produced with an SMR and then used in an industrial burner. In this case we should only include the costs for the gas used in the SMR and not the hydrogen fuel costs for the industrial burner. This double-counting is mostly the case for hydrogen as hydrogen has its own price. For electricity the price is set to zero in the graph. For heat double-counting is probably not happening at the moment, but we should check.

**Export costs must be settled with import costs** 
At the moment the costs for export fuels are included in the total costs calculation (see [this issue](https://github.com/quintel/etmodel/issues/2204)). These costs for exported fuels should not be included in the "Energy sources & import" category. 

**Improve naming of the costs calculation methods**
At the moment the distinction between total costs (over lifetime) methods and yearly total costs methods is not clear. The method `total_costs_per` calculates the yearly total costs and the `total_investment_over_lifetime` calculate the total investment costs of lifetime, if I am right. It would be great if the names would better match with the method :) 

Notifying @MartLubben @ChaelKruip

**Comment by MartLubben** [comment]
Hi @antw,

Thanks for the clear explanation. I have some questions in **bold**. I think that we could already start with the `variable costs excluding fuel costs`. 

> `total_initial_investment - ccs_investment `
>This could be implemented either directly in the gqueries

- I agree that this can be implemented in the queries and I am in favour of that. It will make it very clear that CCS is (as an exception) not part of the investment costs. **Are these investment costs per year? Or in total?**

>Personally, I'm not convinced it's worth renaming all of these methods, but not doing so would make the naming of total costs inconsistent with all the others. Can we not assume anything cost-related is per year by default and only include a time period in the name ("over lifetime") in cases where this isn't true?

- I like your thinking. Also I hear that it is not that difficult to change the names. I will maybe come back on this, but it does not have the highest priority. **Is it correct that is does not create a lot of fallout if we change the names?**

- The double counting and and the settlement of export and import is more relevant for the query making than to the method change I think.

**Comment by antw** [comment]
> Is it correct that it does not create a lot of fallout if we change the names?

It creates a *great deal* of fallout, but most of it can be automated. Anywhere the name is referenced also needs to be changed to reflect the new name; there are probably a great many queries that use these cost methods.

The change in ETSource can be automated with a global search and replace, but it still needs a human review to ensure that the change doesn't break anything.

> > `total_initial_investment - ccs_investment`
>
> Are these investment costs per year? Or in total?

:wink:

I believe both are one-off costs, paid then the plant is built.

**Comment by noracato** [comment]
> I think that we could already start with the variable costs excluding fuel costs.

What would exactly be part of this method? As I understand the `variable_costs` are now:
```
weighted_carrier_costs + co2_emissions_costs + variable_operation_and_maintenance_costs
```

If you don't want to include the fuel and co2 emissions, couldn't you just use the [`variable_operation_and_maintenance_costs`](https://github.com/quintel/etengine/blob/dc293e2ee2ae6a967e575a306d0db718d86c04dd/app/models/qernel/node_api/cost.rb#L278-L290)? Or am I missing something?

**Comment by MartLubben** [comment]
Very good question. I am not sure:
We need to get from a node the variable costs (ex fuel ex ccs), the yearly fixed costs incl investment (ex fuel ex ccs) and the CCS costs. 

I have three questions @michieldenhaan:
1. Is co2_emissions_costs equal to all CCS costs?
2. Is variable_operation_and_maintenance_costs equal to variable costs (ex fuel, ex ccs)?
3. Do we have a method for yearly investment/fixed costs costs (ex fuel, ex ccs)?

**Comment by noracato** [comment]
> 1. Is co2_emissions_costs equal to all CCS costs?

Don't think so, you can check the description of the method out here:
https://github.com/quintel/etengine/blob/dc293e2ee2ae6a967e575a306d0db718d86c04dd/app/models/qernel/node_api/cost.rb#L262-L276

> 2.   Is variable_operation_and_maintenance_costs equal to variable costs (ex fuel, ex ccs)?

I see now there _is ccs_ in the `variable_operation_and_maintenance_costs`: 
```
variable_operation_and_maintenance_costs_per_full_load_hour + variable_operation_and_maintenance_costs_for_ccs_per_full_load_hour
```
That css part has to go then? So we end up with just `variable_operation_and_maintenance_costs_per_full_load_hour` and possibly parts of `co2_emissions_costs`.


> 3. Do we have a method for yearly investment/fixed costs costs (ex fuel, ex ccs)?

There is a method called `fixed_costs` that "Returns the total fixed costs for one plant per year." I don't see any mention of fuel or CCS in there.

**Comment by MartLubben** [comment]
What is needed is the **yearly** costs of:

- CAPEX = CAPEX ex CCS + CAPEX of CCS
- OPEX  =  OPEX (ex fuel, ex CCS), OPEX CCS, fuels costs. 

CAPEX of CCS = annualised ccs_investment
CAPEX (ex CCS) = annualised total investment - annualised CCS investment
OPEX CCS = variable costs of CCS + CO2 credits 
OPEX (ex fuel, ex CCS) = variable O&M - Variable CCS O&M + fixed O&M
