### ISSUE TITLE
Derive heat and electricity output capacity from input capacity and efficiencies?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etengine#1189]
Currently the `heat_output_capacity` and `electricity_output_capacity` is only available for nodes which have these attributes explicitly defined in the node file on ETSource. For CHPs we are thinking about removing these attributes from the node files and defining `typical_input_capacity` instead. The reason for this is that the heat and electricity output _efficiencies_ are now dynamic (dataset dependent). This means that the (ratio between) `heat_output_capacity` and `electricity_output_capacity` should also be dynamic, otherwise `heat_output_capacity / heat efficiency` results in a different total input capacity than `electricity_output_capacity / electricity efficiency`. By removing `heat_output_capacity` and `electricity_output_capacity` from the node all together and instead defining `typical_input_capacity`, we avoid overdefining capacities.

Still, it would be nice if ETEngine would be able to set/calculate `heat_output_capacity` and `electricity_output_capacity` for nodes that have a `typical_input_capacity` and a heat/electricity efficiency. This is because the `output_capacity` attributes are used in quite some queries and it would be cumbersome to replace this by `typical_input_capacity * electricity_output_conversion`. @antw Is this possible / do you see any downsides of doing this?

**Comment by antw** [comment]
I expect this would be fine.
