### ISSUE TITLE
Support "internal" custom curve uploads

### ISSUE THREAD

**Issue by antw** [quintel/etengine#1195]
We need to support additional custom curves in the ETM: a client requested the ability to upload their own custom heat demand and insulation profiles.

These are not available in ETModel due to their complexity and number: there are five types of household, each of which requires three separate demand / insulation curves. It will be easy for someone to shoot themself in the foot by uploading curves that don't make sense.

Therefore, while we must support uploading custom heat curves, we don't want them to be available in ETModel. We will add an "advanced" or "internal" attribute to the curve config in ETSource, then omit any of these curves [from the API](https://docs.energytransitionmodel.com/api/custom-curves#get-all-custom-curves) by default. An API user will have to pass an additional query param to see the available internal curves.

- [x] Add attribute to curve config in ETSource
- [x] Update API to omit internal curves
- [x] Update API to include internal curves when providing a query param
- [x] *(Maybe)* Include a customised internal curve in the API response
- [ ] *(Maybe)* Update ETModel curve upload UI to disable uploading or removing a customised internal curve
- [x] Update documentation

**Comment by antw** [comment]
@MartLubben I've completed these changes and sent them to beta.

I've updated the contributor documentation [explaining how to add or change which curves can be customised by visitors](https://docs.energytransitionmodel.com/contrib/user-curves/). The "[Internal curves](https://docs.energytransitionmodel.com/contrib/user-curves/#internal-curves)" section tells you how to mark a custom curve as "internal" – for use by QIs and experienced users.

Internal curves will not appear in the upload form in ETModel but can be customised [through the API](https://docs.energytransitionmodel.com/api/custom-curves).

---

FYI @noracato and @redekok for quintel/scenario-tools#7.

**Comment by MartLubben** [comment]
@antw . You are a hero. :)
