### ISSUE TITLE
Add CSV download for cost parameters

### ISSUE THREAD

**Issue by noracato** [quintel/etengine#1199]
For the costs projects a new CSV download is required, containing cost parameters for all nodes that are in a _costs_ group. The CSV is supposed to be structured like this:

|group|subgroup|key|CAPEX (ex ccs)|OPEX (ex ccs)|CAPEX ccs|OPEX ccs|Total|
|--- | --- |--- | --- | --- | --- |--- | --- |
|costs_building_and_installations|households|households_cooling_airconditioning_electricity|100|100|0|0||
|...|...|...|...|...|...|...||
|costs_building_and_installations|households|Total|||||300|
|...|...|...|...|...|...|...||

These totals are based on queries with key _group_subgroup_. Other costs queries that do not have anything to do with the node groups, should be able to be incorporated also.

**Comment by marliekeverweij** [comment]
@DorinevanderVlies Github automatically wants to close this issue. Is that okay or not?
I have pinned / saved this issue for now.

**Comment by DorinevanderVlies** [comment]
It is work in progress. We're currently testing the changes made in the cost project. 
Related to: f5f1ca35c208f42226069104fe9f6da3b09a7b9c, 9667c247eedbb1ce419b47a7df33881e4e05f564 and d4a509d6d17e0436e9da9489dd19b4b7b26d1a20
