### ISSUE TITLE
Add costs per MW installed capacity to flow battery costs calculation

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1207]
Both the storage volume and the installed capacity of the new battery type, flow batteries, can be adjusted separately. This means that the investment costs need to update accordingly.

Two components therefore need to be included in the total investment costs calculation of the flow batteries: `installed capacity * costs per MW` + `storage volume * costs per MWh`. The second component already exists, but the first has to be added.

The parameters should be fixed for the node and are based on the node source analysis.

**Comment by antw** [comment]
I've pushed commits to ETEngine and ETSource **innovations-flex** branches that enable a new node attribute: **fixed_costs_per_mw_input_capacity**. This allows you to set a cost in euros per MW of installed input capacity.

This...

* can be [queried on its own](https://github.com/quintel/etengine/blob/7c999f7cfe867c5576a190860e30a94dc27a8bf8/app/models/qernel/node_api/cost.rb#L129) with `V(node_key, capacity_costs)` (euros per plant)
* is included in [the node's initial investment costs](https://github.com/quintel/etengine/blob/7c999f7cfe867c5576a190860e30a94dc27a8bf8/app/models/qernel/node_api/cost.rb#L40-L44) `V(node_key, total_initial_investment)` (euros per plant)

Storage costs are already included in the initial investment costs, and can be queried independently with `V(node_key, storage_costs)`.

For example:

```
- fixed_costs_per_mw_input_capacity = 1000  # 1000 EUR per MW input capacity
- typical_input_capacity = 2                # 2 MW capacity

- storage.volume = 5                        # 5MWh volume
- storage.cost_per_mwh = 1500               # 1500 EUR per MWh volume
```

This would give you:

* a **capacity_costs** of 1000 × 2 = 2000
* a **storage_costs** of 1500 × 5 = 7500
* a **total_investment_costs** of 9500 (assuming initial_investment, ccs_investment, and cost_of_installing are all zero).

@mabijkerk When you have time, can you give this a spin and see if it meets your needs?

**Comment by mabijkerk** [comment]
Looks great! My aim is to start working on these batteries next week, so I'll let you know how it goes.

**Comment by mabijkerk** [comment]
I'm implementing the new technology. One issue that I'm running into is that I want to also be able to adjust the input capacity and the storage volume separately, like this:
![Screenshot 2021-12-24 at 10 17 07](https://user-images.githubusercontent.com/67338510/147339053-48f99d30-a8bc-42f2-879a-97bc03d1ce39.png)

I expect that means that I cannot use `number_of_units` in my inputs, because this would update both input capacity and storage volume. My input statement for the capacity slider therefore looks like this:
```
- query =
    UPDATE(
      V(energy_flexibility_flow_batteries_electricity),
      typical_input_capacity,
      USER_INPUT()
    )
```

My input statement for the volume slider looks like this:
```
- query =
    UPDATE(
      V(energy_flexibility_flow_batteries_electricity),
      "storage.volume",
      USER_INPUT()
    )
```

The capacity slider seems to work, but when I try to adjust the volume slider, the model crashes and I get this error message: "undefined method `storage.volume=' for #"

Am I missing something here @antw, can storage.volume only be updated through the number of units?

**Comment by antw** [comment]
> The capacity slider seems to work, but when I try to adjust the volume slider, the model crashes and I get this error message: "undefined method `storage.volume=' for #"

You can certainly do this, but the query needs to be a little different:

```
- query =
    UPDATE(
      V(energy_flexibility_flow_batteries_electricity, storage),
      "volume",
      USER_INPUT()
    )
```

### Explanation

Most attributes on objects in the graph exist directly on the object you're fetching: typical_input_capacity, number_of_units, availability, demand, etc, all exist directly on the node. However, some attributes are themselves objects with their own attributes: merit_order, fever, storage. Think of it as a tree of attributes:

```yaml
availability: 1
demand: 3001
merit_order:
  type: producer
  subtype: dispatchable
number_of_units: 1337
storage:
  cost_per_mwh: 10
  volume: 5000
typical_input_capacity: 100
```

When you want to update a value on one of these sub-objects, you must first fetch that sub-object (see the second value in `V(...)`) and update _that_. In the above query, we use `V` to fetch the storage attribute on the flow battery node and then use `UPDATE` to change the volume.

I suspect we could change `UPDATE` to support the syntax you were using ("storage.volume"). Maybe that would be less surprising to authors of inputs and queries?

**Comment by mabijkerk** [comment]
Thanks for the explanation!

> I suspect we could change UPDATE to support the syntax you were using ("storage.volume"). Maybe that would be less surprising to authors of inputs and queries?

It's fine for me to keep it as is, it's just that I didn't know yet that this was the proper syntax. Perhaps we can add it to this [GQL documentation](https://github.com/quintel/documentation/blob/e4ad8076be511b5b3953909e268016c9ecd41438/general/GQL.md)? Even though it seems a bit outdated.

**Comment by mabijkerk** [comment]
Works like a charm!
