### ISSUE TITLE
Make protected scenarios read-only

### ISSUE THREAD

**Issue by antw** [quintel/etengine#1209]
During a discussion with Kalavasta, we asked ourselves if protected scenarios should be read-only.

Currently, a protected scenario is one flagged to be migrated whenever an update to the model changes. In the past, protected scenarios would also not be deleted during periodic clean-ups of old scenarios; however, we no longer do these clean-ups and all old scenarios are retained.

We should consider making protected scenarios read-only to prevent malicious actors from editing scenarios that belong to another user, featured scenarios, or even accidental changes to a saved scenario.

This has a downside: once a scenario is marked as read-only, it will become immutable and the owner will not be able to make any further changes, nor set the scenario *not* to be read-only (single sign-on authentication might eventually get around this). I do not think this will have any impact on workflows in the ETM, but we should double-check that it doesn't break transition path charts, and might also consider the impact on API users.

The ETM would need a small update to disable all sliders when the active scenario is read-only.

### Re-use `protected`

We can re-use the existing `protected` attribute whose meaning will change from "migrate this scenario when the model changes" to "migrate this scenario when the model changes _and_ make it read-only". This is a simple option but risks breaking the workflow of some API users.

### Add separate attributes

We can add two new attributes to a scenario:

* `keep_current` – simply a renamed `protected`
* `read_only` – makes the scenario read-only

This means an API user could indicate that a scenario should be migrated when the model changes but is not made read-only. I'm not sure how frequently this distinction would really be needed.

We would also need to add a migration to ensure that all ETModel saved and featured scenarios are updated to be read-only.

**Comment by antw** [comment]
@ChaelKruip @noracato I've updated the issue description with our options. I'm curious what you think?

**Comment by noracato** [comment]
Very nice! I think I'm more in favour of re-using the `protected` attribute.

>  I'm not sure how frequently this distinction would really be needed.

Me neither. If I'm correct we migrate all (fairly) recently accessed scenarios regardless of their protection status. So if a user is actively working on a scenario, they don't need to be worried about missing migration anyways. Marking it as 'protected' on finishing their scenario then does exactly what you'd want when finishing: freeze and keep around. When we would have the two flags, the user would have to remember to set both on finishing.

> single sign-on authentication might eventually get around this

One more argument for the re-use of `protected` is that a `read-only` attribute will become obsolete when we start implementing SSO. If we think that is too far in the future though, this argument of course can be ignored :)

> This is a simple option but risks breaking the workflow of some API users.

Yep. That's the downside. A quick scan of the production database shows ~165 scenarios that were touched in the last year, were marked protected, and were not from ETModel, MYC or the report. Of these scenarios only 70 have a unique name (and those names remind me _a lot_ of projects Roos and Dorine worked on). So what I'm trying to say is that maybe our API users have not yet massively discovered this `protected` flag. And for the ones who did, we could give them a small adjustment period, e.g. by returning a warning with API responses for the next month and by only making protected scenario's older than a month read-only. Then, after the month has passed, we can make all protected scenarios read-only. 
Just a thought of course 🙂
