### ISSUE TITLE
Design connection fertilizer sector

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etengine#1222]

**Comment by mabijkerk** [comment]
We have a two design directions for the coupling of the fertilizer sector:

![image](https://user-images.githubusercontent.com/67338510/150337767-20fb9143-64b8-4cf3-be9f-97800e053b7e.png)

**1: Useful demand input statements**
- Allow the API input statements to affect the `industry_useful_demand_for_chemical_fertilizers_useable_heat` node for all the energetic demands with the exception of electricity.
- The demand for electricity is set in a separate input statement for the `industry_useful_demand_for_chemical_fertilizers_electricity` node.
- The non energetic demand for natural gas is set by an input statement for the `industry_useful_demand_for_chemical_fertilizers_network_gas_non_energetic` node. We can check whether different non-energetic carriers are used in the fertilizer sector in the CTM.
- **Challenge:** will the graph be able to calculate the nodes left of the useful demand nodes, such as `industry_chemicals_fertilizers_haber_bosch_process_hydrogen`, when we use this approach?
- @antw do you know how I can test approach this quickly, without having to already write all the input statements? Or perhaps you might already know whether or not this approach is feasible.

**2: Haber-Bosch input statements**

- Allow the API input statements to affect `industry_chemicals_fertilizers_haber_bosch_process_hydrogen`, `industry_chemicals_fertilizers_locally_available_hydrogen`, `industry_chemicals_fertilizers_steam_methane_reformer_hydrogen`, `industry_useful_demand_for_chemical_fertilizers_useable_heat` and `industry_useful_demand_for_chemical_fertilizers_electricity`.
- If we update the SMR node to match the specifications of MIDDEN (and the CTM) it is likely not necessary to have input statements for the SMR node.
- **Challenge:** hydrogen can only come from the central hydrogen network or from the local SMR. This means there is no local hydrogen production through electrolysis, nor other production technologies.
- The question is therefore if the CTM wants to model local electrolysis, or whether central electrolysis with updated specifications from MIDDEN is sufficient. Important to note is that central electrolysis is price-based, which might make alignment with the CTM more difficult.
- If local electrolysis is a requirement, and we have to model using the Haber-Bosch node, then we might consider changing the input value of network gas in the local SMR to zero, to model electrolysis through final demand of electricity and passing the other energetic demand through the useable heat node.
- Another option would be to add a new node for local electrolysis.
- Another option would be to add a new coupling node for a generic local production method of hydrogen.

**Comment by antw** [comment]
> 1: Useful demand input statements

> will the graph be able to calculate the nodes left of the useful demand nodes, such as industry_chemicals_fertilizers_haber_bosch_process_hydrogen, when we use this approach?

No, it won't. The graph is calculated left-to-right *except* when nodes are connected by reversed edges. As far as I can tell industry is pretty much all left-to-right.

<details>
<summary><strong>Graph example</strong></summary>

If we have a graph like this:

```
+---------------+      +-------------+
| Preset Demand |  --  | Application |
+---------------+      +-------------+
```

... demand "flows" from the preset demand node to the application node:

```
+--------------------+      +------------------+      +---------------------+
| Preset Demand (50) |  ->  | Application (??) |  ->  | Primary demand (??) |
+--------------------+      +------------------+      +---------------------+

+--------------------+      +==================+      +---------------------+
| Preset Demand (50) |  ->  | Application (50) |  ->  | Primary demand (??) |
+--------------------+      +==================+      +---------------------+

+--------------------+      +------------------+      +=====================+
| Preset Demand (50) |  ->  | Application (50) |  ->  | Primary demand (50) |
+--------------------+      +------------------+      +=====================+
```

We can't just set a demand for a random node in the middle, because the demands will be inconsistent:

```
+--------------------+      +------------------+      +---------------------+
| Preset Demand (50) |  ->  | Application (10) |  ->  | Primary demand (??) |
+--------------------+      +------------------+      +---------------------+

+--------------------+      +------------------+      +=====================+
| Preset Demand (50) |  ->  | Application (10) |  ->  | Primary demand (10) |
+--------------------+      +------------------+      +=====================+
```
</details>

I don't know of any way to set demands in the middle of the graph. We'd need to consider if we can initialize these nodes in the middle of the graph ourselves, and reverse the direction of those to the left. I doubt that's possible.

**Comment by mabijkerk** [comment]
@marliekeverweij based on the comment of @antw I suppose we have to go for design direction 2. This means we have to determine whether updating the specs of local and central SMR and central power-to-gas is sufficient for the CTM coupling.

If not, we have to decide whether we can simulate the behaviour we want with the current nodes. My guess is that the input statements required to do so will become quite complex and that it's more efficient to add a coupling node in this sector.

**Comment by mabijkerk** [comment]
Following the discussion with Kalavasta:

- After production of ammonia, further processing to fertilizers is required
- This processing step requires additional inputs, not only from useable heat and hydrogen
- The current Haber-Bosch node does not allow for those inputs
- This means that we have to translate energetic demand of i.e. network gas that is used in further processing of ammonia, from a useable heat input in the Haber-Bosch node, through a number of nodes to arrive at the proper final energetic demand for network gas by fertilizers
- These input statements are likely to become quite complex

The argumentation above strongly favours the implementation of some form of coupling node for this sector. The exact implementation of this node is up for discussion. We may want to explore if we can create the basis for production routes in this project, for example by creating a node similar to `industry_steel_production`.

**Comment by mabijkerk** [comment]
For the energetic part of the fertiliser sector I would propose the following structure, with the new node and edges marked green and the existing nodes and edges in grey:
![Untitled Diagram](https://user-images.githubusercontent.com/67338510/151958083-5dfac975-8dc8-4824-bc76-94bdc8152cfd.png)

- Total energetic demand can be set using the Haber-Bosch node, which would automatically set the share to the coupling node at a 100%
- The energetic final demand per carrier can then be set by changing the input shares of the coupling node
- **Question**: the explicit ETM modelling of the fertiliser sector attributes costs to the burner nodes, can these be assigned to the coupling node?
- **Question**: the explicit ETM modelling of the fertiliser sector assigns useful demand groups to the useable heat node, can and should this be assigned to the coupling node as well? Can it be assigned to the same coupling node or should a dual coupling node be made, as for the steel sector?

**Comment by marliekeverweij** [comment]
> Question: the explicit ETM modelling of the fertiliser sector attributes costs to the burner nodes, can these be assigned to the coupling node?

For steel indeed two coupling nodes have been added. The left one includes the costs. I expect this is also necessary for this coupling node for fertilizers? What do you think @lottevanvlimmeren @antw 

![Screenshot 2022-02-02 at 11 05 56](https://user-images.githubusercontent.com/32833996/152133281-4e46f016-91f6-40eb-a5da-e9f6137b5a52.png)

> Question: the explicit ETM modelling of the fertiliser sector assigns useful demand groups to the useable heat node, can and should this be assigned to the coupling node as well? Can it be assigned to the same coupling node or should a dual coupling node be made, as for the steel sector?

I think you mean the node-groups here (`useful_demand`& `useful_demand_heat_cold`). I do not see them being used, only for queries that are no longer used in a chart, like this one:
https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/sankey_primary,_final,_useful_demand/industry_to_useful_demand_heat_cold_in_sankey_ufp.gql

So I guess we can leave this

Two points from my side:
- I expected that we needed to include non-energetic demand as well as input for this coupling node (at the moment non-energetic gas is used in the SMR) If so, then it would also be possible to use non-energetic hydrogen from the central hydrogen network!

**Comment by mabijkerk** [comment]
> I expected that we needed to include non-energetic demand as well

You're definitely right, that's why I stated that this design only includes the energetic demand. I'm still working on the non energetic demand design.

**Comment by mabijkerk** [comment]
**Transparency**
As the discussion in https://github.com/quintel/etmodel/issues/3899 shows, the demands set by the externally coupled model need to pass through the technologies, in this case the burners, to make the coupling transparant in the frontend. This either requires adding the coupling node **between** the useful demand and the burners, or **not using** a coupling node and managing everything with input statements instead.

- Putting the coupling node **between** the useful demand and the burners is not preferred, as it would make the coupling node an integral part of the graph, through which energy is passed even when no external model is coupled. This may confuse 'normal' users of the model, and it would require some effort to reassign the shares from the useable heat node to the coupling node.
- For the fertilizer sector, **not using** a coupling node for the energetic demands would require setting the demand of the haber-bosch node and then passing it as useable heat all the way through the burner to the final demands. These input statements can become quite complex. What we would then gain in transparency in the frontend, we would lose in the backend.

The proposal is therefore to stick to the design above and add an energetic coupling node that is connected to the haber-bosch node and the final demands. This therefore removes the need to make the burner shares visible in the frontend. What do you think of this argumentation @antw?

**Non-energy use**
In the current modelling, non-energetic demand of network gas is used in the SMR and non-energetic demand of hydrogen in the haber-bosch node. This energy use is then together with the energetic demands passed through to the residual heat nodes.

The proposal is therefore to add a non-energetic coupling node, that is connected to the haber-bosch node and to the non-energetic final demands. This gives API users the most freedom in determining which part of the total energy consumption can be used as residual heat.

**Costs**
Costs can be attributed to the energetic coupling node, it has to be determined whether an additional node has to be created for this.

**Comment by mabijkerk** [comment]
**Proposed design**
![Fertilizer 1](https://user-images.githubusercontent.com/67338510/152308702-abd6720d-03d3-48be-8701-f41cee2e0fb2.png)

**Comment by lottevanvlimmeren** [comment]
> Question: the explicit ETM modelling of the fertiliser sector attributes costs to the burner nodes, can these be assigned to the coupling node?

The costs could be assigned to the coupling node. I don't think that it is necessary to add an additional coupling node for the costs. For the steel sector, it was necessary to add the additional production node for all technologies to make sure that the graph would initialise correctly. Since the additional node was already there, we decided to use it for the fixed costs as well. I don't see any reason to add an additional coupling costs node for the fertilizer sector.
