### ISSUE TITLE
Cost project: error with data export

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etengine#1231]
@noracato , we are experiencing some issues with the data export on the cost branch (capex-opex-per-unit).
Can you have a look at this? It might be cause by (wrongly) rebasing?

Notifying @lottevanvlimmeren 

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/19907658/153006077-92524c36-3989-4ad8-9f8c-142509fcdf78.png">

**Comment by noracato** [comment]
Thanks for notifying me! Yes, it was something with the rebasing. There has been a minor change in how the scenario is treated in most of the API controllers (including this one). I updated the costs download accordingly, everything should work now.
