### ISSUE TITLE
Default values of share group do not add up to 100 percent

### ISSUE THREAD

**Issue by robcalon** [quintel/etengine#1236]
**external_coupling_capture_potential**
- external_coupling_industry_chemical_refineries_ccus_capture_potential (0.0)

**external_coupling_chemicals_fertilizers_useable_heat_input**
- external_coupling_industry_chemical_fertilizers_burner_crude_oil_share (0.0)
- external_coupling_industry_chemical_fertilizers_burner_hydrogen_share (0.0)
- external_coupling_industry_chemical_fertilizers_burner_coal_share (0.0)
- external_coupling_industry_chemical_fertilizers_burner_network_gas_share (0.0)
- external_coupling_industry_chemical_fertilizers_burner_wood_pellets_share (0.0)
- external_coupling_industry_chemical_fertilizers_steam_hot_water_share (0.0)

@marliekeverweij

**Comment by marliekeverweij** [comment]
@mabijkerk could you have a look at this issue?

**Comment by mabijkerk** [comment]
**external_coupling_capture_potential**

- It seems like this input statement shouldn't have a group: the same input statements for other sub sectors don't have one either
- There is only one other edge that comes out of the molecule node (see screenshot), which is inversed flexible, meaning that both edges together will always sum to 100%
- The share_group is therefore unnecessary and is removed.

<img width="696" alt="Screenshot 2022-03-16 at 15 03 47" src="https://user-images.githubusercontent.com/67338510/158607646-3afe0708-0af2-423a-9258-4f934030947f.png">

**external_coupling_chemicals_fertilizers_useable_heat_input**

- There was a minor mistake in the input statements, which is now corrected.
