### ISSUE TITLE
possible invalid share group values by setting external coupling nodes. 

### ISSUE THREAD

**Issue by robcalon** [quintel/etengine#1243]
If I post the following configuration to the inputs of a scenario, the share group "coal_gas_ccus" is balanced on posting. However, this posts disables "share_of_energy_steel_energy_production_coal_gas" and "share_of_energy_steel_chemical_feedstock_coal_gas" and thus results in an invalid total share of zero percent for the share group. The hourly curves seem to be evaluating fine, so I'm not sure if this is intended behaviour or if something is going wrong here and an error message would be appropriate. 

inputs : {'external_coupling_energy_distribution_coal_gas_chemical_feedstock_share': 0.0,
 'external_coupling_energy_distribution_coal_gas_energy_production_share': 0.0,
 'share_of_energy_steel_chemical_feedstock_coal_gas': 0.0,
 'share_of_energy_steel_energy_production_coal_gas': 100.0}

**Comment by robcalon** [comment]
To check for these type of errors before posting, it might be nice to be able to check if a parameter that is attempted to being set can be disabled by another parameter that is also being set. In the current inputs json I can only see the disabled_by parameter of parameters that are already disabled.

**Comment by mabijkerk** [comment]
These input shouldn't be in the same group. To set the shares of the coal gas distribution node using external coupling, only the external coupling sliders should be used. The original sliders, `share_of_energy_steel_chemical_feedstock_coal_gas` and `share_of_energy_steel_energy_production_coal_gas` are then rightfully disabled.

Both of the external coupling inputs should therefore have their own group.

**Comment by mabijkerk** [comment]
This issue is now fixed on master i.e., our beta server, and will be on production with the coming Deploy in the beginning of May.
