### ISSUE TITLE
EU dataset errors

### ISSUE THREAD

**Issue by robcalon** [quintel/etengine#1265]
Hi,

I've spotted some issues in several of the newly added EU countries.

- There's a default parameter of 1000.0% for Cyrpus for the "energy_mixer_for_gas_power_fuel_natual_gas_share".
- The sharegroup "buildings_crude_oil" do not add up to 100% for Germany, Spain, Finland, Greece, Poland and Sweden.

Kind regards,
Rob

**Comment by marliekeverweij** [comment]
Thanks @robcalon for spotting these issues.

I could fix them this week on beta and put them to live in our next deploy on Sept 6th. How is that timing for you, would you like to have them online earlier? Let me know.

**Comment by robcalon** [comment]
No problem to take this along in the next release :)
