### ISSUE TITLE
Write migration for updated specs of 3rd generation nuclear power plant

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1268]
In this PR (https://github.com/quintel/etsource/pull/2744) we update a number of specs of the 3rd generation nuclear power plant. We should write a migration to compensate for the effect of this update on existing scenarios.

- **Availability decreased**
_Effect_: existing installed capacity produces less electricity than before.
_Potential mitigation_: raising installed capacity seem like the most effective way to compensate this, but this also raises the costs. This could be mitigated by taking the costs increase into account by the mitigation of the CAPEX and OPEX (see below).
- **CAPEX increased**
_Effect_: scenario costs increase. 
_Potential mitigation_: lower CAPEX using the relevant costs slider, problem is that this slider also affects the 2nd generation nuclear power plant, of which the specs haven't been changed.
- **OPEX increased**
_Effect:_ may go down in the merit order, leading to lower electricity production than before.
_Potential mitigation_: lower OPEX using the relevant costs slider, problem is that this slider also affects the 2nd generation nuclear power plant, of which the specs haven't been changed.

The question now is which of these potential mitigation efforts to put into practice. @AlexanderWirtz @marliekeverweij I would be happy to hear your thoughts on this.

**Comment by AlexanderWirtz** [comment]
@mabijkerk all these seem like good ideas. Not many scenarios will have a lot of 2nd Gen nuclear installed (except maybe France?), so the effect of your suggested migration is probably not huge. It seems unavoidable that costs differ at least a bit. This is less important _to me_  than energy and stuff

**Comment by mabijkerk** [comment]
Right, then we accept that the costs sliders for CAPEX and OPEX will also affect 2nd generation nuclear power plants. I would then propose that we focus on a migration for the 3rd generation nuclear power plant:

- To maintain the same electricity production, for scenarios with **installed capacity** for the 3rd generation nuclear power plant, the `capacity_of_energy_power_plant_nuclear_gen3_uranium_oxide` will have to be multiplied by inverse of the relative decrease of the availability: 1/(0.90/0.92)
- To maintain the same **initial investment costs**, first the increased installed capacity will have to be compensated. The initial `investment_costs_nuclear_nuclear_plant` therefore has to be multiplied by the inverse of the relative decrease of the availability and then multiplied by the inverse of the relative increase in initial investment costs: 1/(6992000000/4950000000)*(0.90/0.92) = 69.26%, meaning that the slider has to be set at -30.74%. Since this slider only sets the initial investment I don't think that we should compensate for the increased decommissioning costs as well.
- The **operation and maintenance costs** are a bit more tricky, as the slider sets both the fixed and variable operation and maintenance costs. I would preferably maintain roughly the same marginal costs for the 3rd generation power plant, but I'm not sure which attributes are factored into this.

@antw could you check if you agree with this proposal, if I've missed anything or miscalculated. The changed specs are [here](https://github.com/quintel/etsource/pull/2744/files).

Could you look into a way to change the O&M costs in such a way that the 3rd generation nuclear power plant (roughly) maintains the same marginal costs? If the migration would get too complicated perhaps we can just settle to mitigate the variable O&M per flh?

Finally, if the costs sliders have already been set in a scenario I suppose the resulting changes in these sliders will simply have to be added to the user value?

**Comment by AlexanderWirtz** [comment]
@mabijkerk I know I am contradicting myself, but is  this change in availability really worth all this effort? Is it an option to _not_ change the availability and just update the costs? The availability is likely to vary a but by plant anyway. Or is it more work to reverse that than to implement this migration? In that case, ignore what I said.

**Comment by mabijkerk** [comment]
It depends on whether our migration focus on mitigating **inputs** or **outputs**. If we focus on outputs, then we don't want the production of electricity from nuclear to change significantly. If we however focus on inputs, then we would not want the installed capacity to change.

In this case I think there is an argument to be made for leaving the installed capacity as is (and not mitigating the change in availability): users may typically set a certain amount of installed capacity for each power plant as a fixed/documented value, rather than the electricity produced from that power plant.

**Comment by AlexanderWirtz** [comment]
@mabijkerk I don't I made myself clear: how about we leave the availability at `0.92` and only update the costs?

**Comment by antw** [comment]
@mabijkerk I don't think we can write a migration for the initial investment slider either. The slider sets the percentage change for both gen 2 and 3 plants, but the costs have only changed for gen 3 plants.

Changing the value for this slider would also wrongly impact the user's choices for the gen 2 plants.

**Comment by mabijkerk** [comment]
Yes that's true, but based on @AlexanderWirtz's comment:

> Not many scenarios will have a lot of 2nd Gen nuclear installed (except maybe France?), so the effect of your suggested migration is probably not huge.

I concluded:

> Right, then we accept that the costs sliders for CAPEX and OPEX will also affect 2nd generation nuclear power plants

Or do you think that the effect for 2nd generation nuclear power plants will be too large @antw?

**Comment by antw** [comment]
Sorry, I should have paid more attention. 🤦‍♂️

Ignore my previous comment.

**Comment by antw** [comment]
> To maintain the same initial investment costs [...] the slider has to be set at -30.74%. Since this slider only sets the initial investment I don't think that we should compensate for the increased decommissioning costs as well.

I have a migration written that does this (ignoring `availability` for now). It:

1. **Updates those scenarios that had a cost set for nuclear plants so that the cost *in euros* remains the same.**

   For example, if the old default cost was 2 billion with the slider set to -50% (1 billion), and the new cost is 4 billion, the slider will now be set to -75%.

2. **Sets all other scenarios to -29.2%**

   This means that the initial investment costs for nuclear will not change in scenarios which are already created.

@mabijkerk Does this sound like what you wanted?

**Comment by mabijkerk** [comment]
Your migration for the investment costs sounds perfect! Just to check, scenarios that had a costs set for nuclear will maintain the same costs for the **3rd generation nuclear power plant**?

I would then take the same approach for the variable costs.
