### ISSUE TITLE
How to create a new scenario from C# webservice?

### ISSUE THREAD

**Issue by E-nergium** [quintel/etengine#1277]
Hello all!

I 'm busy with building a webapplication to create scenario's based on scenario's from a 3D globe with windturbines. During my creation of scenario's I want to push the turbines into a new scenario through the API, for a specific region (gemeente).

How can I do that? 

I did read the manual and I can read from an existing area the data. But I can't create a scenario through the API.....

1. The manual I did read: https://docs.energytransitionmodel.com/api/changelog/
2. The parameters to add to the API call : 
`{
  "scenario": {
    "title": "My scenario",
    "description": "A description"
  },
  "detailed": true
}`
3. The URL I'm using: [https://engine.energytransitionmodel.com/api/v3/scenarios]

**Comment by E-nergium** [comment]
I did fix this! Did you this code: 

`public static string XmlHttpRequest(string urlString, string xmlContent)
    {
        string response = null;
        HttpWebRequest httpWebRequest = null;//Declare an HTTP-specific implementation of the WebRequest class.
        HttpWebResponse httpWebResponse = null;//Declare an HTTP-specific implementation of the WebResponse class

        //Creates an HttpWebRequest for the specified URL.
        httpWebRequest = (HttpWebRequest)WebRequest.Create(urlString);

        try
        {
            byte[] bytes;
            bytes = System.Text.Encoding.ASCII.GetBytes(xmlContent);
            //Set HttpWebRequest properties
            httpWebRequest.Method = "POST";
            httpWebRequest.ContentLength = bytes.Length;
            httpWebRequest.ContentType = "text/xml; encoding='utf-8'";

            using (Stream requestStream = httpWebRequest.GetRequestStream())
            {
                //Writes a sequence of bytes to the current stream 
                requestStream.Write(bytes, 0, bytes.Length);
                requestStream.Close();//Close stream
            }

            //Sends the HttpWebRequest, and waits for a response.
            httpWebResponse = (HttpWebResponse)httpWebRequest.GetResponse();

            if (httpWebResponse.StatusCode == HttpStatusCode.OK)
            {
                //Get response stream into StreamReader
                using (Stream responseStream = httpWebResponse.GetResponseStream())
                {
                    using (StreamReader reader = new StreamReader(responseStream))
                        response = reader.ReadToEnd();
                }
            }
            httpWebResponse.Close();//Close HttpWebResponse
        }
        catch (WebException we)
        {   //TODO: Add custom exception handling
            throw new Exception(we.Message);
        }
        catch (Exception ex) { throw new Exception(ex.Message); }
        finally
        {
            httpWebResponse.Close();
            //Release objects
            httpWebResponse = null;
            httpWebRequest = null;

        }

        return response;
    }
`

**Comment by E-nergium** [comment]
well... My C# api call did not use my template id of a preset senario.... quite hard to find out how to use it.

Someone got some tips & trics how to use a template scenario on creating a new scenario?

I do use this description here:

https://docs.energytransitionmodel.com/api/scenario-basics#preset-scenarios 

But that doesn't work for me, even if I'm testing with the example from that page. Only thing I've got in response is the default NL2019 scenario, without any data...

**Comment by noracato** [comment]
Hi!

Thanks for reaching out.

The example used in the documentation uses the dummy `scenario_id` 11111, which doesn't really exist. That's why instead you get a blank scenario back. You can try to replace this value with the `scenario_id` of one of your own existing scenarios, or for instance with the ID of the national II3050 scenario, which is 763309.

Let me know if that works for you

**Comment by E-nergium** [comment]
hey @noracato / Nora,

De oplossing voor mij was om met jquery in de client het scenario op EMT api aan te maken. 

Zo werkt ie goed! 

Met dank aan het testen via de python toolbox :-)

:-)
