### ISSUE TITLE
Add a CSV export for residual hourly curves

### ISSUE THREAD

**Issue by antw** [quintel/etengine#1285]
From [Basecamp](https://3.basecamp.com/3797409/buckets/28651897/todos/5178653388#__recording_5458311780):

> What we aim to do here is to generate a CSV file that has (at least) 6 curves:
>
> * Residual load curve
>     * electricity (1) electricity_imbalance_inflexible_curve
>     * steam hot water (2) heat_network_imbalance_inflexible_curve
>     * network gas (3) network_gas_imbalance_cumulative_curve
>     * hydrogen (4) hydrogen_imbalance_inflexible_curve
> * Moving average of the residual load curve
>     * network gas (5) network_gas_imbalance_inflexible_smoothed_curve
>     * hydrogen (6) hydrogen_imbalance_inflexible_smoothed_curve

>Preferably it would be easy to add additional curves in a later stage. A config file in ETSource like the sankey_csv.yml would work very well.

**Comment by antw** [comment]
@mabijkerk This has been completed on the hydrogen-moving-average branches for ETSource.

I was a bit uncertain about how to name both the CSV and the headers within the CSV. I called it "residual_load.csv", but please feel free to suggest a better name if you have one.

The contents of the CSV may be customised in [etsource/config/residual_load_csv.yml](https://github.com/quintel/etsource/blob/hydrogen-moving-average/config/residual_load_csv.yml). I'm hoping it's fairly self-explanatory, but please get in touch with any questions.

The CSV itself can be downloaded at `${ETENGINE_URL}/api/v3/scenarios/:id/curves/residual_load.csv`.

**Comment by mabijkerk** [comment]
Works like a charm!

**Comment by mabijkerk** [comment]
Works like a charm!

**Comment by mabijkerk** [comment]
Works like a charm!
