### ISSUE TITLE
How to send the JSON parameters for a GET query on the API?

### ISSUE THREAD

**Issue by E-nergium** [quintel/etengine#1301]
1. I'm using the API of the ETENGINE to create scenario's, to calculate scenario's for windturbines. It's working allright to post the scenario with also the number of windturbines to the API.

2. Now I want to receive the calculated costs of my scenario based on the number of turbines. How and what to send to the API? 

3. I did use the scenario-tools in python, and it does what I want. That's great! This is my output of the JSON from the Python scripts:

`Processing scenario Aalten_test..
 Setting scenario title, description and protected status
 Getting queries

JSON gqueries  /scenarios/976639/ {'detailed': True, 'gqueries': ['dashboard_total_costs_per_household', 'dashboard_total_costs']}
 Getting downloads

URL scenario /scenarios/976639/energy_flow

URL scenario /scenarios/976639/curves/merit_order

All done! Open the scenarios in the Energy Transition Model:
test_scen: https://pro.energytransitionmodel.com/scenarios/892503
Aalten_test: https://pro.energytransitionmodel.com/scenarios/976639`

**Comment by E-nergium** [comment]
So Windturbines is based on my GeoAI interface based on distances from geo-objects (houses / schools / etc). And that's working very nice from my application on the ETM API. 

But now I want to receive the output from a requested calculation-parameter to use in my scenario. 

First I want to use these:
'dashboard_total_costs_per_household', 
'dashboard_total_costs'

![image](https://user-images.githubusercontent.com/93062675/206707785-88ce8318-83a3-4f8c-9f17-4adae18d914c.png)

**Comment by marliekeverweij** [comment]
Thanks for creating this issue. I am not sure if I understand your question. Are you trying to run the queries below and you need help how to do this?

- `dashboard_total_costs_per_household`
- `dashboard_total_costs`

**Comment by E-nergium** [comment]
Hoi Marlieke,

Ja, juist. Ik wil voor diverse parameters / nodes de resultaten ophalen vanuit de ETM Engine, behorende bij mijn scenario's.

Hier bijvoorbeeld 1 van de tests scenarios: https://energytransitionmodel.com/scenarios/977322

Voor dit scenario wil ik totale kosten ophalen, zoals deze in het ETM display ook zichtbaar is. Echter maak ik gebruik van het ETM als 'rekenmachine' om scenario's te ontwikkelen voor scenario's van windturbines met verschillende afstanden van woningen tot potentiele turbines. 

En de energetische doorrekeningen vanuit het ETM geeft daarbij een indicatie van de energetische effectiviteit van het scenario. En ja, dat is nog maar het begin in de hele energietransitie.... 

Dus, voor wat betreft de parameters kan / wil ik eventueel ook meerdere parameters ophalen. Deze ga ik gebruiken in een enquete met een waardering voor draagvlak en participatie. Best nobel dacht ik zo. :-)

**Comment by E-nergium** [comment]
Hier haal ik o.a. de parameters uit: 

https://github.com/quintel/scenario-tools/blob/master/data/adopt_template_settings.xlsx

**Comment by E-nergium** [comment]
Voor het aanmaken van scenario's heb ik gebruik gemaakt van de handleiding zoals deze hier staan:
https://docs.energytransitionmodel.com/api/scenario-basics/

Dat was wel flink stoeien met de samenstelling van de JSON:
![image](https://user-images.githubusercontent.com/93062675/206733983-16b0b156-9dec-4e0f-a6b6-d763c2c70dc1.png)

Zou fijn zijn als er ook een handleiding komt / bestaat voor het ophalen van data uit ETM Engine via de API, vergelijkbaar met aanmaken van scenario's. :-)

**Comment by E-nergium** [comment]
https://docs.energytransitionmodel.com/api/nodes ben ik vooral mee bezig. Echter krijg ik niet de verwachte response. 

Ik zal er nog wat dieper in duiken! Denk dat ik via deze link en setup van mijn JSON request hopelijk resultaat ga krijgen....

**Comment by E-nergium** [comment]
`"{\"key\":\"industry_chp_combined_cycle_gas_power_fuelmix\",\"sector\":\"industry\",\"use\":\"energetic\",\"presentation_group\":\"chps\",\"data\":{\"technical\":{\"total_installed_electricity_capacity\":{\"present\":0.0,\"future\":0.0,\"unit\":\"MW\",\"desc\":\"Installed electrical capacity\"},\"electricity_output_conversion\":{\"present\":\"46.0\",\"future\":\"46.0\",\"unit\":\"%\",\"desc\":\"Electrical efficiency\"},\"heat_output_conversion\":{\"present\":\"42.0\",\"future\":\"42.0\",\"unit\":\"%\",\"desc\":\"Heat efficiency\"},\"full_load_hours\":{\"present\":2959.9,\"future\":0.0,\"unit\":\"hour / year\",\"desc\":\"Full load hours\"}},\"cost\":{\"total_investment_over_lifetime_per_mw_electricity\":{\"present\":\"958583\",\"future\":\"958583\",\"unit\":\"EUR / MW\",\"desc\":\"Investment over lifetime per MW\"},\"fixed_operation_and_maintenance_costs_per_mw_electricity\":{\"present\":\"9129\",\"future\":\"9129\",\"unit\":\"EUR / MW / year\",\"desc\":\"Fixed operation and maintenance costs\"},\"variable_operation_and_maintenance_costs_per_full_load_hour\":{\"present\":\"328\",\"future\":\"328\",\"unit\":\"EUR / full load hour\",\"desc\":\"Variable operation and maintenance costs\"},\"wacc\":{\"present\":\"4.0\",\"future\":\"4.0\",\"unit\":\"%\",\"desc\":\"Weighted average cost of capital\"},\"takes_part_in_ets\":{\"present\":\"true\",\"future\":\"true\",\"unit\":\"boolean\",\"desc\":\"Do emissions have to be paid through the ETS?\"}},\"other\":{\"technical_lifetime\":{\"present\":30.0,\"future\":30.0,\"unit\":\"years\",\"desc\":\"Technical lifetime\"}}},\"uses_coal_and_wood_pellets\":false}"`

Het werkt! Simpel met de /nodes/{key} structuur :-). 

Dit is (was?) mijn testcase: 
https://engine.energytransitionmodel.com/api/v3/scenarios/977324/nodes/industry_chp_combined_cycle_gas_power_fuelmix

Nu verder werken met de total_costs | total_costs_households | etc etc

En dan per parameter alle waarden ophalen in een mooie functie :-).

**Comment by noracato** [comment]
Hallo,

Leuk dat je zo aan de slag bent!

Er staat op de documentatie ook een klein hoofdstukje over het ophalen van resultaten op basis van `queries` (zoals `dashboard_total_costs_per_household` en `dashboard_total_costs`). Dat is hier te vinden: https://docs.energytransitionmodel.com/api/scenarios#query-a-scenario.

Nog even een ander punt om op te letten. Binnenkort schakelen we over op een nieuw authenticatiesysteem. Je hebt dan een token nodig om met de API te blijven communiceren. Meer informatie daarover kan je hier vinden: https://docs.energytransitionmodel.com/api/authentication.
