### ISSUE TITLE
Find out why scenarios are being migrated that don't fit the migrations criteria

### ISSUE THREAD

**Issue by noracato** [quintel/etengine#1318]
When running a scenario migration to delete a deprecated input that was present in ~1500 scenarios, the migration reported 7600 scenarios has undergone a change. Upon closer inspection inputs like insulation level and multiple buildings space heating shares had been changed in these scenarios with a few percent.

All scenarios affected were last updated before early December 2022.

Investigate why this is happening:
- Is it only happening now because of the December 2022 deploy?
- Or has it been going on for a long time and we're only noticing it now?
- How can we fix it?

I committed a debug version of `ScenarioMigration` based on the affected migration in 5f9a85d. I'll attach the logs to this issue.

---

[migration_log.txt.zip](https://github.com/quintel/etengine/files/10537147/migration_log.txt.zip)

Related to #1317

**Comment by noracato** [comment]
Notifying @ChaelKruip

**Comment by thomas-qah** [comment]
Plan of action:
1. Check how many migratable scenario's contain the `REDUNDANT_AGGREGATE_KEYS` for scenario's since 01-01-2022
2. Run the migration locally with a prod db and see what happens ;)
3. If more scenarios are affected than the ones identified in step 1, find out why

**Comment by thomas-qah** [comment]
Prelimenary outcome after testing: The correct scenarios seem to be selected during my test runs. Let discuss this coming monday @noracato :)

**Comment by noracato** [comment]
Does not seems the changes have any impact. Closing the issue.
