### ISSUE TITLE
Possible ambiguous saved scenario history

### ISSUE THREAD

**Issue by robcalon** [quintel/etengine#1320]
It is possible to edit a scenario_id that's part of a saved scenario's history and set that scenario_id as the 'active' scenario when loading a saved scenario. In this case the scenario_id will be both in the scenario history as being the active scenario in the returned information. 

Once I again update the saved scenario by referring to a new scenario_id, the scenario_id that was already present in the history will not change position in the scenario_id_history list. I would have expected that the order of the scenario_id_history list would at least have changed, making the history a bit ambiguous. 

I would expect the API to refuse setting to update an saved scenario with a scenario_id that is already present in the scenario_id_history to prevent this behaviour from happing. You could than revert your scenario to an point in time by setting a copy of the point in time as the active scenario_id.

**Comment by robcalon** [comment]
@noracato is this one to reopen or is this addressed elsewhere?

**Comment by noracato** [comment]
Yes, it closed itself while I was on holiday 😄

**Comment by noracato** [comment]
Fix is now live
