### ISSUE TITLE
Should CO2 costs be allocated to CCS?

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1326]
**Introduction**
@DorinevanderVlies and @ChaelKruip, we had a short discussion about the costs of CO2 in the model. Point of discussion is what should be included in the "Carbon capture, sequestration and utilisation" group in the chart below.

<img src="https://user-images.githubusercontent.com/67338510/224078603-1d0e1aa8-fb1e-478a-b909-55131ced383a.png" width="500" />

The query behind this costs group consists of costs for CCS made in the molecule graph and costs for CCS made in the energy graph. The [costs_co2_energy_graph](https://github.com/quintel/etsource/blob/master/gqueries/general/costs/mece_costs/6_CCUS/costs_co2_energy_graph.gql) include a component called `operating_expenses_ccs_per(:node)`, which increases as the CO2 price increases.

**Technical details**
The `operating_expenses_ccs` are defined [here](https://github.com/quintel/etengine/blob/master/app/models/qernel/node_api/cost.rb#L193-L197), and include component called `co2_emission_costs.` 

```ruby
      def operating_expenses_ccs
        fetch(:operating_expenses_ccs) do
          variable_operation_and_maintenance_costs_for_ccs + co2_emissions_costs
        end
      end
```

In the `co2_emissions_costs`, the `area.co2_price` (this is what is set by the slider in the frontend) is included [here](https://github.com/quintel/etengine/blob/master/app/models/qernel/node_api/cost.rb#L401-L407):

```ruby
def co2_emissions_costs_per_typical_input
        fetch(:co2_emissions_costs_per_typical_input) do
          weighted_carrier_co2_per_mj * area.co2_price *
            (1 - area.co2_percentage_free) *
            (takes_part_in_ets || 1.0) * ((1 - free_co2_factor))
        end
      end
```

**Conclusion**
Effectively the technical details above show that the costs of CO2 emissions are included in the operating expenses of nodes. This means that the costs of CCS increase when the CO2 price increases, because the price of emissions increases. Strangely though, this is not stated in our [documentation](https://docs.energytransitionmodel.com/main/cost-overview-per-sector#carbon-capture-utilisation-and-storage-ccus).

<img width="500" alt="Screenshot 2023-03-10 at 08 38 36" src="https://user-images.githubusercontent.com/67338510/224253145-99d7d242-60e0-4a25-977d-c967ba484f40.png">

Questions that arise from this are:

- Does it make sense to include CO2 emission costs within a category that is currently defined as "Carbon capture, sequestration and utilisation"?
- Does it make sense to include Co2 emission costs in the calculation of **system costs** (this question was raised during the discussion)
- Do we need to schedule a short meeting for this? Do we need to include others in this discussion? Is further research required (in case I'm interpreting the costs method wrong)?

**Comment by mabijkerk** [comment]
@KoenvanB can this issue be closed?

**Comment by KoenvanB** [comment]
Yes, because both questions seem answered within the pilot FIT project:

1. CO2 emissions costs _should_ be included as system costs because they are relevant for e.g. the merit order;
2. CO2 emissions costs are **not** part of CCUS costs because they can be incurred without any CCUS present. As such they have been removed from the `operating_expenses_ccs` method in ETEngine

CO2 emissions costs are now included as a separate system costs component in the costs charts, and as a separate column in the costs download.
