### ISSUE TITLE
Collective heat pump is not assigned any electricity on the input curve

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1337]
When I open the [II3050v2 EUR](https://energytransitionmodel.com/saved_scenarios/14554) scenario and add 7000 MW of the collective heat pump (`energy_heat_heatpump_water_water_electricity`), I get the following results:

<img width="1487" alt="Screenshot 2023-04-19 at 11 36 05" src="https://user-images.githubusercontent.com/67338510/233034028-e56df092-5242-4cc7-a351-376a6469df9e.png">

The collective heat pump is therefore producing steam hot water for the heat network and consuming electricity. However, when I export all the electricity curves, the input curve of the heat pump is 0 in every hour. This is confirmed in the following query:

```ruby
SUM(V(energy_heat_heatpump_water_water_electricity,electricity_input_curve))

0.0
```

@noracato can you look into this issue? It does not seem to occur when I install 7000 MW in a blank `nl2019` scenario:

```ruby
SUM(V(energy_heat_heatpump_water_water_electricity,electricity_input_curve))

835,404.3176110185
```

The issue also does not seem to occur for any of the other electricity consumers on the heat network in the II3050v2 EUR scenario: `energy_heat_well_geothermal`, `energy_heat_flexibility_p2h_heatpump_electricity` and `energy_heat_flexibility_p2h_boiler_electricity`. These all have electricity assigned to the input curve. A difference is that these are `must_run` producers however, whereas the collective heat pump is the only `dispatchable` producer on the heat network that consumes electricity.

**Comment by noracato** [comment]
When I follow your steps of adding the 7000MW of collective heatpump, it starts showing up in the merit order:

<img width="482" alt="Screenshot 2023-05-16 at 13 54 04" src="https://github.com/quintel/etengine/assets/14875123/b7da246a-0384-48bd-8428-f689dee550ad">

But it comes in place 3, after the waste heater with 0 capacity. Looking at the available capacity of the next candidate is, I believe, a stop condition for Merit. So maybe inside Merit the collective heat pump is never reached.

I'll look into this some more, but it might be a good starting point!

**Comment by DorinevanderVlies** [comment]
I find that the electricity demand for collective heat pumps "disappears" when a battery is installed **with forecasting**.
Below images of [a scenario for NL2019 with all heating by HT heat network and a large collective heat pump](
https://energytransitionmodel.com/saved_scenarios/17409).
![image](https://github.com/quintel/etengine/assets/19907658/aa6a7ad6-8436-4c4c-934e-48c88ecccb1a)
<img width="2277" alt="image" src="https://github.com/quintel/etengine/assets/19907658/a28ca454-8d80-496c-ac23-89c8351cf5fa">

**Comment by louispt1** [comment]
@mabijkerk 
The branch in [this PR](https://github.com/quintel/etsource/pull/3094) ([heat-pump-subtype](https://github.com/quintel/etsource/tree/heat-pump-subtype)) has the changed subtypes for the heat pump. 

I'm obviously not super experienced with testing these things, so I would appreciate it if a modeller could take a look at this and check that the solution works. I would also appreciate seeing how they would perform their checks/tests because I think it will definitely help me in the future.

**Comment by mabijkerk** [comment]
Nice work @louispt1 and good suggestion to go through it together. I'll schedule something.
