### ISSUE TITLE
[Bug]: Create saved scenario id not working

### ISSUE THREAD

**Issue by robcalon** [quintel/etengine#1338]
It appears that the create saved scenario id feature is not working anymore, could it be that the endpoint has somehow changed to what is stated in the documentation? https://docs.energytransitionmodel.com/api/saved-scenarios#create-a-saved-scenario

**Comment by noracato** [comment]
Thanks for notifying us! Nothing seems to have changed to the endpoint in the last 4 months. My first hunch is that maybe you request headers are incorrect, or that your personal API token may have expired.
Could you check that? If nothing comes out of that I'll dive in deeper :)

**Comment by robcalon** [comment]
You are right, there was a trailing space in there. Thanks for thinking along!
