### ISSUE TITLE
Facilitate easy migration of multiple scenarios between live and staging

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1348]
**Background**
Currently it is challenging to migrate a scenario manually from live to staging. This is because not only the inputs have to be migrated (which can be achieved easily by copy-pasting the scenario inputs between the engines), but each merit order and especially all adjusted curves have to be migrated as well. The curves are not visible in the engine scenario view. 

Currently we typically ask a developer to migrate such scenarios. Given the current limited availability of our developers, this means that it can take a while for scenarios to be migrated, especially when it concerns multiple scenarios, as in https://github.com/quintel/mechanical_turk/issues/168#issuecomment-1504800483

**Solution**
I'm not sure what the best solution would be to enable easy migration of multiple scenario between live and staging (both directions). @noracato or @thomas-qah do you think something like this could be implemented for the modellers? If so, who of you can pick this up?

Notifying @Charlottevm

**Comment by noracato** [comment]
I think with small change to the [quintel/scenario-tools](https://github.com/quintel/scenario-tools) you should be able to do it. For example we could add a small command that allows you to download everything from a scenario from one server, and upload it into another (which could as well be your `localhost`).

**Comment by mabijkerk** [comment]
What is the status of this issue? I believe @thomas-qah has created a tool? Is this something modellers can easily use as well?

**Comment by noracato** [comment]
Yes! You can find documentation on @thomas-qah script [here](https://docs.energytransitionmodel.com/contrib/cloning-scenarios).

I'll close this one now
