### ISSUE TITLE
start etengine with: bundle exec rails server

### ISSUE THREAD

**Issue by nick-gorman** [quintel/etengine#1350]
Hi quintel team!

Trying to get the etm running locally (both engine and model). 

However, I'm running into an issue. When I run the etmodel in docker I get the prompt in the screenshot below.

![image](https://github.com/quintel/etengine/assets/40549624/2ae802fc-4e9e-4e21-a805-7d67e1134c7f)

While I can start the etengine locally using docker-compose run, I can't figure out how to start it with the command "bundle exec rails server", any guidance on this would be much appreciated.

Cheers,
Nick

**Comment by noracato** [comment]
Hi Nick!

Happy to see you're trying to use our model locally!

The engine can be run both via Docker (`docker-compose up`) or directly (`bundle exec rails s`). For internal development we use the latter, that's probably why these instructions are referring to that one. However, for instruction 1 from your screenshot it doesn't matter how you run the engine, as long as it is running. 

When it's running you should be able to proceed to the next steps. Signing in to the engine requires the account generated for you when you set up the database ([in step 3](https://github.com/quintel/etengine#installation-with-docker)).

If you're interested, [this part of the readme](https://github.com/quintel/etengine/tree/master#installation-without-docker) specifies how you can run the engine directly on mac and linux machines.

Cheers,
Nora

**Comment by nick-gorman** [comment]
Thanks @noracato think that resolves my question :)
