### ISSUE TITLE
locally running ETEngine: "tailwind.css" is not present

### ISSUE THREAD

**Issue by nick-gorman** [quintel/etengine#1352]
When I attempt to run the ETEngine locally using docker, after running `dock-compose up` and opening http://localhost:3000/ in the browser, I get the following result:

![image](https://github.com/quintel/etengine/assets/40549624/bbb9fcd1-446e-4c53-b5ff-ae2760c52eb6)

I think the main issue appears to be a missing file called tailwind.css

This is using the latest version of ETEngine on the master branch (6231e03)

Note the one step I skipped in the install process was adding the ETSource decryption password, as I haven't obtained this yet, and was hoping there is some sample non-encrypted data I could run the engine and model with.

**Comment by nick-gorman** [comment]
Based on this rails issue: https://github.com/rails/tailwindcss-rails/issues/158

I ran the command  `docker-compose run --rm web bash -c 'bin/rails assets:precompile'` before rerunning step 3 of the ETEngine docker install process, this fixed the issue. But looks life the ETEngine setup process needs to be updated to make sure tailwind.css gets added.

**Comment by Charlottevm** [comment]
Hi @nick-gorman ,

Thank you for opening this issue and bringing our attention to the outdated ETEngine setup process. 
It was indeed on our to-do list to change the ETEngine setup process, apologies for the inconvenience.
Happy to see you found a solution in the meantime!
If you need any additional help from us or if anything else is unclear don't hesitate to open another issue 👍
