### ISSUE TITLE
Set scenarios to keep_compatible and apply missed migrations

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1353]
One of our clients has created a number of scenarios for which the `keep_compatible` attribute is set to `false`. For the scenarios the attribute needs to be set to `true`. In the meantime, migrations have been applied that these scenarios have missed. The question is how to apply the missed migrations to the scenarios after they have been set to `true`. Perhaps this is done automatically by ETEngine?

Scenarios are still confidential, so contact me for the scenario-links.

- [ ] Set `keep_compatible` for marked scenarios to `true` with an API call
- [ ] Check how missed migration can be applied to marked scenarios
- [ ] Apply missed migrations to marked scenarios

Notifying @DorinevanderVlies

**Comment by noracato** [comment]
The most important question is: (how) do we know which migrations have been missed? 

Unfortunately it's not that straightforward to apply them. If values were changed based on older calculations we cannot see anymore what it should have been. We also don't know if some migrations have been carried out when the scenarios were updated (we migrate for 1 month after the last update), followed by some missed migrations when the scenarios were untouched again for a while, and then again maybe some applied migrations after an update.

Anyhow, we have to do it all by hand.

Did they create the scenario's through the API? Then they should have explicitly put `keep_compatible` to `true`like it says in our API docs. If they did not create them through the API, but via the font-end we have to investigate if that is the behaviour that we want - that scenario's get stale so quickly without users apparently being aware of it.

**Comment by mabijkerk** [comment]
This issue also applies to the II3050v2 scenarios, though I'm still awaiting confirmation from our client to check that `keep_compatible = false` was unintentional.

**Comment by noracato** [comment]
Closed in 7687e51
