### ISSUE TITLE
Better insight in scenario compatibility

### ISSUE THREAD

**Issue by noracato** [quintel/etengine#1361]
You can view the current scenario in the engine to check the compatibility settings quickly, see the screenshot here below.

![Screenshot 2023-09-28 at 14 13 03](https://github.com/quintel/etengine/assets/14875123/c97664d8-3b5a-4737-8cca-3fa7d8276671)

However there are two issues with the current display:
1. It is unclear what this compatibility actually means
2. The link to the docs is broken

This issue proposes solutions for both these problems.

## 1. Changing the tags
The current way of displaying compatibility:
**Current model version only** `keep_compatible` is set to false, but the scenario is _young_ enough to be ok
**Outdated - not guaranteed** `keep_compatible` is set to false, and the scenario is (most probably) too old to join migrations
**Keep compatible** `keep_compatible` is set to true, the scenario is being migrated

We would like to split this up into two labels:
- **Keep compatible** => Simple `True` or `False`
- **Compatibility** => Interpreting the current state:
  - `Fully compatible`
  - `Within this deploy`
  - `Possibly outdated`

## 2. Update the link
The new link to the docs is https://docs.energytransitionmodel.com/api/scenarios#forward-compatibility

**Comment by mabijkerk** [comment]
> but the scenario is young enough to be ok
Wat do you mean by this? Is this related to the '1 month old migration criterium'?

**Comment by mabijkerk** [comment]
> Keep compatible => Simple `True` or `False`

Good idea!

> Compatibility => Interpreting the current state:
> `Fully compatible`
> `Within this deploy`
> `Possibly outdated`

This seems fine, as long as there is good documentation what each state means. On their own I don't have a feeling for what these states mean.
