### ISSUE TITLE
Slider migrations solar-pv roof & efficiencies industry

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etengine#1388]
Two slider units (for multiple sliders) have been changed resulting in the need for scenario migration(s).
In short, we have changed the solar panels on roofs (for buildings and households) from `% of roof surface potential` to `MW`, as well as changed the efficiency sliders in industry from `% per year` to `% total`. This means those sliders need to be recalculated in existing scenario's. 

**Step 1: Recalculate solar panels on roof sliders**
This considers the following sliders (names have been changed!):
- `households_solar_pv_solar_radiation_market_penetration` --> `capacity_of_households_solar_pv_solar_radiation`
- `buildings_solar_pv_solar_radiation_market_penetration` --> `capacity_of_buildings_solar_pv_solar_radiation`

_The following calculation is needed:_

**(USER_INPUT() / 100.0) * AREA(residences_roof_surface_available_for_pv) / V(households_solar_pv_solar_radiation, land_use_per_unit)) * V(households_solar_pv_solar_radiation, electricity_output_capacity)**

_or add numbers hardcoded if necessary..:_
land_use_per_unit) = 1.6000000000000001e-06
electricity_output_capacity = 0.000272

_In words:_
The % roof surface needs to be recalculated to MW. This is done by 1. calculating the roof surface area, 2. calculating the amount of units (solar panels) can be fit into that area using the land_use_per_unit and then multiplying this by the capacity of one unit (solar panel) using the electricity_output_capacity.

**Step 2: Recalculate efficiency sliders in industry**
This considers the following sliders:
- `industry_useful_demand_for_other_paper_electricity_efficiency`
- `industry_useful_demand_for_other_paper_useable_heat_efficiency`
- `industry_useful_demand_for_other_food_electricity_efficiency`
- `industry_useful_demand_for_other_food_useable_heat_efficiency`
- `industry_useful_demand_for_other_ict_efficiency`
- `industry_useful_demand_for_chemical_other_electricity_efficiency`
- `industry_useful_demand_for_chemical_other_useable_heat_efficiency`
- `industry_useful_demand_for_chemical_fertilizers_electricity_efficiency`
- `industry_useful_demand_for_chemical_fertilizers_useable_heat_efficiency`
- `industry_useful_demand_for_chemical_refineries_electricity_efficiency`
- `industry_useful_demand_for_chemical_refineries_useable_heat_efficiency`
- `industry_other_metals_process_electricity_efficiency`
- `industry_other_metals_process_heat_useable_heat_efficiency`

_The following calculation is needed (in words):_
T = eindjaar
t = huidig jaar
Eff_jaar = efficiëntieverbetering per jaar (in %)
Eff_tot = efficiëntieverbetering over gehele periode (in %)

**Eff_tot = 100 * (1 -  1/(1 + Eff_jaar / 100)^(T - t) )**

_NOTE / QUESTION:_ The min / max of sliders changes due to the unit change, is it possible to check how many scenario's now fall outside of the min/max of the sliders? @noracato 

For more information, check out the changes made on [ETSource](https://github.com/quintel/etsource/pull/2996) or [ETModel](https://github.com/quintel/etmodel/pull/4192).

Notifying @KoenvanB & @mabijkerk

**Comment by mabijkerk** [comment]
Based on the issue description I think it boils down to the following todos:

- [ ] Research amount of scenarios with value of chemical industry efficiency < 0 and what the value is (@noracato and @Charlottevm)
- [ ] Determine best way to migrate chemical industry efficiency inputs (@mabijkerk @Charlottevm and @KoenvanB)
- [ ] If necessary based on discussion, restructure min_value in chemical industry efficiency inputs (@KoenvanB)
- [ ] Write solar migration @noracato 
- [ ] Write industry migration @noracato 

Additionally a minor adjustment should be made to the approach for the food and paper efficiency sliders. Each is split into two inputs, who should **both** be assigned the transformed value of the old input.

- Old inputs
  - industry_useful_demand_for_other_food_efficiency (%/y)
  - industry_useful_demand_for_other_paper_efficiency (%/y)
- New inputs
  - industry_useful_demand_for_other_food_electricity_efficiency (%)
  - industry_useful_demand_for_other_food_useable_heat_efficiency (%)
  - industry_useful_demand_for_other_paper_electricity_efficiency (%)
  - industry_useful_demand_for_other_paper_useable_heat_efficiency (%)

**Comment by Charlottevm** [comment]
@noracato Yesterday  @mabijkerk and I discussed the minimum for the chemical industry efficiency sliders:

```industry_useful_demand_for_chemical_other_electricity_efficiency```
```industry_useful_demand_for_chemical_other_useable_heat_efficiency```

We decided to put the min_value at 0.0. This means 178 scenario's which currently have a negative slider value will have to be updated to 0.0% (or the start_value) in the migration.

**Comment by noracato** [comment]
> This means 178 scenario's which currently have a negative slider value will have to be updated to 0.0% (or the start_value) in the migration.

Do you want me to explicitly set it to 0, or is it okay to just "reset" the slider (so that it automatically goes to the start value)?

**Comment by noracato** [comment]
I created the migration on the branch `solar-industry-drenthe`, let me know what you think after testing it!
