### ISSUE TITLE
Deficits show up in hourly calculations but not in yearly node

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1389]
**Background**
When I open a blank `nl2019` scenario on `master`, the deficits for households and buildings are 0.0 PJ. See the `households_space_heater_deficit`:

<img width="1076" alt="Screenshot 2024-01-25 at 13 28 49" src="https://github.com/quintel/etengine/assets/67338510/bbad40ad-65c2-4090-8f13-d2c813d84138">

When I however open the deficits table, it shows that there are deficits for apartments between 2005 and present:

![Deficits in space heating per residence type and construction period 2526230](https://github.com/quintel/etengine/assets/67338510/84ca4908-be50-4229-94f4-c093be5bcd5b)

**Issue**
This means that the FEVER_DEMAND_CURVE and the FEVER_PRODUCTION_CURVE for `households_useful_demand_for_space_heating_apartments_2005_present` are not equal. These are subtracted from each other in the query `absolute_deficit_useful_demand_for_space_heating_apartments_2005_present`.

**Solution**
I am not sure how this should be solved. Some interesting points to note:

- The `households_useful_demand_for_space_heating_apartments_2005_present` is the first of the existing households in the `space_heating_consumer_order`
- The deficits do increase with infinity in the screenshot above, even though they are 0 PJ in both present and future
- If I set the gas combi boiler to 100% and then back again to 84% (without using the reset button), the deficits disappear

**Comment by mabijkerk** [comment]
Data-initialisation now shows 0 deficits in a blank scenario, nice work @noracato! I do still spot a minor issue however. Opening a blank scenario produces -0 deficits:

<img width="626" alt="image" src="https://github.com/quintel/etengine/assets/67338510/d7424da7-b233-4fb1-9fba-38d4426829c8">

**Comment by mabijkerk** [comment]
Additionally, when I introduce deficits and then set the amount of decimals to 1, this seems to have no affect. For example:
```ruby
      %td{:data => {:decimals => 1, :gquery => "relative_deficit_useful_demand_for_space_heating_apartments_before_1945", :graph => :future}}
      %td{:data => {:decimals => 1, :gquery => "relative_deficit_useful_demand_for_space_heating_detached_houses_before_1945", :graph => :future}}
      %td{:data => {:decimals => 1, :gquery => "relative_deficit_useful_demand_for_space_heating_semi_detached_houses_before_1945", :graph => :future}}
      %td{:data => {:decimals => 1, :gquery => "relative_deficit_useful_demand_for_space_heating_terraced_houses_before_1945", :graph => :future}}
```

This still produces:
<img width="620" alt="Screenshot 2024-01-30 at 16 58 33" src="https://github.com/quintel/etengine/assets/67338510/b2b0ccfe-1c18-405c-a17f-b2c328bbce5f">

**Comment by noracato** [comment]
> Additionally, when I introduce deficits and then set the amount of decimals to 1, this seems to have no affect.

That is because the unit of the values is unknown, so the table does not (know how to) scale the values and keeps them as the are.

**Comment by mabijkerk** [comment]
How can the table know the unit of the values? Especially when there are two unit type values in the same table?

**Comment by noracato** [comment]
Sorry, that was unclear of me.

In the interface file, your table does not specify a unit, and therefore the table will not rescale values as it does not what the rules are for the conversion. Hence, giving the table cell a precision of 1 decimal will not do anything, as the table is not doing anything with the number.

**Comment by mabijkerk** [comment]
So is it possible to set a unit for part of the table?

**Comment by noracato** [comment]
Not at the moment unfortunately

**Comment by noracato** [comment]
Or we have to rebuild the table in a different way, like for example the plant profitability table

**Comment by mabijkerk** [comment]
Table is looking great! There is however still an interesting thing going on with the data-initialisation in a blank nl2019 scenario. A tiny amount of deficits occur:

```ruby
V(households_space_heater_deficit,demand)

0.0001087188720703125
```

The table then looks like this:
<img width="625" alt="Screenshot 2024-01-31 at 15 20 33" src="https://github.com/quintel/etengine/assets/67338510/3b2cc719-d65f-4a16-a63f-702435f435e2">

Should I open a new issue for this? It seems so marginal that is more of a nice-to-solve at some point than a must-have now.

**Comment by mabijkerk** [comment]
It is still something worth investigating in my opinion, because in a blank `DE_germany` scenario, some deficits are quite significant:
<img width="621" alt="Screenshot 2024-01-31 at 15 27 05" src="https://github.com/quintel/etengine/assets/67338510/d3510df0-6dc6-4957-831b-af713bd1cd13">

If is set any of the technologies at 100% in that scenario, no deficits occur. This suggests that it is not related to the technology capacities, but to the initialisation.
