### ISSUE TITLE
Recent fever changes are not picked up by heat_network_mt and heat_network_lt

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1390]
On `production`, if I open a blank `nl2019` scenario and set the households space heating technologies to 50% for MT heat networks, I immediately get a backup gas burner to supply the heat demand:

<img width="600" alt="Screenshot 2024-01-25 at 13 45 36" src="https://github.com/quintel/etengine/assets/67338510/1842be6c-ba4c-461c-89d5-85a2ebad1c2e">

However, when I do the same on `master`, no bakcup gas burner is used:

<img width="600" alt="Screenshot 2024-01-25 at 13 45 36" src="https://github.com/quintel/etengine/assets/67338510/8b95a63e-01db-4008-8f72-c91ad37e97ba">

This is not due to large deficits. Instead, something seems to go wrong on the backup burner node:

<img width="1490" alt="Screenshot 2024-01-25 at 13 45 36" src="https://github.com/quintel/etengine/assets/67338510/76defa85-9771-4683-99f1-7ef6a7a156b6">

More specifically, none of the dispatchable heat source on the MT heat network seem to be working. This is the same for the LT heat network. HT heat network seems to be working fine.

**Comment by noracato** [comment]
First breakthrough:
If in the node `households_final_demand_mt_steam_hot_water.final_demand` you set the `demand` to e.g. 15.0 instead of 0.0, then all future calculations start working again. So it looks like some calculations don't happen in the future when the present is 0, I'll continue looking!

**Comment by mabijkerk** [comment]
Heat networks on MT and LT now are closer to what we would expect:

<img width="631" alt="Screenshot 2024-01-30 at 17 03 42" src="https://github.com/quintel/etengine/assets/67338510/00880214-85ab-4f04-bb1d-7cf2c5b15cf7">

The only thing that now does not seem to be working is the heat provided to account for distribution losses in the MT heat network:

<img width="1486" alt="Screenshot 2024-01-30 at 17 04 31" src="https://github.com/quintel/etengine/assets/67338510/9ce924a2-3215-4085-b620-4f16986beccc">

More is demanded from the backup burner in `steam_hot_water` than what is actually used in `network_gas`. The difference seems to be in the `energy_heat_distribution_mt_loss`.

**Comment by noracato** [comment]
Done

**Comment by mabijkerk** [comment]
LGTM! 

![District heating supply and demand per temperature level 2527467](https://github.com/quintel/etengine/assets/67338510/f974afd1-97bf-444e-a4de-e5f8a9dd1f0c)
