### ISSUE TITLE
Recent fever changes do not seem to work for all heating technologies in buildings

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1391]
When I open a blank `nl2019` scenario on `master` and go to the heating technologies in the buildings sector, some unexpected behaviour arises. For a number of technologies the supplied heat goes to 0 and only deficits occur. For example, when the Air heat pump (gas) `buildings_space_heater_heatpump_air_water_electricity` is set to 100%:

![Final energy demand for heating in buildings 2526238](https://github.com/quintel/etengine/assets/67338510/33c51f3c-d061-46eb-ab78-92b1e3a3d6f2)

- Air heat pump (gas): `buildings_space_heater_heatpump_air_water_electricity`
- Ground heat pump with TS: `buildings_space_heater_collective_heatpump_water_water_ts_electricity`
- Aquathermal heat pump with TS (surface water): `buildings_space_heater_heatpump_surface_water_water_ts_electricity`
- Electric boiler: `buildings_space_heater_electricity`
- Biomass-fired heater: `buildings_space_heater_wood_pellets`

I thought it might be related to the attribute households_supplied_per_unit = 1.0, but adding it to the air heat pump (gas) does not seem to solve the issue. The extent to which deficits occur also change per technology. The strange thing is that for the biomass heater, some deficits occur with its `heat_output_capacity` being 0.137 MW, whereas the condensing combi boiler (gas) does not have any deficits with a `heat_output_capacity` of 0.043 MW.

**Comment by noracato** [comment]
> I thought it might be related to the attribute households_supplied_per_unit = 1.0

It is! But that attribute only works for nodes that are part of the `demand_driven` group. Adding this group to the affected nodes solves the issue!

**Comment by mabijkerk** [comment]
LGTM!
