### ISSUE TITLE
Deficits do not seem to occur in households when expected

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1392]
When I open a blank `nl2019` scenario, I set the condensing combi boiler (gas) to 100% for households.

I can get the demand curve of apartments before 1945: `FEVER_DEMAND_CURVE(V(households_useful_demand_for_space_heating_apartments_before_1945))`. The maximum value of that curve is 3006 MW demand in a single hour. With the number of units set to 540698, the maximum demand of single residence is 5.56 kW.

I would therefore expect deficits to occur when I set the `heat_output_capacity` of the `households_space_heater_combined_network_gas` to 5.5 kW or lower in the dimensioning section: [https://beta.energytransitionmodel.com/scenario/demand/households_heating_order/capacities](https://beta.energytransitionmodel.com/scenario/demand/households_heating_order/capacities). However, if I set the relevant input `households_heater_combined_network_gas_heat_output_capacity` to 5.5 kW, no deficits appear in the deficit table. Only when I set the capacity to 5.0 kW, deficits appear:

![Deficits in space heating per residence type and construction period 2526243](https://github.com/quintel/etengine/assets/67338510/2ab7b938-a5bf-4b8e-952a-2cf95c4980fb)

This is relatively close to what is expected, but I'm still wondering why this difference occurs. During testing we also encountered an example where the difference was larger, but I can't reproduce it now. Maybe @redekok knows when this occured?

**Comment by redekok** [comment]
> During testing we also encountered an example where the difference was larger, but I can't reproduce it now. Maybe @redekok knows when this occured?

I thought I did but I'm not able to fully reproduce this bug. When maximally installing air-sourced heat pumps and increasing the typical useful demand values to 500 kWh/m2 for each category, barely any deficits occur. Changing the installed capacity per heat pump unit doesn't change anything. I think it was a variation on a [scenario](https://beta.energytransitionmodel.com/scenarios/2526253) like this.

**Comment by noracato** [comment]
The `households_space_heater_combined_network_gas` has its `defer_for` property set to 4. Roughly meaning it has 4 hours to catch up with any deficit that occurred. So it does not surprise that there is this small difference from 5.5 to 5.0 to when we really see the deficits.

Or is there more to investigate that I'm not seeing?

**Comment by redekok** [comment]
Ah interesting, I thought we were gonna drop that attribute. @mabijkerk what are your latest thoughts on the `defer_for` attribute?

**Comment by mabijkerk** [comment]
Thanks for pointing this out @noracato! I also thought that we would drop that attribute. I suggest to set the `defer_for` to 0 for all heaters.

This still produces an unexpected result though. In a blank `nl2019` with the combined gas combi-boiler set to 100% and `defer_for` to 0, the detached houses from before 1945 begin to get some deficits from a heat output capacity of 5.8 kW. The capacity below which deficits are expected to occur lies at 5.5 kW though:

```ruby
DIVIDE(
  MAX(FEVER_DEMAND_CURVE(V(households_useful_demand_for_space_heating_detached_houses_before_1945))),
  V(households_useful_demand_for_space_heating_detached_houses_before_1945,number_of_units)
)*1000

5.466262439750358
```
