### ISSUE TITLE
Set scenarios to keep_compatible and apply missed migrations

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1393]
A while back we had an issue where saved_scenarios on ETModel were no longer automatically set to `keep_compatible`. This issue has since been addressed, but we have only set `keep_compatible` to `true` and applied missed migrations for the limited set of scenarios that we were aware of.

Users have indicated another set of scenarios that should be set to `keep_compatible` = `true` and for which any missed migrations should be applied:

- https://energytransitionmodel.com/saved_scenarios/15025
- https://energytransitionmodel.com/saved_scenarios/15024
- https://energytransitionmodel.com/saved_scenarios/15023
- https://energytransitionmodel.com/saved_scenarios/15022

@noracato I'm guessing this is enough information to work with. If not, let me know.

**Comment by MartLubben** [comment]
https://pro.energytransitionmodel.com/scenarios/1031350

**Comment by MartLubben** [comment]
**NPE scenario's:**
- NPE 2030: https://pro.energytransitionmodel.com/scenarios/1045605
- NPE 2035: https://pro.energytransitionmodel.com/scenarios/1045610
- NPE 2040: https://pro.energytransitionmodel.com/scenarios/1045612
- NPE 2050: https://pro.energytransitionmodel.com/scenarios/1045617 

**NPE - TEACOS-ready**
- NPE 2030: https://pro.energytransitionmodel.com/scenarios/1092620
- NPE 2035: https://pro.energytransitionmodel.com/scenarios/1092622
- NPE 2040: https://pro.energytransitionmodel.com/scenarios/1092627
- NPE 2050: https://pro.energytransitionmodel.com/scenarios/1092629 

**Halffabrikaten IPO:** 
PV20 – Groningen energytransitionmodel.com/scenarios/1022606
PV21 – Friesland energytransitionmodel.com/scenarios/1022604
PV22 – Drenthe energytransitionmodel.com/scenarios/1022602
PV23 – Overijssel energytransitionmodel.com/scenarios/1022610
PV24 – Flevoland energytransitionmodel.com/scenarios/1022603
PV25 – Gelderland energytransitionmodel.com/scenarios/1022605
PV26 – Utrecht energytransitionmodel.com/scenarios/1022611
PV27 – Noord-Holland energytransitionmodel.com/scenarios/1022609
PV28 – Zuid-Holland energytransitionmodel.com/scenarios/1022613
PV29 – Zeeland energytransitionmodel.com/scenarios/1022612
PV30 – Noord-Brabant energytransitionmodel.com/scenarios/1022608
PV31 – Limburg energytransitionmodel.com/scenarios/1022607

@Charlottevm en @jorisberkhout Missen jullie nog scenario's?

**Comment by noracato** [comment]
Hee @MartLubben! Dank voor de lijst. Weet je ook wanneer de scenarios zijn gemaakt en in welke periodes ze eventueel nog zijn aangepast? Dan kan ik een inschatting maken van welke migraties ze allemaal hebben gemist!

**Comment by MartLubben** [comment]
Hoi Nora, 

Dat weet ik niet precies. NPE was in november / december. IPO was veel eerder: @Charlottevm weet jij dat?

**Comment by Charlottevm** [comment]
IPO liep tot mei dus ik denk dat het veilig is om te stellen dat deze vanaf april geen migraties meer hebben gehad. 

Ter aanvulling heb ik nog deze scenario's voor Amersfoort, deze zijn wel op beta gemaakt mocht dit nog verschil maken?:
https://beta-pro.energytransitionmodel.com/scenarios/2505310
https://beta-pro.energytransitionmodel.com/scenarios/2505311
https://beta-pro.energytransitionmodel.com/scenarios/2505312
https://beta-pro.energytransitionmodel.com/scenarios/2505313
https://beta-pro.energytransitionmodel.com/scenarios/2505314
https://beta-pro.energytransitionmodel.com/scenarios/2505315

En nog scenario's voor ondersteuning NPE:
https://energytransitionmodel.com/scenarios/1032954 
https://energytransitionmodel.com/scenarios/1032956 
https://energytransitionmodel.com/saved_scenarios/14790 
https://energytransitionmodel.com/scenarios/1032945 
https://energytransitionmodel.com/scenarios/1032948 
https://energytransitionmodel.com/scenarios/1032949

**Comment by noracato** [comment]
Done for the top two posts with links!
