### ISSUE TITLE
Update broken data-export for household heat

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etengine#1395]
The Households heat curves download in the [Data export](https://energytransitionmodel.com/scenario/data/data_export/hourly-curves-for-household-heat) section is broken and should be fixed to match the new modelling of heat in the built environment. The proposed new design is as follows:

- Rows
  - 8760 hourly values
- Columns
  - Households space heating consumers FEVER_DEMAND_CURVE
  - Households space heating consumers FEVER_PRODUCTION_CURVE
  - Households space heating producers FEVER_DEMAND_CURVE
  - Households space heating producers FEVER_PRODUCTION_CURVE
  - Households hot water consumers FEVER_DEMAND_CURVE
  - Households hot water consumers FEVER_PRODUCTION_CURVE
  - Households hot water producers FEVER_DEMAND_CURVE
  - Households hot water producers FEVER_PRODUCTION_CURVE

This allows users to determine for which consumers deficits occur and for which producers deficits occur. A potential next step would be to provide the full information: DEMAND_CURVE and PRODUCTION_CURVE for all consumer-producer pairs. This would however increase the size of the download beyond what is useful.

- [x] Update the data export @noracato 
- [x] Update the locales on ETModel @mabijkerk

**Comment by noracato** [comment]
The buildings heat download uses the same underlying structure, so that one will be automatically updated as well. Keep that in mind when updating the locales.

**Comment by mabijkerk** [comment]
This is fixed on `heat-final-fixes`.
