### ISSUE TITLE
Expand application_demands_serializer with input capacity per carrier

### ISSUE THREAD

**Issue by KoenvanB** [quintel/etengine#1401]
**Feature request**
For project FiT we would like to expand the `application_demand` export with columns that specify the `input_capacity` for each carrier. Preferably, we would like a column for each carrier in the ETM, along the lines of `input_capacity_of_carrier`. 

**Background**
For project FiT we need to attribute system costs to end users based on the type of input carrier:

- end users are all nodes in the `costs_building_and_installations` group;
- system costs are costs for infrastructure, production and flexibility. 
- relevant input carriers are: `electricity`, `hydrogen`, `network_gas` and 'heat' (`ht/mt/lt_steam_hot_water`)

To give an example: a household air water heat pump (`households_space_heater_heatpump_air_water_electricity`)...
- consumes electricity, so it should be attributed a part of the costs for electricity production facilities;
- makes use of the electricity network and should therefore be attributed a fraction of the total electricity infrastructure costs;
- Similarly, it should be attributed a fraction of the costs for flexibility infrastructure regarding electricity, i.e. all conversion and storage facilities that output electricity.

The distribution key for attributing infrastructure and flexibility costs is the input capacity per carrier; hence the feature request.

**Comment by noracato** [comment]
@KoenvanB can I close this?

**Comment by KoenvanB** [comment]
Yes!

**Comment by KoenvanB** [comment]
This feature is no longer required within the pilot FIT project.
