### ISSUE TITLE
https://engine.energytransitionmodel.com/api/v3/scenarios is offline

### ISSUE THREAD

**Issue by Geoneer** [quintel/etengine#1417]
I use the URL [https://engine.energytransitionmodel.com/api/v3/scenarios] to do calculations from my 3D Geo model. 

The URL seems to be offline. 

Can you check the status of the server?

Thanks! :-)

![image](https://github.com/quintel/etengine/assets/218929/34147595-099b-45af-80af-98b3383e0aca)

**Comment by Geoneer** [comment]
https://engine.energytransitionmodel.com/api/v3/scenarios

**Comment by mabijkerk** [comment]
Hi @Geoneer, unfortunately the ETM server has been down. We're working to resolve the issue and hope to get it back online quickly. In the meantime the beta server is stable and running: [https://beta.energytransitionmodel.com/](https://beta.energytransitionmodel.com/).

**Comment by mabijkerk** [comment]
@Geoneer, the server is back online! Good luck with your work.
