### ISSUE TITLE
Edge processes in GQL are broken

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etengine#1426]
When I try to use a function like 'EGDES' I get the following error in the sandbox.

<img width="905" alt="Screenshot 2024-05-02 at 09 03 40" src="https://github.com/quintel/etengine/assets/150331345/080fe975-1df7-4591-8ca0-d336644cc00c">

It seems this error comes from the function edges_for in the 'traversal.rb'.
This function is used in quite some GQL-functions which can't be used at the moment.

**Comment by mabijkerk** [comment]
@kaskranenburgQ according to the comments I think you are supposed to add `V()` or `L()` to the node. That having said, the `EDGES()` function indeed appears to be broken. However, other GQL traversal functions do seem to be working, for example:

```
V(OUTPUT_EDGES(V(transport_final_demand_diesel)),demand)
```

As far as I can tell it not used in any queries at the moment, I would not give this priority until it becomes relevant for any new queries we want to write.

**Comment by kaskranenburgQ** [comment]
> As far as I can tell it not used in any queries at the moment, I would not give this priority until it becomes relevant for any new queries we want to write.


@mabijkerk let's not solve this for now then. Maybe a good idea to add this big to the documentation?
