### ISSUE TITLE
Error in balancing heating_households group in IP2024 scenario's on beta

### ISSUE THREAD

**Issue by kndehaan** [quintel/etengine#1430]
When changing an input of the heating_households group in the ETM, an error occurs in balancing: group sums to 100.1. This error occurs only on beta (not pro)  in at least the following scenarios:
- IP2024 2030 Climate ambition
- IP2024 2030 International ambition
- IP2024 2030 National drivers

The error does not occur in II3050 v2 scenarios or in a blanco NL 2050 scenario. 

<img width="926" alt="image" src="https://github.com/quintel/etengine/assets/102598197/6cf0dcbb-95e5-4f65-acda-782d15d19442">

**Comment by noracato** [comment]
Nice catch, we had this one before. It's possible for some regions to set `households_heater_crude_oil_share` through the API, but not via the interface. ETModel does not know about this input and balances to 100% without it, sending the results to the engine, who sees the crude oil share set to 0.1 already and starts to complain.

Best thing to do is to alter the scenario, removing the crude oil share as it should not have been there in the first place.
