### ISSUE TITLE
Change working of V() command in GQL

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etengine#1433]
The "V()" command is the most used command for querying data from the energy graph. 
It's documentation can be found [here](https://docs.energytransitionmodel.com/contrib/gql#core-functions).

At the moment the V() argument does not give any feedback about whether the given node actually exists within the code base. 
For instance, if we try look at the query `wet_biomass_to_export_in_biomass_sankey`, which is currently used in the biomass sankey, we see the following:
```

- unit = PJ
- query =
     DIVIDE(
      V(energy_export_wet_biomass, demand),
      BILLIONS
      )

```
The node that is referenced does not exist anymore in our active codebase. 
If we were to query this we see the following:

<img width="762" alt="Screenshot 2024-05-23 at 17 31 48" src="https://github.com/quintel/etengine/assets/150331345/b2c20d31-dce8-4626-b7fb-674685808e60">

The same happens while directly querying the query that is mentioned in the biomass sankey.
<img width="762" alt="Screenshot 2024-05-23 at 17 32 29" src="https://github.com/quintel/etengine/assets/150331345/ba230597-0daa-4f7f-9df0-4ef2e43c23c1">

While I could argue that the demand of the given 'element' is indeed zero, I don't think this information is of interest to us.
Therefore, I propose that we rewrite the V() command so that when an incorrect nodename is given to a query, the query returns 'nil', and not zero. 

This will give direct feedback to the modellers when they are working on graph alterations. 

The fallout of this will be large, because a lot of outdated query names are used in the output elements at the moment. 
These output elements will al break when we update the V() command in a direct way.

I would like to hear your opinion on this matter @kndehaan @mabijkerk @noracato

**Comment by kndehaan** [comment]
Sounds like very useful feedback to me if we rewrite the V() command, for future model improvements as well as for cleaning up outdated or malfunctioning queries. I don't know if it's easy to change the V() command? As you mentioned, the implications could be quite large so there should also be enough time budgeted to fix the  fallout.

**Comment by kaskranenburgQ** [comment]
In [this PR ](https://github.com/quintel/etengine/pull/1434)I changed the working of V().

However, the same happens if I query `wet_biomass_to_export_in_biomass_sankey`:

<img width="669" alt="Screenshot 2024-05-26 at 13 32 52" src="https://github.com/quintel/etengine/assets/150331345/e5f9e018-5475-42c8-85f5-82326f9533ff">

While without divide the query returns 'nil':
<img width="669" alt="Screenshot 2024-05-26 at 13 34 27" src="https://github.com/quintel/etengine/assets/150331345/102de5f4-c774-4e3c-b60a-a69ef9241d57">

It seems that PRODUCT, DIVIDE, SUM, ignore queries that return nil, as is stated in the [documentation](https://docs.energytransitionmodel.com/contrib/gql/)

**Comment by mabijkerk** [comment]
I get where you are coming from @kaskranenburgQ. I have a few thoughts though:

- Will a value of "nil" help us to spot an error more quickly? Will charts/dashboard elements/other calculations break when "nil" is returned?
- Can we imagine use cases where it is useful to have 0 returned? For example, if we want to query the sum of e.g. typical_input_capacity * number_of_units of a set of nodes. Then it might be fine that the nodes in that group that have no typical_input_capacity are processed and do not produce an error. There may be other use case @noracato?
- I would then rather build another function that is explicitly different from V(), which would then be used in the specific cases that we want to make sure that all values are returned.

In the future, I would suggest that we finish the discussion on whether or not we want to implement a feature before working on the implementation. Especially for functions that are this fundamental, a lot of fallout can be expected: queries need to be changed, tests (re)written. We therefore really need to be sure that we want to implement it and how we want to implement it.
