### ISSUE TITLE
Add active/mutable field to input parameters endpoint

### ISSUE THREAD

**Issue by robcalon** [quintel/etengine#1446]
When processing scenario parameters the inputs endpoint at https://engine.energytransitionmodel.com/api/v3/scenarios/xxxx/inputs provides valuable information on which parameters are active in the model and which parameters are disabled. Unfortunately, all parameters are set to disabled when accessing a read_only scenario making it harder to process read_only scenarios from this endpoint.

Would it be possible to add an addition flag to the input parameters to make a distinction between the parameter being used by ETEngine in evaluating the scenario and the current user being allowed to change the parameter via the API?

Additionally a third field could be desirable to indicate if an external coupling node has been activated. I currently see only two imperfect ways to check if an external coupling node is in use:

- **Check if an user value has been set for a external coupling parameter**
This unfortunately does not work in cases where the scenario uses another scenario as template as this will set the default value as the user value of the copied scenario.
- **Check disabled inputs that have a disabled_by field**
This is also not a viable option for read_only scenarios due to all parameters being listed as disabled (as described above).

Especially with the recently implemented multi user support for scenarios I'm expecting some issues when read_only users need to export scenario data via the API.

**Comment by robcalon** [comment]
@noracato could you also have a look at the options for this one?

**Comment by noracato** [comment]
Should be fixed now!

**Comment by robcalon** [comment]
Hi @noracato! 

I'm not sure if this issue is actually fixed as I still do not seem to be able to distinguish parameters that are disabled by the etengine in the scenario, e.g. "om_costs_water_mountains" in a nl2019 scenario between a the same scenario with only "scenario_vierwer" permissions. In both cases the parameter will be listed as "disabled".
