### ISSUE TITLE
Load shifting in industry can becomes price setting in scenario's where it is not active.

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etengine#1475]
In the following scenario : https://energytransitionmodel.com/saved_scenarios/18545

We see a very spiky price profile:
![Electricity price per hour 1238307](https://github.com/user-attachments/assets/e63f5f20-1aeb-4d09-b862-f842b094cf7a)

In this scenario, the following flex options are set:

- Batteries in households : Local forecasting algorithm
- Batteries in electric vehicles: Forecasting residual load
- Large-scale batteries: Forecasting residual load
- Load shifting in metal industry: 35% WTA 850
- Load shifting in other industry: 25% WTA 500
- Load shifting in metal industry: 20% WTA 2000
- Load shifting in central ICT industry: 55% WTA 75

In a lot of hours, the price is set to 2000. 

This is remarkable, since according to the merit order, the technology Hydro (mountain) should generate more than enough energy in this scenario, with a marginal cost of 2.49 EUR/MWh.

![Merit order table 1238307](https://github.com/user-attachments/assets/a8aab618-946e-4c32-9093-b73d9a49c3c4)

Now, there are 2 ways in which a price profile with a price of 2.49 occurs:

1. Setting the Batteries in households to no Forecasting algorithm
2. Shutting off the Load shifting in industry. 

For some reason, the forecasting algorithm (both the system and the local algorithm) takes over the price of the highest flex option (in this case, the load shifting in industry of the metal sector). 

This relates to part 4 of issue #1403. 

@louispt1 @noracato Would be great if one of you could have a look some time.

Notifying @mabijkerk .

**Comment by mabijkerk** [comment]
This is the same issue as indicated in https://github.com/quintel/etengine/issues/1403.
