### ISSUE TITLE
Discussion: Qernel::Queryable and Qernel::Plugin

### ISSUE THREAD

**Issue by antw** [quintel/etengine#463]
Hi all,

As I've finished working on [carrier-dependent efficiency](https://github.com/dennisschoenmakers/etengine/issues/364) and [dynamic loss slots](https://github.com/dennisschoenmakers/etengine/issues/345), I'd like to start a discussion on some of the bigger changes I made while implementing them, and provide an opportunity for objections to be raised _before_ merging. The merge is planned for immediately after the September 26th deploy.
## 

In the past, it has been difficult to customise the calculations performed by some Qernel objects; for example, to support demand-driven converters, a subclass of ConverterApi was added and is used only for converters in the "demand_driven" group. However this doesn't scale very well... what happens if we want a converter to have two or more custom behaviours? [Qernel::Queryable](https://github.com/dennisschoenmakers/etengine/blob/queryable/app/models/qernel/queryable.rb) and [Qernel::Plugin](https://github.com/dennisschoenmakers/etengine/blob/queryable/app/models/qernel/plugin.rb) will allow us to do this.
### Qernel::Plugin

Plugin is similar to ConverterApi: it defines attributes (calculations) for a Qernel object. In the past, we might have written something like this:

``` ruby
def full_load_hours
  function(:full_load_hours) do
    # calculation
  end
end
```

With Plugin, this becomes:

``` ruby
attribute :full_load_hours do |converter|
  # calculation
end
```

For a real-world example (with just one attribute), [see Plugins::Slot::Loss](https://github.com/dennisschoenmakers/etengine/blob/queryable/app/models/qernel/plugins/slot/loss.rb).
### Qernel::Queryable

Queryable is mixed into Qernel objects like Slot and Converter, and provide an easy way to define which plugins are used by the object, and therefore control how the object calculates its attributes.

To explain this better, let's go through [how Queryable is being used](https://github.com/dennisschoenmakers/etengine/blob/queryable/app/models/qernel/slot.rb#L57-72) on slots to dynamically calculate loss, and carrier-efficiency:

``` ruby
class Qernel::Slot
  include Qernel::Queryable

  def plugins
    plugins = [ Plugins::Slot::Base ]

    if carrier_efficient?
      plugins.push(Plugins::Slot::CarrierEfficiency)
    end

    if loss? && output?
      plugins.push(Plugins::Slot::Loss)
    end

    plugins
  end
end # Qernel::Plugin
```

Here we define that _every_ slot uses a `Base` plugin which contains attributes common to all slots. Those which have [carrier-efficiency](https://github.com/dennisschoenmakers/etengine/issues/364) data will also use the `CarrierEfficiency` plugin, while [loss slots](https://github.com/dennisschoenmakers/etengine/issues/345) will use the `Loss` plugin:

```
"Normal" slot plugins:           [ Base ]
Loss slot plugins:               [ Base, Loss ]
Carrier-efficient slot plugins:  [ Base, CarrierEfficiency ]
```

In these examples no slot has more than two plugins, but there is no practical limit to how many can be used. When we ask a slot for an attribute, it looks at each of its plugins in reverse order (e.g. Loss -> Base, CarrierEfficiency -> Base); the first one found which can calculate the requested attribute is used.

I would suggest reading the module documentation for **[Plugin](https://github.com/dennisschoenmakers/etengine/blob/queryable/app/models/qernel/plugin.rb)** and **[Queryable](https://github.com/dennisschoenmakers/etengine/blob/queryable/app/models/qernel/queryable.rb)** for more complete examples of how they can be used.
## Changes

_Please note that Queryable is currently used only on Slot, but examples below include other classes to show what will happen if/when Queryable is used throughout the Qernel._
### Instance Methods

Previously, "dataset attributes" were exposed as instance methods on the Qernel objects. For example you could call `slot.conversion`, `link.share`, or `converter.number_of_units`.

This is not ([officially](https://github.com/dennisschoenmakers/etengine/blob/queryable/app/models/qernel/legacy_attributes.rb)) supported with Queryable, and you should call `attr` instead:

``` ruby
slot.attr(:conversion)
link.attr(:share)
converter.attr(:number_of_units)
converter.attr(:total_costs_per, :mw_input)
```

This results in Qernel objects which are a bit leaner; they're not complicated by methods used for calculations, but the side-effect is that these calculations will look more verbose.

See: **[Queryable / Plugin examples using attr](https://gist.github.com/9e4cf0a63cd962e64cb7)**.
##### Alternatives:
- It would be possible to make this slightly less verbose [by instance_eval'ing plugin blocks](https://gist.github.com/e33b2de9420cc0a8b9a8); I don't like this because it seems too "magic" and isn't immediately obvious from where `attr` comes. It also makes it impossible to create "helper methods".
- If there are strong objections, we could re-enable calculations as instance methods, but this would require [some sort of DSL](https://gist.github.com/95e58075c19b3ba28d1d) so we would know ahead-of-time which methods to create. I'm also not a fan of this idea... however it _could_ be done.
### GQL

Plugin attributes are supported in GQL, without requiring any changes:

``` ruby
V(converter_name, number_of_units)
V(OUTPUT_SLOTS( V(converter) ), conversion)
```

However, string and lambda arguments are not supported:

``` ruby
# No.
V(converter, "demand / number_of_units")
V(converter, -> { demand / number_of_units })

# Yes.
V(converter, demand) / V(converter, number_of_units)
```
##### Alternatives
- Like with instance methods, [it would be possible to bring back](https://gist.github.com/ebf5ab80cadbeaef60fd) support for this if demand was high. However there would be a small performance hit, and I don't want to complicate the code if nobody cares about it.
### Speak now or forever hold your peace

If you depend on any of the features I have removed, or you dislike the current implementation, _please let me know_; anything can be changed at this stage.

Also, fire away with any questions...

Cheers all!

**Comment by ChaelKruip** [comment]
@antw is this still something we want to do?
