### ISSUE TITLE
Increase Security on GQL code

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etengine#464]
Right now, it is possible to run system commands from GQL:

```
V(agriculture_burner_crude_oil, `ls`)
```

We probably need [a SAFE=4 or something](http://www.ruby-doc.org/docs/ProgrammingRuby/html/taint.html)

**Comment by ChaelKruip** [comment]
This is a very old issue but in light of https://github.com/quintel/etengine/issues/929 perhaps relevant again?
