### ISSUE TITLE
Graph should be able to recalculate without the tricks now used for Merit Order

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etengine#495]
From graph.rb:

``` Ruby

        if use_merit_order_demands? && future?
          dataset_copy = Marshal.load(Marshal.dump(@dataset))
        end

        calculation_loop # the initial loop

        if use_merit_order_demands? && future?
          mo = Plugins::MeritOrder::MeritOrderInjector.new(self)
          mo.run
          detach_dataset!
          self.dataset = dataset_copy
          mo.inject_updated_demand
          calculation_loop
        end

```

**Comment by dennisschoenmakers** [comment]
Still relevant, @antw?

**Comment by antw** [comment]
> antw was assigned on Dec 7, 2012 [...] Still relevant, @antw?

A little late to the party, but... I *think* it is relevant, especially in light of the merit order now being enabled by default. However I don't see any way to integrate the demands of merit order participants *without* recalculating the whole graph.

There are probably smart solutions to this, such as finding all ancestors and descendants of the participants and recalculating only those, but the producers are so central to the network that this includes most nodes in the graph.

My feeling is that this is an item for the ETEngine v2.0 wishlist, should that day ever come. For the time being, I don't think we can do anything about this. 😞
