### ISSUE TITLE
NOTE: when adding import/export to Merit Order module we need to revisit merit_order_injector.rb

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#507]
This ticket serves as reminder that the current implementation of the communication between etengine and Merit is not robust for extension to import&export. In particular, the solution for [this ticket](https://github.com/quintel/etengine/issues/500) in [this commit](https://github.com/quintel/etengine/commit/04ddab299429a6234f0d467f1e09bfa6c235ba6b) need to take the possibility of import&export into account.

**Comment by jorisberkhout** [comment]
@ChaelKruip , is this (old) issue still relevant, or is it superseded by the fact that import/export is now implemented in the ETM?

**Comment by antw** [comment]
Good catch; it is not relevant anymore. The "injector" has long since been replaced with the plugin system.
