### ISSUE TITLE
Input::InputGQLError: Failed to calculate label value for costs_biomass input

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#533]
Apparently, the gquery `price_of_wood_pellets` following GQL:

```
PRODUCT(
              V(CARRIER(wood_pellets),"cost_per_mj * mj_per_kg"),
              KG_PER_TONNE
             )
```

...leads to an **error** on beta.et-engine.com, because `cost_per_mj` apparently is a `String`.

```
V(CARRIER(wood_pellets),cost_per_mj).class
=> String
```

**Comment by jorisberkhout** [comment]
Just checked this on the `beta-engine.energytransitionmodel.com`; works like a charm as
```
V(CARRIER(wood_pellets),cost_per_mj).class
=> Float
```
Closing.
