### ISSUE TITLE
Debug of gqueries and converter methods is broken

### ISSUE THREAD

**Issue by wmeyers** [quintel/etengine#552]
Both on beta and live

![screenshot 28-05-13 09 49](https://f.cloud.github.com/assets/1001341/571068/21880c6a-c76b-11e2-80c0-aa1c07b0b6a5.png)

* http://www.et-engine.com/data/latest/debug/gquery?gquery=V%28agriculture_burner_crude_oil%2C+total_costs_per%28%3Aplant%29%29
* http://beta.et-engine.com/data/220623/debug/gquery?gquery=Q%28dashboard_renewability%29

**Comment by jorisberkhout** [comment]
Seems to be working fine now. Closing.
