### ISSUE TITLE
Costs (pop-up) chart for very small testing grounds has weird axis labels

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#756]
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/5504070/181e3c00-877f-11e4-919c-d29a4d1dddbf.png)

**Comment by jorisberkhout** [comment]
Assigning @grdw .

**Comment by grdw** [comment]
Is this in relation with scaling? If so, to how many residences should I scale? I've chosen 50 but I don't get the same result as your 'testing ground'.

**Comment by jorisberkhout** [comment]
Not deploy critical, removing milestone.

**Comment by ChaelKruip** [comment]
Closing as this seems to have been solved.
