### ISSUE TITLE
Space heating options are counted double: implications for local testing grounds

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#757]
This is a known issue: some technologies such as combi-boilers are used both for hot water and space heating. 
The `number_of_units` are computed by multiplying the `number_of_residences` with the slider settings in both slides and the resulting number of combi-boilers can be **twice** the number of residences (if the sliders are 100% in both space heating and hot water). 

Perhaps we could take the average:

```
number_of_units_testing_ground = ( number_of_units_space_heating + number_of_units_hot_water ) / 2
```

**Comment by jorisberkhout** [comment]
Related to https://github.com/quintel/etmodel/issues/2185

**Comment by redekok** [comment]
Not relevant anymore. Closing this issue.
