### ISSUE TITLE
Scaling interface fails to load when logged in to ETM

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#759]
It seems that there is a problem loading the user-specific scenarios. Also see [this Airbrake message](https://quintel.airbrake.io/projects/35337/groups/1324481542975690741/notices/1324481542975690739).

**Comment by dennisschoenmakers** [comment]
I'll have a look at this @antw!

**Comment by antw** [comment]
Already fixed. :smiley:

The form would break if ETModel contained a saved scenario which had since been deleted on ETEngine.

**Comment by dennisschoenmakers** [comment]
:+1:
