### ISSUE TITLE
QUESTION: What is the recommended method for retreving debug info?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#766]
I have tried to use:

```
logger.debug "My string"
```
and
```
raise("My string")
```
in the body of [this function](https://github.com/quintel/etengine/blob/master/app/models/qernel/demand_driven_converter_api.rb#L55-L79) but that makes ETE crash in weird ways.

Using
```
puts "My string"
```
does not seem to result in any output (@dennisschoenmakers and I 'grep'ed on the log files but did not find any matches with the string).

**Comment by ChaelKruip** [comment]
Including @dennisschoenmakers

**Comment by antw** [comment]
```ruby
Rails.logger.info "Your message"
```

The message will go to `log/{development,staging,production}.log` depending on the environment in which you're running ETE.

> Using puts "My string" does not seem to result in any output

[Kernel#puts](http://ruby-doc.org/core-2.2.1/Kernel.html#method-i-puts) goes to the standard output, *not* the log; it will only work if ETEngine is running in the foreground (e.g. if you started it by running `rails server`).

**Comment by ChaelKruip** [comment]
Thanks @antw!
