### ISSUE TITLE
Adding descendants for scenarios to the api 

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#768]
Like discussed at https://github.com/quintel/etloader/issues/95

**Comment by grdw** [comment]
@ChaelKruip I now am able to grab the descendants of a certain scenario. Though, is this what we truly want, considering that we only want to use scaled scenarios for ETloader? Or do we also want to include non-scaled scenarios?

**Comment by ChaelKruip** [comment]
> Though, is this what we truly want, considering that we only want to use scaled scenarios for ETloader? Or do we also want to include non-scaled scenarios?

As discussed: it would be nice to show both (sorted by being scaled or not). With the 'units' working, we are able to import unscaled scenario's in ETLoader.

**Comment by grdw** [comment]
Closing this issue because the whole interface connected to this issue doesn't exist anymore.
