### ISSUE TITLE
The number_of_inhabitants does not update the households_appliances_other_electricity_efficiency

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etengine#777]
The slider number_of_inhabitants updates the electricity consumption of all the appliances in the demand except the households_appliances_other_electricity_efficiency.

![image](https://cloud.githubusercontent.com/assets/12493788/9270925/d6d057f8-4275-11e5-8a1b-d0868438a321.png)

**Comment by ChaelKruip** [comment]
Well spotted @georgiasavvidou. Because of the 'value freeze' we will postpone this to the January deploy.

**Comment by ChaelKruip** [comment]
@georgiasavvidou, for future reference: input's are part of the 'etsource' repository and issues about them should be created there.

**Comment by georgiasavvidou** [comment]
OK got that! Thanks!

On Mon, Aug 17, 2015 at 2:18 PM, Chael Kruip <notifications@github.com>
wrote:

> @georgiasavvidou <https://github.com/georgiasavvidou>, for future
> reference: input's are part of the 'etsource' repository and issues about
> them should be created there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quintel/etengine/issues/777#issuecomment-131797734>.
>



-- 

Georgia Savvidou

Quintel Intelligence
Atrium - Strawinskylaan 3051
1077 ZX  Amsterdam
The Netherlands

Visiting address:
Keizersgracht 639
1017 DT Amsterdam

T  : +31 (0)20 301 22 69
F  : +31 (0)20 301 22 02
M : +31 (0)6 476 613 92

E  : georgia.savvidou@quintel.com
I   : www.quintel.com and www.energytransitionmodel.com
