### ISSUE TITLE
The input transport_car_using_electricity_efficiency refers to both cars and trucks

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etengine#778]
Maybe change the transport_car_using_electricity_efficiency into transport_electric_vehicles_using_electricity_efficiency (electric vehicles is the name in the ETM interface) or transport_electric_car_truck_using_electricity_efficiency to avoid confusion?

**Comment by ChaelKruip** [comment]
The gains of changing this are too slim to justify the work IMO. Closing.
