### ISSUE TITLE
The input buildings_useful_demand_cooling_electricity does not refer to cooling

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etengine#779]
There are two inputs:
1. buildings_useful_demand_cooling
2. buildings_useful_demand_cooling_electricity

The first one refers to cooling but the second one refers to the slider electricity per building (see picture)

![image](https://cloud.githubusercontent.com/assets/12493788/9271100/9523c658-4277-11e5-9d70-6385dc363a94.png)

**Comment by ChaelKruip** [comment]
Well spotted @georgiasavvidou!

**Comment by ChaelKruip** [comment]
Assigning @mabijkerk as this might be a good exercise to learn about renaming input statements :)

**Comment by mabijkerk** [comment]
As far I was able to determine the slider has already been corrected. As I change the slider for electricity per building, the slider shows as buildings_useful_demand_electricity:
![Screenshot 2020-11-18 at 10 08 13](https://user-images.githubusercontent.com/67338510/99509383-fc95d880-2985-11eb-90b1-d7c4c18d6ada.png)

The corresponding input_elements file also shows the correct slider name:
![Screenshot 2020-11-18 at 10 09 45](https://user-images.githubusercontent.com/67338510/99509555-31099480-2986-11eb-9f04-84e5d0b4886b.png)

**Comment by ChaelKruip** [comment]
Great work @mabijkerk! Closing.
