### ISSUE TITLE
The inputs industry_useful_demand_electricity and industry_useful_demand_electricity_efficiency refer to the other industry

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etengine#780]
Maybe rename the inputs:
1. industry_useful_demand_electricity
2. industry_useful_demand_electricity_efficiency

to:
1. industry_useful_demand_for_other_electricity
2. industry_useful_demand_for_other_electricity_efficiency

in order to be consistent with the respective inputs for chemical industry and to avoid confusion.

**Comment by ChaelKruip** [comment]
:+1:
