### ISSUE TITLE
Issues with initialising the storage/conversion nodes for the present year

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#781]
When we calculate storage and conversion, we need to run Merit on the demand curve and, hour by hour, determine the amount of energy that is stored/converted.
This is relatively 'straightforward' for the future year, but for the present things are not so easy. Especially, I am worried about how to initialise the graph.

The problem is that we don't know which numbers to use for the initialisation of the graph. This is done by the analysis on etdataset and the resulting shares and preset demands on etsource. To be able to calculate the preset demands and shares, we would need to perform the whole 'Merit-storage-calculation' in the dataset analysis Excel. Worse than the InputExcel IMHO!

**What if we assume the storage/conversion to be zero for the present year?**

This is the most obvious approach but it has some drawbacks:
- We will not be able to handle start-years and countries for which the storage/conversion is non-zero in the present year. Currently, there are no such countries and start-years but that will rapidly change (hopefully).

**Comment by ChaelKruip** [comment]
Including @dennisschoenmakers @AlexanderWirtz @jorisberkhout @antw

**Comment by AlexanderWirtz** [comment]
Good point @ChaelKruip. I think this is the least bad solution. I agree that making the research analyses more complicated is not desirable. Still, you may not need to make them that complicated in order to obtain something that can initialize the graph.

**Comment by jorisberkhout** [comment]
This is still very relevant, but not deploy-critical as all flexibility related demands are currently zero in the start year. I will remove the milestone and assign myself.
