### ISSUE TITLE
Can we update AREA attributes?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#782]
As requested by @AlexanderWirtz and discussed by @antw.

We can already use the `UPDATE` method, for example for the `number_of_residences`:

``` GQL
UPDATE(AREA(), number_of_residences, 1)
```

We will have to put this into an input statement.

e.g.:

``` YAML
- query = UPDATE(AREA(), number_of_residences, USER_INPUT())
- priority = 2
- max_value = 1.0
- min_value = 0.0
- start_value = 0.0
- step_value = 1.0
- unit = x
- update_period = both
```

@AlexanderWirtz could you provide me with a list of which [area attributes](https://github.com/quintel/etsource/blob/ba3652a7b2b0c626d6def2958a1fc89303dc5b93/datasets/nl/nl.ad) you would like to give a certain number? 

Then we can update the scenario by 'tweaking' the user_values hash in the database.

I plan to re-assign to @twilkinson573 to create the missing inputs when we have some numbers, @AlexanderWirtz !

**Comment by antw** [comment]
> We can already use the UPDATE method, for example for the number_of_residences:

[This input actually exists already](https://github.com/quintel/etsource/blob/master/inputs/demand/households/households_misc/households_number_of_inhabitants.ad).

**Comment by dennisschoenmakers** [comment]
> This input actually exists already.

Excellent!

**Comment by AlexanderWirtz** [comment]
Here is a first suggestion. This is a lot to ask, so please consider this a s a negotiation. :smile: 
I have put the most important ones first:

### Wishlist

**Quite important**
```
- areable_land
- coast_line
- land_available_for_solar
- offshore_suitable_for_wind
- onshore_suitable_for_wind
- residences_roof_surface_available_for_pv
- buildings_roof_surface_available_for_pv
```

**Quite nice to have:**
``` 
- co2_emission_1990
- number_of_buildings
- number_of_inhabitants
- number_of_new_residences
- number_of_old_residences
```
**Nice to have:**
```
- has_fce
- has_metal
- has_other
```


### By the way
I noticed this attribute: `- number_of_residences = 7386743.0`
This seems redundant, after we specify `number_of_new_residences` and `number_of_old_residences`

**Comment by dennisschoenmakers** [comment]
@AlexanderWirtz: could you include (example) numbers for the inputs? They do not have to be definite, but it makes testing 1_000_000 times easier. :smile:

**Comment by ChaelKruip** [comment]
> I noticed this attribute: [...]

See https://github.com/quintel/etsource/issues/946

**Comment by AlexanderWirtz** [comment]
> @AlexanderWirtz: could you include (example) numbers for the inputs? They do not have to be definite, but it makes testing 1_000_000 times easier. :smile:

I do not know the numbers yet. They will be close to the numbers that have been scaled down based on inhabitants, but after scaling, I would like to be able to fine-tune them. 

For example: 
The area I am working on is more rural than the rest of the Netherlands, so after scaling by `number_of_inhabitants`, I expect the `areable_land` to be too low, etc. 

I want to set these to `false` *after scaling*:
```
- has_fce = false
- has_metal = false
- has_other = false
```

**Comment by AlexanderWirtz** [comment]
Question: which attributes are scaled down? All of the numeric ones?

**Comment by dennisschoenmakers** [comment]
The answer is found [here](https://github.com/quintel/atlas/blob/293795cb316529c6944d7f067f9738da9a2af2e0/lib/atlas/dataset.rb#L81-L106).

**Comment by jorisberkhout** [comment]
I believe this is no longer needed due to the new way of creating local datasets, right @grdw ? If so, could you close this issue?

**Comment by grdw** [comment]
I have no idea about the context of this issue, but it appears that inputs for `AREA` attributes already exist and are in use. So I guess this can be closed.

**Comment by jorisberkhout** [comment]
> I have no idea about the context of this issue

Given the age of the issue, probably nobody does anymore :wink: Thanks for the taking responsibility and closing this issue 😄
