### ISSUE TITLE
Correcting Conversion Efficiency Units in the Transport Useful Demand Section

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etengine#784]
As found out in https://github.com/quintel/etdataset/issues/626 ,all transport_(...)_kms converters have their conversion effiencies given as percentages, but physically these conversion effiencies should have units of km/MJ.

![38a4a2a4-5d4c-11e5-849f-2bf2784e9c47](https://cloud.githubusercontent.com/assets/14106387/9987441/3b572c0c-6048-11e5-9816-5d7e1e9024eb.png)

@antw, could you replace all '%' signs under conversion effiencies for all these converters with 'km/MJ'? Thanks!

**Comment by jorisberkhout** [comment]
Assigning @grdw .

**Comment by grdw** [comment]
> but physically these conversion effiencies should have units of km/MJ.

I see that it's hard-coded as a percentage. Is this only needed for `transport_car_using_electricity` or also for other converters? If so, which ones?

**Comment by antw** [comment]
>  could you replace all '%' signs under conversion effiencies for all these converters with 'km/MJ'? 

Before @grdw gets too far with this... would you each be receptive to including the km/MJ value separately, below the percentage (even though the number is the same)? The slot conversion being a *percentage* is fairly fundamental part of what a slot is, and I can imagine one day someone will see the km/MJ value without the accompanying percentage and get confused.

<img width="232" alt="screen shot 2016-01-21 at 13 43 53" src="https://cloud.githubusercontent.com/assets/4383/12482016/0e5d2d20-c045-11e5-9544-04299f806cc1.png">

```ruby
- if output_slot.carrier.key == :car_kms
  %div(style="font-size: 12px; color: #999")
    == (#{(100.0 * output_slot.conversion).round(2)} km/MJ)
```

**Comment by RobTerwel** [comment]
> would you each be receptive to including the km/MJ value separately, below the percentage (even though the number is the same)?

I think this is a better implementation than my initial suggestion, @antw ! I like it very much. Could you instead of just car_kms

````
if output_slot.carrier.key == :car_kms
  %div(style="font-size: 12px; color: #999")
    == (#{(100.0 * output_slot.conversion).round(2)} km/MJ)
````
also put truck_kms and shipping_kms and remove the multiplication with 100.0 (our cars are not that good yet :wink: )
````
if output_slot.carrier.key == :car_kms, :truck_kms, :shipping_kms
  %div(style="font-size: 12px; color: #999")
    == (#{(output_slot.conversion).round(2)} km/MJ)
````
(in correct notation, not sure if the above is), since the slots with these output carriers all have physical efficiencies of km/MJ?

**Comment by antw** [comment]
> remove the multiplication with 100.0

x100 is because the "raw" slot conversion value is a fraction (0.5 instead of 50%). [We do the same with the percentage value](https://github.com/quintel/etengine/blob/0cc7a5237ed38b85a97a9a8785c6857f41b62b0d/app/views/data/converters/_converter_links.html.haml#L40).

**Comment by RobTerwel** [comment]
> "raw" slot conversion value is a fraction (0.5 instead of 50%).

Exactly, but in this case this fraction is precisely what we're after: `transport_car_using_electricity` has an efficiency of 1.5385 km/MJ (not 153.85 km/MJ or 153.85%). The ETSource attribute `output.car_kms` (and the same holds for `output.trucks_kms` and `output.shipping_kms`) is given in km/MJ (which is the "raw" slot conversion value). Therefore, there is no need to apply  x100 anymore.

**Comment by antw** [comment]
:+1:
