### ISSUE TITLE
sustainability_share is calculated differently than expected

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#785]
The current sustainability value for the dashboard depends on gqueries of the form:

```
V(INTERSECTION(G(final_demand_group),USE(energetic))," demand * sustainability_share").sum / V(INTERSECTION(G(final_demand_group),USE(energetic))," demand").sum
```

Here, the `sustainability_share` is the main method to determine how sustainable the demand of a node is. The `sustainability_share` of, for example, the `agriculture_final_demand_network_gas` node is equal to 0.00253366622. 

What I would expect as the definition of the `sustainability_share` is:
```
sustainability_share = sum_of_sustainable_primary_demand / sum_of_primary_demand
```

When I manually perform the above calculation for 2012 in NL I end up with a slightly different number, however: 0.002714982.
Instead, the [code that calculates `sustainability_share`](https://github.com/quintel/etengine/blob/master/app/models/qernel/recursive_factor/sustainable.rb#L22-L31) seems to do something else: it traces the final carrier (`network_gas`) to the right in the graph until it hits the node where `network_gas` occurs for the first time (when starting from primary demand, or right). 

For this example, the node is `energy_national_gas_network_natural_gas`. When using the two carriers that made up `network_gas` (`greengas` and `natural_gas`) to find the `sustainability_share` I get the observed number:
```
3.49/(1374.49+3.49) = 0.00253366622
```

So, currently the `sustainability_share` is calculated by considering the carriers that make up the queried carrier. This calculation, therefore, does not take into account any losses further right of the `energy_national_gas_network_natural_gas` in this case. Making the conversion of biogas into greengas much less efficient would not change the `sustainability_share` of agriculture_final_demand_network_gas` whereas I have the feeling that it should!

Including @jorisberkhout @dennisschoenmakers @alexanderwirtz

**Comment by dennisschoenmakers** [comment]
Good catch @ChaelKruip!

**Comment by ChaelKruip** [comment]
Closing this issue because we want to stick with the current definition of renewability based on final demand (annoying as it may be).
