### ISSUE TITLE
NICE TO HAVE: query for bio footprint

### ISSUE THREAD

**Issue by antw** [quintel/etengine#790]
_From @ChaelKruip on October 7, 2015 15:6_

@AlexanderWirtz and myself have been dreaming up some charts to display relations between energy content and bio_footprint of carriers (and how much they are used in a scenario). Currently, the bio_footprint is [calculated in ETEngine](https://github.com/quintel/etengine/blob/master/app/models/qernel/graph_api.rb#L61-L71) but there is no easy way to use GQL to return the footprint of individual nodes. It would be great to be able to use queries of the form

```
V(some_node_using_electricity, "primary_demand_of_carrier * footprint_of_carrier")
```

I have tried some stuff already like:
```
V(CARRIER(biogas), typical_production_per_km2)
```
which returns a number. However,

```
V(INTERSECTION(G(final_demand_group),SECTOR(transport)), "supply_of_biodiesel * V(CARRIER(biodiesel), typical_production_per_km2)")
```
which returns an error. 

I also tried this:
```
V(INTERSECTION(G(final_demand_group),SECTOR(transport)).select {|node| node.input_slots.detect { |slot| slot.carrier.biodiesel? }}, V(CARRIER(biodiesel),typical_production_per_km2)).last
```
This returns a number but I'm not sure how to make that work with a node that does not uses the primary carrier but rather a final carrier such as electricity.

_Copied from original issue: quintel/etmoses#515_

**Comment by antw** [comment]
> However, [...] which returns an error.

This works:

```ruby
INTERSECTION(G(final_demand_group), SECTOR(transport))
  .sum { |con| con.query.supply_of_biodiesel * V(CARRIER(biodiesel), typical_production_per_km2) }
```

Not sure if it's what you're looking for though, and it requires dropping down from GQL to plain-Ruby, which isn't ideal...

**Comment by antw** [comment]
This versions avoids the pure-Ruby gymnastics:

```ruby
V(CARRIER(biodiesel), typical_production_per_km2) *
  SUM(V(INTERSECTION(G(final_demand_group), SECTOR(transport)), supply_of_biodiesel))
```

**Comment by ChaelKruip** [comment]
Thanks @antw!
