### ISSUE TITLE
How to model the hybrid heat pump?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#791]
In the second sprint of the ETMoses gas-infra project we will add the hybrid heat pump to the ETM (and ETMoses). This ticket is meant to discuss how to model this new technology in the graph.

# Background

DISCLAIMER: numbers mentioned here are indicative will be properly researched by @AlexanderWirtz before the start of the second sprint.

A hybrid heat pump (HHP) consists of a small electric heat pump of about 2 kW heat output capacity coupled with a combi-boiler using gas. Typically, the heat pump provides the 'base load' by heating water with outside temperature (15 degrees or so) to about 45 degrees which is appropriate for space heating. The gas fired boiler takes care of the following things:
* boost the temperature of the 45 degree water to higher temperatures (60 degrees typically) for hot tap-water consumption
* produce extra hot water for space heating if the capacity of the heat pump is insufficient
* produce extra hot water for space heating if the outside air temperature is too low for the heat pump to perform at a reasonable COP
* (ETMoses only) take over from the heat pump if the network is congested (depending on the strategy chosen)

# Considerations for the ETM

* In the ETM we separate hot water and space heating technologies, so likely the HHP for SH will have somewhat different specs (mainly COP) than the one for HW. Note that we also have to correct for the double counting of investment costs due to this doubling of technologies analogous to other combi technologies ([see this query](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/dashboard/dashboard_total_cost_correction.gql))
* The HHP really consists of two different technologies, each with their own carrier and efficiency. Which of these technologies produces most of the heat (has the most FLH) depends on the heat demand. 

# Possible solution directions

1. Model the HHP as multiple converters (separate converters represent the HP and the combi boiler)
2. Model the HPP as a single converter with dynamic efficiency and dynamic input of electricity and gas ratio depending on the demand for heat (FLH)

Option 1 is likely more 'clean' from the point of view of the graph but more complex when it comes to communication to the user: technology specs are not unambiguously defined requiring custom queries etc.

Option 2 is cleaner from GQL/front-end point of view but requires some new etengine capabilities:
* different ratio of input carriers depending on FLH
* different efficiency/COP depending on FLH (or ratio of input carriers)

## Possible implementation of Solution 1
Space heating:
![cursor_and_20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/10582170/d8138992-7686-11e5-8217-2c2df5f2d386.png)
Hot water:
![cursor_and_20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/10582377/ec91763a-7687-11e5-9637-37273bf76dde.png)
Note that for hot water, there is a fixed share of heat that must be provided by the combi boiler (CB) which corresponds to the the 'temperature jump' from 45 to 60. Even if the heat pump is not working at full capacity and 8760 hours per year, the CB must do part of the job.

@jorisberkhout @antw does the description above make sense to you? Do you see any viable other modelling options besides 1 and 2? Do you have a preference for either 1 or 2?

Including @dennisschoenmakers @AlexanderWirtz

**Comment by ChaelKruip** [comment]
After discussion with @jorisberkhout I am leaning more and more towards solution direction 1 (three nodes to model the hybrid heat pump). The main considerations:

# option 1 (three nodes)
## Pros
* COP and efficiencies for HP and CB part can be fixed which makes things more transparent for researcher and users and keeps the analysis in Excel relatively straightforward
* FLH for the HP and CB part can be treated separately
* No extra features in ETEngine are required (as far as I can see, please correct me if wrong @antw! perhaps we can run into issues like https://github.com/quintel/etsource/issues/937?)

## Cons
* GQueries will likely have to made which deal with the 'problem' of having some features of the HHP in separated nodes
* Input statements have to deal with the 'problem' of scaling the `number_of_units` several nodes simultaneously

# option 2 (using one node)
## Pros
* All specs and costs are contained in one node (simplifies GQL and Input statements)

## Cons
* ETEngine needs to be extended to do the following things:
  * Vary the relative (and absolute) input of gas and electricity as the FLHs vary
  * Vary the efficiency as a function of FLHs
* Not very transparent what we mean with the COP or efficiency of the HHP (depends on the demand/FLH)
* The data-analysis should include the same complex modelling of the HHP which decreases its transparency

I think that the modelling can be made equal for hot water and space heating (in contrast to the image above) and should look like this:
![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/10788204/52dfaba6-7d76-11e5-8f66-9ffe6e0e0f0b.png)
Here q1 and q2 add up to unity and are fixed shares which specify how much of the initial demand flows to either the heat pump or the combi-boiler part of the HHP. These shares will likely differ between the space heating and the hot water options. Finding shares that are representative for a large range of FLHs is the challenge here:

* For hot water, the shares are determined mostly by how much the CB has to do to heat the water from (typically 45 degrees) to 60 degrees. Secondary reason for the CB to run is when the hot water demand is higher than what the buffer and the capacity of the HP can satisfy (long showers etc.).
* For space heating the shares depend principally on how often the heat demand cannot be satisfied by the buffer and the capacity of the HP. Another reason might be that the outside temperature is too low and the COP of the HP is so bad that a CB is a smarter option.

@AlexanderWirtz @dennisschoenmakers @antw @jorisberkhout please read this wall of text (sorry about that) and give your opinions. This is an important decision to make and I would like to reach a broadly supported decision.

**Comment by antw** [comment]
This seems like it might have been a perfect candidate for the mythical "embedded graph" wherein the HHP converter could contain "sub-converters" which describe the separate components.

I'm biased towards the first option, if only because of "no extra features in ETEngine are required". :laughing:

If we could implement a generic solution in ETE (such as embedded graph) which could be reused to solve *other* problems, I would hugely favour that. Given that we definitely won't have the time for that, I prefer option 1 since it doesn't clutter up ETE with code that only solves one very specific problem. Option 2 likely affects Atlas (new attributes needed) and Refinery, and I'm not sure how much time that would consume.

I suggest we try option 1, and take another look another look at the embedded graph idea when time permits (early next year?).

**Comment by ChaelKruip** [comment]
> This seems like it might have been a perfect candidate for the mythical "embedded graph" wherein the HHP converter could contain "sub-converters" which describe the separate components.

I know! :sob: 

> I suggest we try option 1, and take another look another look at the embedded graph idea when time permits (early next year?).

:+1:

**Comment by dennisschoenmakers** [comment]
Agree 100% with you @antw and @ChaelKruip ! option 1 for now, and let's try to go for embedded graph  next year hopefully!

**Comment by AlexanderWirtz** [comment]
@ChaelKruip I finally got through the wall of text this time (sorry) and agree entirely with the choice for option 1. I also agree with the following:
> Finding shares that are representative for a large range of FLHs is the challenge here:

The FLH for heating will depend on the level of insulation of the average house the HHP is installed in. The ratio of q1/q2 will obviously change as demand for space heating changes. A devilishly difficult problem to model...

**Comment by ChaelKruip** [comment]
As discussed in https://github.com/quintel/etengine/issues/799, @dennisschoenmakers and myself opted to keep the q1 and q2 fixed for the moment. This simplifies the inclusion of HHPs.

**Comment by ChaelKruip** [comment]
Closing this discussion.
