### ISSUE TITLE
Can we download the layout (graph) as a pdf/eps/svg?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#796]
That would be handy.

How difficult is this @antw @grdw?

**Comment by dennisschoenmakers** [comment]
It's currently already an SVG object within the html page. Could we use something like:

```ruby
respond_to do |format|
  format.svg { render inline: svg}
end
```

**Comment by antw** [comment]
The layout is rendered entirely using JavaScript, so there's nothing on the Rails side that we could reuse to build this: it would have to be made from scratch.

We can already generate the graph layout from Refinery using GraphViz, but it's not nearly as readable. If we could find a way to reuse the converter positions from ETEngine and feed the into GraphViz, that would make the output far more useable.

**Comment by dennisschoenmakers** [comment]
> The layout is rendered entirely using JavaScript, so there's nothing on the Rails side that we could reuse to build this: it would have to be made from scratch.

Anything on the JavaScript side then?

**Comment by grdw** [comment]
You can convert an `svg` to a `png`. I had to investigate a little for ETMoses. I'm not sure if it's functional yet :sweat_smile: . I'm going to look into it tomorrow for ETMoses in https://github.com/quintel/etmoses/issues/604

**Comment by antw** [comment]
> You can convert an svg to a png. I'm going to look into it tomorrow for ETMoses in quintel/etmoses#604

:+1:

I have added a "save as SVG" option in the meantime:

![screen shot 2015-11-19 at 16 39 42](https://cloud.githubusercontent.com/assets/4383/11276971/3ab712fe-8edc-11e5-93db-80ca2c720351.png)

**Comment by jorisberkhout** [comment]
> You can convert an svg to a png. I had to investigate a little for ETMoses. I'm not sure if it's functional yet :sweat_smile: . I'm going to look into it tomorrow for ETMoses in quintel/etmoses#604

@grdw, what is the status of that search? Would you have time to pick this up?

**Comment by grdw** [comment]
> @grdw, what is the status of that search? Would you have time to pick this up?

Pretty much over. It's possible to [download](https://github.com/quintel/etmoses/blob/master/app/controllers/topologies_controller.rb#L65-L79) an SVG as a PNG.

**Comment by jorisberkhout** [comment]
> Pretty much over. It's possible to download an SVG as a PNG.

Would it be possible to implement something similar in ETEngine?

**Comment by antw** [comment]
> Would it be possible to implement something similar in ETEngine?

SVG download was added a month or two back. Go to the layout page, wait for the graph to load, and you should see this:

![screen shot 2016-01-30 at 14 52 05](https://cloud.githubusercontent.com/assets/4383/12696377/3b27117c-c761-11e5-9c93-dab3c2d45ea9.png)

Is PNG really needed? I'd prefer not to have to add RMagick to ETEngine just for this feature unless it were truly necessary.

**Comment by jorisberkhout** [comment]
@dennisschoenmakers , as you raised this issue, can it be closed?

**Comment by dennisschoenmakers** [comment]
Yes, it can be opened and edited in Illustrator.
