### ISSUE TITLE
Overflow feature needed for hybrid heat pump

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#799]
With the modeling of hybrid heat pumps as three nodes (see https://github.com/quintel/etengine/issues/791) we run into the following issue.

The combi-boiler part of the HHP is connected to both the collector and to the HP part as shown here:
![](https://cloud.githubusercontent.com/assets/1303760/10788204/52dfaba6-7d76-11e5-8f66-9ffe6e0e0f0b.png)

The reason for this: when the HP part cannot fulfil its part of the demand anymore, the combi boiler should fulfil that demand. 

The converters in the space heating and hot water section of the ETM are `demand driven` meaning that they scale their FLH to match the demand (keeping `number_of_units` and capacity fixed). Currently, the FLH can surpass their physical limit of 8760 hours per year without the ETM batting an eyelid. This means that the demand would never 'overflow' into the combi-boiler part of the HHP.

@antw would it be possible to make demand 'flow over' when the FLH of a converter reach 8760?
If this is difficult, we might reconsider to model the HHP as one converter but this would require both the efficiency and the inputs of carriers to depend on the demand (which sounds like more work in ETE to me).

**Comment by ChaelKruip** [comment]
Including @dennisschoenmakers @jorisberkhout @AlexanderWirtz

**Comment by AlexanderWirtz** [comment]
Is it time to revive the infamous 'flex_max' feature?

**Comment by ChaelKruip** [comment]
> Is it time to revive the infamous 'flex_max' feature?

Interesting suggestion! Perhaps that is easier in the end...
Using a 'cap' on the HP edge, the situation could be described as follows:
![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/11468999/c70490ea-9753-11e5-8be7-5f37d289adeb.png)

I am not sure if we can have both the 'fixed' q_1 and _q2 and the 'overflow' happening correctly though. @antw what do you think about all this?

**Comment by antw** [comment]
> @antw would it be possible to make demand 'flow over' when the FLH of a converter reach 8760?

We could probably add the option to hard-limit a demand-driven converter to 8760 hours without much difficulty. Do you think that would be enough to solve the problem?

> I am not sure if we can have both the 'fixed' q_1 and _q2 and the 'overflow' happening correctly though. > @antw what do you think about all this?

With flex-max, it is possible to assign a `priority` to edges to force one to be given preference over another. I don't think that solves the problem though as there is still the question of what to do with the overflow.

**Comment by ChaelKruip** [comment]
Thanks @antw for your feedback. After discussing this with @dennisschoenmakers I'm closing this issue as we decided to keep the shares fixed and ignore the 'overflow' feature for now.
