### ISSUE TITLE
DISCUSSION: what do we expect a single converter hybrid heat pump implementation to do?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#801]
Several issues suggest that it would be easier to model the hybrid heat pump (HHP) as one single converter:

* https://github.com/quintel/etengine/issues/800
* The fact that we would not need to create a lot of ugly gqueries summing the costs etc. of two converters

On the other hand, the HHP is complex and putting all that complexity in one converter may require new functionality in ETE. This ticket is meant to explore what exactly we would need from ETE and to see if this is feasible within the limited time we have (on this planet).

## Inputs and outputs

The HHP has one output carrier: useable_heat
The HPP has three input carriers: network_gas, ambient_heat and electricity

## Efficiencies / COP

The heat produced by the HHP should be the sum of three transformations:
* network_gas * gas_efficiency -> heat_from_gas
* electricity * electricity_efficiency -> heat_from_electricity
* ambient_heat * ambient_heat_efficiency -> heat_from_ambient_heat

The following boundary conditions hold for these three heat flows:

1. (heat_from_ambient_heat + heat_from_electricity) / electricity = COP = 4.5 or so
2. (heat_from_ambient_heat + heat_from_electricity) / heat_from_gas = F
where F is a fraction that can be changed by an input statement.

## Discussion

I have the feeling that most of the complexity lies in the last 'boundary condition'. @antw what do you think?

**Comment by ChaelKruip** [comment]
Including @jorisberkhout @AlexanderWirtz @RobTerwel @dennisschoenmakers

**Comment by antw** [comment]
To be clear: the converter will use electricity and gas simultaneously, rather than using electricity up to a limit, and then "failing over" to gas when the electricity limit is reached?

I don't really understand what the desired *behaviour* of the HHP converter is. You want to be able to set the heat input conversion (efficiency) using an input, and have the ambient heat input be dynamic, or...?

(not knowing what a "boundary condition" is doesn't help. :grimacing:)

**Comment by ChaelKruip** [comment]
> the converter will use electricity and gas simultaneously, rather than using electricity up to a limit, and then "failing over" to gas when the electricity limit is reached?

Yes indeed. With hindsight, the ""failing over" to gas" behaviour is a bit too complex for what we need at this point IMO.

> I don't really understand what the desired behaviour of the HHP converter is. 

I want the ratio of heat_produced_with_gas to heat_produced_with_ambient_heat_and_electricity to be flexible (adjustable by an input statement). 

Say the demand for heat is 100 PJ, and the ratio is 1/4 I expect the consumption of gas to be:
```
gas_consumed = (0.25 * 100 / efficiency_of_gas_heater) PJ,
```
the consumption of electricity to be
```
electricity_consumed = (0.75 * 100 / COP_of_heat_pump) PJ,
```
and the ambient_heat consumed to be
```
ambient_heat_consumed = (0.75 * 100 * (1.0 - 1 / COP_of_heat_pump)) PJ.
```

So for the ambient_heat and the electricity the following relation holds:
```
heat_produced_with_ambient_heat_and_electricity = electricity_consumed + ambient_heat_consumed,
```
and the COP is defined as follows:
```
COP = (electricity_consumed + ambient_heat_consumed) / electricity_consumed.
```

> (not knowing what a "boundary condition" is doesn't help. :grimacing:)

Sorry about that. In this case all I meant is to pose extra conditions that the system should respect.

**Comment by ChaelKruip** [comment]
To make the above more numeric: 
* COP = 4.5
* efficiency_of_gas_heater = 1.0
* heat_demand = 100 PJ
* fraction_of_hp_to_gas = 0.25

This would mean that:
* gas_consumed = 25 PJ
* electricity_consumed = 75/4.5 = 16.66666...
* ambient_heat_consumed = 75 * 0.7777777778 = 58.33333...

**Comment by dennisschoenmakers** [comment]
I guess the 'final end solution' to this kind of problem would be a subgraph, a long term wish: in that case we could ask the 'sub energy system' that is a hybrid heat pump installation for it's costs, it's full load hours, etc. which would all be defined on the *sub system* level. I guess this is a good approach given the current limitations.

**Comment by antw** [comment]
> To make the above more numeric [...]

I'm not sure why the amount of heat demand (in PJ) is significant. If the user is choosing what share of the input should be gas, is it not simple to adjust the electricity and ambient_heat conversions like so?

```ruby
# USER_INPUT() == fraction_of_hp_to_gas

UPDATE(INPUT_SLOTS(V(hhp), network_gas),  conversion, USER_INPUT())
UPDATE(INPUT_SLOTS(V(hhp), electricity),  conversion, 0.2222 * (1 - USER_INPUT()))
UPDATE(INPUT_SLOTS(V(hhp), ambient_heat), conversion, 0.7777 * (1 - USER_INPUT()))
```

Having to hard-code the electricity and ambient heat conversions is a bit ugly, but would be okay in the short-term.

I suppose we'd have to hard-code suitable starting values for the slot conversions also:

```
- input.network_gas = 0.25
- input.electricity = 0.16666
- input.ambient_heat = 0.5832
```

I suspect I'm missing something obvious. :laughing:

**Comment by ChaelKruip** [comment]
> I suspect I'm missing something obvious. :laughing:

You are 100% correct @antw! @RobTerwel and myself are experimenting with exactly the kind of input statements as you describe. The first results are hopeful :smile:

**Comment by ChaelKruip** [comment]
Closing this as we have proven that this is feasible.
