### ISSUE TITLE
create new method to calculate required additional network capacity

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etengine#803]
This is part of https://github.com/quintel/etmodel/issues/1961 where I describe the background of the network calculation. The current issue deals with the core of the calculation.

**Current implementation**

Currently we calculate the required additional network capacity in a set of Gqueries (e.g. `network_lv_net_delta_peak_load_max.gql`), in which we compare the additional peak load on the that voltage level to the total available capacity on that voltage level. This calculation is performed for five of the six different voltage level in the ETM.

**Proposed implementation**

We would like to replace the total available capacity by a distribution of the available capacity over the subnets within that voltage level. I have obtained these distribution from Alliander (and will place them in a Gist). I have successfully implemented the following calculation in a Python script and would like to have a similar ETEngine method such that I can implement it in the ETM. Below I describe this method.

*Inputs*
The method would require three inputs:
- The total additional peak load, obtained from e.g. `Q(network_lv_net_peak_load_we)`; this inputs needs to be variable as we would have to perform the same method for different additional peak loads
- The total capacity of the voltage level; this can be obtained from the respective node file and needs to be an input to this method
- The distribution of the available capacity over the subnets in this voltage level. This is a new piece of data (available here: [LV data](https://gist.github.com/jorisberkhout/be194614c9602d1c8fb7), [MV data](https://gist.github.com/jorisberkhout/1edfa91fe141fb8f9510) and [HV-MV data](https://gist.github.com/jorisberkhout/8e692b86c39309fd4091)) and basically consists of a list of 20 data points (between 0 and 1) describing which fraction of the network is still available. Different voltage levels require different distributions which are stored in different files. As an option for this method, I would like to be able to select which of these distributions to use (I propose to use the name of the file as an identifier, but am open to suggestions)

*Calculation*

For ease I have defined the inputs as follows
`L_p`: additional peak load
`C_tot`: total capacity of the voltage network
`a_i`: the i-th entry of the distribution
`n`: is the number of entries in the distribution file (for now 20, but this might vary in the future)

Based on the above inputs the following calculation needs to be performed:

`C_tot = SUM ( MAX ( L_p / n - C_tot / n * a_i , 0 ) ) `

*Output*

The method needs to output a single number, i.e. the required additional capacity over all subnets in that voltage level

I will then connect the existing Gqueries to this new method (and will create a separate issue for this).

Two points to be addresses are (I will create separate issues for this):
- [ ] where to store the distribution files? (I propose somewhere on ETSource)
- [ ] how to specifiy which distribution file to use?

Assigning @dennisschoenmakers .

**Comment by dennisschoenmakers** [comment]
@jorisberkhout thanks! could you:
* add a list of and link to all the queries that need updating?

With regards where to store the distribution files: I think they belong in the country's dataset/year directory. Could you put them in a separate folder, and one for every node?

@antw I would like to ask you to make an estimate on time required to implement this technically.

**Comment by dennisschoenmakers** [comment]
@jorisberkhout: could you also add a numeric calculation example? So we could write the spec and be sure it calculated correctly

**Comment by jorisberkhout** [comment]
> could you add a list of and link to all the queries that need updating?

The following Gqueries would need to be updated (I will do this once the new method would be available):

- [network_hv_mv_trafo_delta_peak_load_max.gql](https://github.com/quintel/etsource/blob/master/gqueries/modules/network/network_impact_calculations/hv_mv_trafo/network_hv_mv_trafo_delta_peak_load_max.gql)
- [network_lv_net_delta_peak_load_max.gql](https://github.com/quintel/etsource/blob/master/gqueries/modules/network/network_impact_calculations/lv_net/network_lv_net_delta_peak_load_max.gql)
- [network_mv_d_net_delta_peak_load_max.gql](https://github.com/quintel/etsource/blob/master/gqueries/modules/network/network_impact_calculations/mv_d_net/network_mv_d_net_delta_peak_load_max.gql)
- [network_mv_lv_trafo_delta_peak_load_max.gql](https://github.com/quintel/etsource/blob/master/gqueries/modules/network/network_impact_calculations/mv_lv_trafo/network_mv_lv_trafo_delta_peak_load_max.gql)
- [network_mv_t_net_delta_peak_load_max.gql](https://github.com/quintel/etsource/blob/master/gqueries/modules/network/network_impact_calculations/mv_t_net/network_mv_t_net_delta_peak_load_max.gql)

**Comment by jorisberkhout** [comment]
> With regards where to store the distribution files: I think they belong in the country's dataset/year directory. Could you put them in a separate folder, and one for every node?

I have pushed these distribution files for the NL dataset to a separate branch on ETSource (`load-distrbutions` (apologies for the typo in the branch name :smile:). The files are called:

- `network_hv_mv_trafo_distribution.csv`
- `network_lv_net_distribution.csv`
- `network_mv_d_net_distribution.csv`
- `network_mv_lv_trafo_distribution.csv`
- `network_mv_t_net_distribution.csv`

We currently only support the network calculation for NL.

**Comment by dennisschoenmakers** [comment]
@jorisberkhout could you add a link to that etsource commit?

**Comment by jorisberkhout** [comment]
> @jorisberkhout could you add a link to that etsource commit?

https://github.com/quintel/etsource/commit/25b253bd2bc1bbd74f8d690c267891541640a07c

**Comment by antw** [comment]
> where to store the distribution files? (I propose somewhere on ETSource)
> how to specifiy which distribution file to use?

I suggest we add a new attribute to Atlas::Node so that you may specify the distribution file:

```
- capacity_distribution = network_mv_d_net_distribution
```

(I'm not sure about the name, we can change that as you see fit).

> @antw I would like to ask you to make an estimate on time required to implement this technically.

Given that all of the data seems readily available, implementing the method seems pretty simple. I would estimate a day, maybe two. I would want to add support to Atlas to read the distribution files (with some simple tests), add a Node attribute to associate the node with the CSV file, and then create the method in ETEngine.

@jorisberkhout Just so I'm clear, would you expect to call the new method like this?

```ruby
V(
  some_network_converter,
  required_additional_network_capacity(Q(network_lv_net_peak_load_we))
)
```

This provides the additional load calculated with another query. The total capacity of the network could probably be read from the Converter attributes instead of having to be provided explicitly.

**Comment by jorisberkhout** [comment]
> could you also add a numeric calculation example?

In the table below I provide one numerical calculation example per voltage level, so you can test the individual voltage levels one by one

| Voltage level | input: Additional peak load (`L_p`) (MW) | input: Total capacity of the voltage network (`C_tot`) (MW) | Expected output (MW) |
|---|---|---|---|
|`hv_mv_trafo`| 20,000.0 | 37,830.0 | 8,053.2 |
|`lv_net`| 100,000.0 | 98,179.2 | 17,431.3 |
|`mv_d_net`| 50,000.0 | 72,000.0 | 10,144.0 |
|`mv_lv_trafo`| 50,000.0 | 67,790.4 | 11,510.6 |
|`mv_t_net`| 50,000.0 | 50,921.2 | 19,141.8 |

**Comment by jorisberkhout** [comment]
> @jorisberkhout Just so I'm clear, would you expect to call the new method like this?

Indeed.

> The total capacity of the network could probably be read from the Converter attributes instead of having to be provided explicitly.

Good idea. So far I simply added the `network_capacity_available_in_mw` and `network_capacity_used_in_mw`. If possible, I suggest we do the same in the new method.

**Comment by antw** [comment]
> > Just so I'm clear, would you expect to call the new method like this?
>
> Indeed.

![](https://i.imgur.com/CRIcP.gif)

(Sorry :laughing:)

In which case, I think one day is fair for the technical implementation. 1.5 if you want to be cautious, but I don't see any complicating factors.

BTW, thanks for the clear and detailed explanation!

**Comment by jorisberkhout** [comment]
:laughing:

**Comment by antw** [comment]
All done!

@jorisberkhout: [Atlas](https://github.com/quintel/atlas/commit/43c3a241b2ba64c4fac82e66823373fb676dd36a) and [ETEngine](https://github.com/quintel/etengine/commit/45bbde8bf4f46fc3b1e7e2610aed137f12394afe) are updated, and [I assigned the appropriate `capacity_distribution` attributes](https://github.com/quintel/etsource/commit/074d4bd79aa678430b51f83194ab4396274732b9) on your load-distrbutions ETSource branch. ETEngine (beta) has not been deployed with these changes yet, but we can do so whenever you're ready.

If the names `capacity_distribution` and `required_additional_network_capacity_in_mw` don't meet with your approval, let me know what you'd prefer and I'll get them changed.

**GQL:** (locally)

```ruby
EACH(
  V(energy_power_transformer_mv_hv_electricity,       required_additional_network_capacity_in_mw(20_000.0)),
  V(energy_power_lv_network_electricity,              required_additional_network_capacity_in_mw(100_000.0)),
  V(energy_power_mv_distribution_network_electricity, required_additional_network_capacity_in_mw(50_000.0)),
  V(energy_power_transformer_lv_mv_electricity,       required_additional_network_capacity_in_mw(50_000.0)),
  V(energy_power_mv_transport_network_electricity,    required_additional_network_capacity_in_mw(50_000.0))
)
```

**Results:**

```ruby
[
  8,053.205,           # hv_mv_trafo  expected: 8,053.2
  17,431.292799999996, # lv_net       expected: 17,431.3
  10,144.0,            # mv_d_net     expected: 10,144.0
  11,510.626400000005, # mv_lv_trafo  expected: 11,510.6
  19,141.752799999995  # mv_t_net     expected: 19,141.8
]

```

*(Thank you for [that table of expected results](https://github.com/quintel/etengine/issues/803#issuecomment-163586090); that was very helpful!)*

**Comment by dennisschoenmakers** [comment]
Super fast!

**Comment by jorisberkhout** [comment]
> All done!

Wow, that's fast, thanks!

> If the names `capacity_distribution` and `required_additional_network_capacity_in_mw` don't meet with your approval, let me know what you'd prefer and I'll get them changed.

These certainly meet my approval, so no changes required there.

I'm going to work on implementing it in the relevant Gqueries right away.
