### ISSUE TITLE
 Data from P2H and P2G from Merit needs to be taken into account in future graph

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#806]
See https://github.com/quintel/merit/issues/135 for the information that Merit collects.

There are two of these quantities that affect the other energy flows in the graph:

* Amount of gas produced by P2G: we have decided to mix the produced hydrogen gas from P2G into the gas-network. This would require the `energy_flexibility_p2g_electricity` to be updated with the production after Merit has done its calculation. The  `energy_flexibility_p2g_electricity`-node will be connected to the national gas network as follows:
![beta_et-engine_com_data_latest_layout_edit](https://cloud.githubusercontent.com/assets/1303760/11956423/64c53d6c-a8ba-11e5-8778-b60af4a804d6.png)
The graph should be re-calculated with the new gas-mix.

* Amount of heat produced by P2H: the heat has to be used to satisfy a share from the `households_useful_demand_for_hot_water_for_houses_with_p2h`. The share needs to follow dynamically from the amount of heat produced by the P2H technology and the demand of `households_useful_demand_for_hot_water_for_houses_with_p2h`:
![beta_et-engine_com_data_latest_layout_edit](https://cloud.githubusercontent.com/assets/1303760/11957634/258372e6-a8c3-11e5-8831-2a7201b68c6f.png)

I would say that the share `households_useful_demand_for_hot_water_for_houses_with_p2h`-to-`households_flexibility_p2h_electricity` is given by:
```
share = V(households_flexibility_p2h_electricity, demand) / V(households_useful_demand_for_hot_water_for_houses_with_p2h, demand).
```

This fraction is guaranteed to be smaller than 1 because the hot water demand profile which the P2H technology uses in Merit is scaled to match `V(households_useful_demand_for_hot_water_for_houses_with_p2h, demand)` (see https://github.com/quintel/merit/issues/131).

**Comment by jorisberkhout** [comment]
The P2H part of this is closed. The (temporary) approach for P2G is described in https://github.com/quintel/etmodel/issues/1966#issuecomment-181845948. Closing this issue.
