### ISSUE TITLE
Question: Why is the test GQL executed in a view and not in the controller?

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#811]
See relevant line: https://github.com/quintel/etengine/blob/master/app/views/data/gqueries/_result.html.haml#L2

Might be a possible clean-up.

**Comment by antw** [comment]
Because it's ancient. :laughing: There's no technical reason that I'm aware of.

Feel free to change it!

**Comment by grdw** [comment]
> Because it's ancient.

I hoped that that was the answer haha. :smile: 

> Feel free to change it!

Cool. :+1:
