### ISSUE TITLE
Adding a number_of_units attribute to converters

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etengine#813]
## Background

We have some methods in ET-Engine to calculate the number_of_units attribute based on their <a href="https://github.com/quintel/etengine/blob/master/app/models/qernel/converter_api/helper_calculations.rb">capacity<a/> and one specifically for (space/water heating technologies) <a href="https://github.com/quintel/etengine/blob/master/app/models/qernel/demand_driven_converter_api.rb">demand_driven converters<a/>.

There are, however, plenty of converters where a `number_of_units` attributes is wanted, but where these methods return 0. Especially when it comes to scalability and costs, this can even be necessary for other methods to return correct values. For instance in https://github.com/quintel/etsource/issues/800 , we need a `number_of_units` attribute for two car technologies to correctly calculate extra investments costs (otherwise these costs will just be multiplied by 0, the `number_of_units` returned as of now).

## First attempt

I simply added a `number_of_units` attribute to `transport_car_using_hydrogen`in ETSource, added this attribute to the list of numeric attributes in <a href="https://github.com/quintel/atlas/blob/master/lib/atlas/node.rb">note.rb<a/> in Atlas, set my Gemlock to my local Atlas in ETEngine and put `V(transport_car_using_hydrogen,number_of_units)` in the GQL sandbox, which worked and gave me the value I had initially put. 

## Problem

However, when I created a new scenario, I got a lot of errors of 'nil cannot be coerced into float' and my dashboard wouldn't appear. Debugging the total cost calculation led me to <a href="https://github.com/quintel/etengine/blob/master/app/models/qernel/converter_api/conversion.rb#L146-L147">conversion.rb<a/> : 
````
when :converter
      cost * number_of_units
````
 I figured this is because ETEngine, now that number_of_units is a converter attribute, looks for it in every converter and returns nil if it is not included in the list of converter attributes. This belief was strengthened by the fact that the error arose in `agriculture_burner_crude_oil`, the first converter given our folder structure.

## Possible solution

The best possible possible solution that came to my mind is the following (however, I don't know how hard it is to implement): make `number_of_units` an 'optional' attribute, such that ETEngine picks it up if it is included in the particular converters attributes, but 'skips' the converter (and doesn't return number_of_units = nil) if it is not there and then executes other `number_of_units` calculations mentioned at the start of this ticket.

This solution has the advantage it doesn't require the development of new `number_of_units` calculation methods and that other converters which would benefit from or need a `number_of_units` attributes could easily get one as well.

@antw , what are your thoughts, do you think this is easily implemented, do you foresee any trouble, or would you perhaps know a better solution (one that allows us to either calculate or define the number_of_units for converters without capacities)?

**Comment by antw** [comment]
@RobTerwel Would you mind pushing your ETSource and Atlas changes to branches on GitHub? I'll take a look and see what I can do.

**Comment by RobTerwel** [comment]
> Would you mind pushing your ETSource and Atlas changes to branches on GitHub?

Sure, ETS is <a href="https://github.com/quintel/etsource/compare/h2_number_scaling">h2_number_scaling<a/> and Atlas is <a href="https://github.com/quintel/atlas/compare/new_attributes">new_attributes<a/>. Thanks!

**Comment by RobTerwel** [comment]
Great work, @antw ! Thanks for making this possible, also in such a small timespan!

**Comment by antw** [comment]
> The best possible possible solution that came to my mind is the following: make number_of_units an 'optional' attribute

This has been done in 13dd4ce5, and all the queries are executing correctly for me.

> I figured this is because ETEngine, now that number_of_units is a converter attribute, looks for it in every converter and returns nil if it is not included in the list of converter attributes.

This was pretty much correct. Most converters would get a `number_of_units` set to `nil`, since they had no value defined in ETSource. I've set it so that any converter with no NoU will compute the value as before.

**Comment by RobTerwel** [comment]
:+1:
