### ISSUE TITLE
Dynamic calculation of weighted average of output.useable_heat seems static

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etengine#814]
On the ETSource branch `hhp_if_statement` I added the following attributes to the `households_space_heater_hybrid_heatpump_air_water_electricity` node:
- output.useable_heat.network_gas = 1.067
- output.useable_heat.electricity = 1.0
- output.useable_heat.ambient_heat = 1.0

Based on the input shares, ETE then calculates the weighted average of `output.useable_heat`. When I run 

``` 
V(households_space_heater_hybrid_heatpump_air_water_electricity, useable_heat_output_conversion)
```

in the GQL sandbox I get 1.0125585754451745, which indeed is the weighted average of the input.CARRIER times the respective output.useable_heat.CARRIER (input.network_gas = 0.187441424554827). In short:

```
input.network_gas * 1.067 + (1 - input.network_gas) * 1.0 = 1.0125585754451745
```

Changing the insulation level of old houses, that of new houses, the number of old houses or that of new houses (inputs can be found on the same branch), update the converter specs as follows:

```
UPDATE(INPUT_SLOTS(V(households_space_heater_hybrid_heatpump_air_water_electricity), electricity), conversion, input_conversion_electricity)
```

This should update the `input.electricity` attribute, and therefore result in a different weighted average of `output.useable_heat`. However, running the same query in the sandbox returns the same, initial value. It seems like this output is not updated dynamically. <a href="https://github.com/quintel/atlas/blob/master/lib/atlas/slot/carrier_efficient.rb">Here<a/> in Atlas it is said it should be.

@antw , am I perhaps overlooking something or do you know how this `output.useable_heat`could be determined dynamically?

**Comment by ChaelKruip** [comment]
Thanks @RobTerwel for writing this down so clearly :+1:

**Comment by RobTerwel** [comment]
> Thanks @RobTerwel for writing this down so clearly :+1:

Thanks, @ChaelKruip ! :blush:

**Comment by antw** [comment]
I don't think that this is supported in ETEngine; it's a feature of Atlas/Refinery used to create the data which is fed into ETEngine. The documentation does not make that very clear, sorry. The only such dynamic calculation in ETEngine [is for loss](https://github.com/quintel/etengine/blob/5f96908e6377d866fcde6acf98b48d6d091f0131/app/models/qernel/slot/elastic.rb).

I'm not sure how robust such a feature would be in ETE since it calculated from output to input, but provided we know the input shares ahead of time – and I think we do – we can probably implement this. But, I'm sorry to say that I'm reasonably sure this is not *currently* supported in ETEngine.

> Thanks @RobTerwel for writing this down so clearly 

Yes indeed!

**Comment by RobTerwel** [comment]
Thanks a lot for clearing this up, @antw ! 

@ChaelKruip , shall I make a ticket for implementation of this feature?

**Comment by jorisberkhout** [comment]
How urgent is this, @ChaelKruip and @RobTerwel . I prefer removing it from the deploy milestone.

**Comment by RobTerwel** [comment]
Hmm... it is a bug, but the max error in efficiency it could give is about 1.3%. This is because the weighted average in the present is 1.0125585754451745 (for min insulation) and converges to 1.0 (for max insulation). Therefore, if the present value is static (which it is now), the max. deviation is quite small.

I also don't know how much work a fix for this would be, but I think it's safe to say that we can postpone this as there are some more important issues to be solved and the deploy is nigh upon us. Do you agree @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> o you agree @ChaelKruip ?

Yes!

**Comment by jorisberkhout** [comment]
Removing milestone then.
