### ISSUE TITLE
How to feed hydrogen into the gas-network

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#822]
P2G creates a certain amount of hydrogen which we want to 'pump' into the gas-network. In the graph this means that the P2G node is right of the gas-network:
![etengine_dev_data_latest_layout](https://cloud.githubusercontent.com/assets/1303760/12818203/1acc0a24-cb56-11e5-9670-de79e20c3746.png)

I tried to use a `reversed_flexible` edge similar to power plants but that does not seem to work, though. 
The hydrogen does not seem to make it into the gas-network:
![energytransitionmodel](https://cloud.githubusercontent.com/assets/1303760/12818173/fb8b48b4-cb55-11e5-89df-19ed806c57f0.png)

Making the edge to `energy_treatment_natural_gas` flexible did not fix this for me.

@antw (perhaps @RobTerwel) do you have any suggestions of how to make this work?

**Comment by ChaelKruip** [comment]
You can view the work in [the flexibility branch](https://github.com/quintel/etsource/tree/flexibility)

**Comment by antw** [comment]
Will look into it now.

**Comment by antw** [comment]
Do the slot conversions not [come from Atlas+Refinery](https://github.com/quintel/etengine/blob/3cda4b839e4f179a88fab3f639731893fae5bd3b/app/models/etsource/dataset/import.rb#L206-L208) and then get updated by a "share of green gas" input? The only exception to this is elastic (loss) slots.

The only solution I can think of is to special-case P2G and (re-)calculate the slot conversions after merit has run.

**Comment by ChaelKruip** [comment]
Perhaps I am not understanding this correctly but I don't see how slot conversations need to be dynamic. Couldn't we do the same as with power plants? Keep all conversations fixed but adjust the energy flow through the node?
With power plants, the number of units and full load hours determine production but for p2g the total input of electricity determines production. So I would expect we require a different type of update statement (setting energy flow directly rather than NoU and FLH) rather than dynamic slot conversions.

**Comment by jorisberkhout** [comment]
Moved to storage milestone.

**Comment by jorisberkhout** [comment]
As discussed, this proved to be harder than expected. We decided to go for an alternative approach and use the hydrogen from power-to-gas in the transport sector. Therefore this issue is no longer deploy-critical; I will remove the milestone. The issue stays relevant however.
