### ISSUE TITLE
Perhaps this will speed up our production server?

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etengine#826]
https://www.hetzner.de/en/hosting/produkte_rootserver/dx151

Relevant since the Merit Order is now on by default.

**Comment by dennisschoenmakers** [comment]
What do you think @antw?

### CPU

Single Intel® Xeon® 
E5-2600 v3 @ 2.40GHz Octa-Core incl. 
Hyper-Threading Technology

### RAM 

RAM64 GB DDR4 ECC RAM
optional max. 192 GB
(at additional cost)

### SSD (optional)
240 GB 6 Gb/s SSD DC Edition

**Comment by ChaelKruip** [comment]
Also relevant for ETMoses?

**Comment by antw** [comment]
Lets look into some benchmarks after the deploy. A *quick* first look suggests that the single core performance of the E5-2630v3 isn't any better than the E3-1270v3 we already use. Single core performance is (unfortunately) what matters for us.
