### ISSUE TITLE
Expand ETEngine API for ETMoses to question the attributes for technologies dynamically

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#828]
Right now the attributes we query for ETMoses are defined [here](https://github.com/quintel/etengine/blob/master/app/models/api/v3/converter_stats_presenter.rb#L4-L17). However as @ChaelKruip and I noticed yesterday, a lot of those don't make any sense to even question in the first place on a per technology basis. It's incorrect from a physics-perspective and semantically a bit skewed from an IT perspective.

In light of https://github.com/quintel/etmoses/issues/740 I would suggest to remove the static frozen Hash and instead take an extra argument with a dynamic array of attributes you would like to question. 

You would get something like this:

``` ruby

module Api
  module V3
    class ConverterStatsPresenter
      attr_reader :key

      def initialize(key, gql, attributes)
        @key = key
        @gql = gql
        @attributes = attributes

        unless @gql.present_graph.converter(@key)
          fail "Missing converter: #{ @key }"
        end

        @present = @gql.present_graph.converter(@key).converter_api
        @future  = @gql.future_graph.converter(@key).converter_api
      end

      def as_json(*)
        @attributes.each_with_object({}) do |attr_key, hash|
          hash[attr_key] = {
            present: @present.public_send(attr_key),
            future:  @future.public_send(attr_key)
          }
        end
      end
    end # ConverterStatsPresenter
  end # V3
end # Api

```

**Comment by antw** [comment]
> In light of quintel/etmoses#740 I would suggest to remove the static frozen Hash and instead take an extra argument with a dynamic array of attributes you would like to question.

Yes! I think it would be good to specify the attributes on a per-converter basis:

```json
{
  "converter_key_1": ["attr1", "attr2"],
  "converter_key_2": ["attr2", "attr3"]
}
```

However, the attribute names **must** be whitelisted before `public_send`'ing anything; we don't want anyone requesting the `exit`attribute.

```ruby
module Api
  module V3
    class ConverterStatsPresenter
      PERMITTTED_ATTRIBUTES = %i(attr1 attr2 attr3).freeze

      # ...

      def as_json(*)
        (@attributes & VALID_ATTRS).each_with_object({}) do |attr_key, hash|
          # ...
        end
      end
    end # ConverterStatsPresenter
  end # V3
end # Api
