### ISSUE TITLE
[Airbrake] 845: NaN not allowed in JSON

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#832]
**Airbrake error:** [#7882](https://quintel.airbrake.io/projects/32233/groups/1657110342408247882)
**Airbrake project:** ETE

**Error type:** `JSON::GeneratorError`
**Error message:** `845: NaN not allowed in JSON`
**Where:** `api/v3/scenarios#update`
**Occurred at:** Apr 05, 2016 09:03:13 UTC
**First seen at:** Apr 05, 2016 09:02:26 UTC
**Occurrences:** 28 (0 since last deploy on `<no information>`)

**URL:** [https://engine.energytransitionmodel.com/api/v3/scenarios/288136](https://engine.energytransitionmodel.com/api/v3/scenarios/288136)
**File:** `/gems/json-1.8.2/lib/json/common.rb`

**Backtrace:**
```
/gems/json-1.8.2/lib/json/common.rb:223:in generate
/gems/json-1.8.2/lib/json/common.rb:223:in generate
/gems/activesupport-4.1.5/lib/active_support/json/encoding.rb:96:in stringify
/gems/activesupport-4.1.5/lib/active_support/json/encoding.rb:34:in encode
```

**Comment by dennisschoenmakers** [comment]
Hey Anthony, could you check this out? Someone playing with our API and triggered this error, or...?

**Comment by antw** [comment]
The fix is on its way to staging, and I'll cherry-pick it to production since that's where the error was raised.

**Comment by antw** [comment]
The cause, by the way, was that the scenario in question set all the cost sliders to -100%. This will have resulted in a division-by-zero in the cost gqueries used by the charts.

<img width="463" alt="screen shot 2016-04-05 at 10 28 00" src="https://cloud.githubusercontent.com/assets/4383/14278078/cf06d360-fb1d-11e5-9054-d4e6e5e60263.png">

**Comment by dennisschoenmakers** [comment]
> the scenario in question set all the cost sliders to -100%.

![](https://media.giphy.com/media/wEZUqNBMl9r7q/giphy.gif)
