### ISSUE TITLE
QUESTION: does the primary_demand_of method depend on link-groups?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#838]
In the context of https://github.com/quintel/etmodel/issues/2110 I seem to remember that the [primary_demand methods](https://github.com/quintel/etengine/blob/master/app/models/qernel/recursive_factor/primary_demand.rb) had some relation to the link-groups defined for edges.

This seems to be confirmed by the observation that adding a [compressed_network_gas edge to the `final_demand` link-group](https://github.com/quintel/etsource/pull/1112/commits/c7ce96808f8d0a560f736bd17dee65ec6a6496c5) did have impact on the outcome of a `primary_demand_of_natural_gas` query (details will be posted in https://github.com/quintel/etmodel/issues/2110 later).

@antw can you shed some light on this?

**Comment by jorisberkhout** [comment]
The issue discussed in quintel/etmodel#2110 has been solved.

It would still be interesting to know the answer to the question in this issue.

**Comment by antw** [comment]
> I seem to remember that the primary_demand methods had some relation to the link-groups defined for edges

The primary demand methods do look for a `primary_energy_demand` group on *converters/nodes* (the [calls to `primary_energy_demand?` here](https://github.com/quintel/etengine/blob/5e2f6fe33eff64fd4dc0e4e0d1330ca4eb33ac07/app/models/qernel/recursive_factor/primary_demand.rb#L63-L93), but I don't recall (nor can I find) any relation in the ETEngine code between primary demand and the `final_demand` group. The `final_demand` method [looks for converters in the "final_demand" group](https://github.com/quintel/etengine/blob/0617072fb5e88b3b58fe9a228af0f70cc6759ed6/app/models/qernel/recursive_factor/final_demand.rb#L25) in much the same way.

As far as I am aware, link groups are only used to implement [some queries relating to final demand](https://github.com/quintel/etsource/tree/f9eafa3c0293c28e52bf00eea3568dc630f6640b/gqueries/general/final_demand/mece)  (#618).

**Comment by jorisberkhout** [comment]
Can this be closed, @ChaelKruip ?
