### ISSUE TITLE
Importing the result of a converter calculation.

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#843]
In relation to PR #841, is it possible to import the result of a converter calculation instead of an converter attribute? For instance: `fixed_cost_per(:plant)` or should this be done in another fashion?

**Comment by antw** [comment]
That's a reasonable thing to want to do. Given the need to whitelist permitted attributes, you could kill two birds with one stone:

```ruby
class ConverterStatsPresenter
  # A map of attributes which may be requested and a proc which will retrieve
  # the attribute from a converter.
  ATTRIBUTES = {
    # Simple attributes.
    demand:                      nil,
    electricity_output_capacity: nil,
    input_capacity:              nil,

    # Custom fetchers.
    fixed_cost_per_plant: -> conv { conv.fixed_cost_per(:plant) }
  }

  def as_json(*)
    @graph_attributes.each_with_object({}) do |key, hash|
      fail "Invalid attribute: `#{ key }'" unless ATTRIBUTES.key?(key)

      attribute = ATTRIBUTES[key] || key.to_proc

      hash[key] = {
        present: attribute.call(@present),
        future:  attribute.call(@future)
      }
    end
  end
end
```

The alternative would be to only permit attributes/methods which don't accept an argument, and get that data via a Gquery. But that seems long-winded.
