### ISSUE TITLE
Change 'staging' branch to 'master' branch

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#854]
Everytime I make changes to ETEngine I find out that the staging branch is set to [staging](https://github.com/quintel/etengine/blob/master/config/deploy/staging.rb#L19) (which makes sense) instead of master, which is the case for any other project, ETModel and ETMoses.

Could we synchronize this? 😄

**Comment by antw** [comment]
I agree. I think that's easy enough to set up in Semaphore...
