### ISSUE TITLE
It would be cool to have a method for local CO2 emission

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#855]
One of our clients would like to know *where* CO2 is emitted in stead of who is responsible for primary emissions. In other words: "Where does the CO2 come out of the tailpipe, smokestack or chimney?"
We currently don't have a method to calculate this local CO2.

The closest I have come to find a solution for this is by looking up the `co2_conversion_per_mj` for specific carriers:
![energytransitionmodel](https://cloud.githubusercontent.com/assets/1303760/16990407/33275932-4e98-11e6-802a-8f74456d9989.png)
 and try to use this in a gquery.

There are several complications with trying to solve this in GQL:
* Only energetic transformations should be accounted for
* Some converters have the same input carrier as output carrier, so the difference should be used
* Some converters convert a carrier containing CO2 into another one containing CO2, so the difference should be used
* Some carriers don't have a `co2_conversion_per_mj` attribute: mixed carriers (e.g., network_gas, diesel_mix) cannot get this static attribute so it should be computed

I am curious about any ideas of how to solve this @antw @dennisschoenmakers @jorisberkhout @RobTerwel

**Comment by ChaelKruip** [comment]
After some discussions with @RobTerwel and @jorisberkhout I am hopeful to use the `weighted_carrier_co2_per_mj` method (see also weighted_carrier_co2_per_mj) to create gqueries of the form (pseudo code):

```
CO2-emission-of-node = CO2-coming-in - CO2-going-out
```
where,
```
CO2-coming-in = SUM_OVER_INPUT_SLOTS( weighted_carrier_co2_per_mj * demand_of_carrier )
``` 
and
```
CO2-going-out = SUM_OVER_OUTPUT_SLOTS( weighted_carrier_co2_per_mj * demand_of_carrier )
``` 

I am not sure if this works for carriers without any 'intrinsic' CO2 such as `electricity` and `useable_heat`. 

@antw do you think the approach sketched above has any chance of success?

**Comment by antw** [comment]
> ```
> CO2-coming-in = SUM_OVER_INPUT_SLOTS(weighted_carrier_co2_per_mj * demand_of_carrier)
> CO2-going-out = SUM_OVER_OUTPUT_SLOTS(weighted_carrier_co2_per_mj * demand_of_carrier)
> ```

Is `weighted_carrier_co2_per_mj` the attribute from the converter?

**Comment by ChaelKruip** [comment]
> Is `weighted_carrier_co2_per_mj` the attribute from the converter?

In my understanding `co2_conversion_per_mj` is a carrier attribute and the `weighted_carrier_co2_per_mj` is a method of the converters (which bases its results on the recursive weighted summation of the `co2_conversion_per_mj` attributes along the paths).

**Comment by antw** [comment]
> In my understanding co2_conversion_per_mj is a carrier attribute and the weighted_carrier_co2_per_mj is a method of the converters 

It is; sorry for the misunderstand. It just looked like you were using it as an attribute or method of the slots. It is indeed a method on the converter. Could this therefore be simplified as:

```ruby
# Assuming input >= output
(converter.input - converter.output) * converter.weighted_co2_conversion_per_mj
```

That seems too simple, so maybe I'm missing something?

* What happens with converters which have a `loss` slot? Is that loss included as "output"?

**Comment by ChaelKruip** [comment]
> That seems too simple, so maybe I'm missing something?

I hope that it's that simple! 😄 

> What happens with converters which have a loss slot? Is that loss included as "output"?

I think it would work if we either ignore loss or count loss as "output" with weighted_co2_conversion_per_mj == 0. What has your preference @antw?

**Comment by ChaelKruip** [comment]
Perhaps we could specify a zero `co2_conversion_per_mj` in the [AD file of the loss carrier](co2_conversion_per_mj)?

**Comment by ChaelKruip** [comment]
@antw how can I turn the above code into working GQL?

```
V(  G(final_demand_group), "(converter.input - converter.output) * converter.weighted_co2_conversion_per_mj")
```

Does not work nor does


```
V(  G(final_demand_group), "(input - output) * weighted_co2_conversion_per_mj")
```

**Comment by antw** [comment]
>  how can I turn the above code into working GQL?

With this monstrosity:

```ruby
MAP(
  G(final_demand_group),
  -> {
    weighted_carrier_co2_per_mj * (
      converter.inputs.sum(&:external_value) -
      converter.outputs.reject(&:loss?).sum(&:external_value)
    )
  }
)
```

This will ignore energy loss when calculating the total output (I'm assuming none will have loss as *input*, so I didn't bother filtering it out there).

**Comment by ChaelKruip** [comment]
> With this monstrosity:

Do you think it would be worth it to define new GQL methods to query 'input' and 'output' of nodes? Then we could do:

```
V(  G(final_demand_group), "(input - output) * weighted_co2_conversion_per_mj")
```

**Comment by ChaelKruip** [comment]
I (finally) had a clear moment... The reason that I formulated the 'query' based on slots (and their carriers) in https://github.com/quintel/etengine/issues/855#issuecomment-247322728 is that we want to see how much CO2 comes in *contained in carriers* and subtract the CO2 that is taken out of the converter by (possibly other) carriers. 

Example: Node A converts 1 PJ of oil (having CO2/PJ = 0.0755 Mton) without loss into heat. The result should be 0.0755 Mton of CO2.

The problem with simply using:
```
V(  G(final_demand_group), "(input - output) * weighted_co2_conversion_per_mj")
```
is that the input and output are all expressed in energy but contain no information about the carriers. 

In our example, the result would be zero Mton of CO2 because input == output.

**Comment by antw** [comment]
> we want to see how much CO2 comes in contained in carriers and subtract the CO2 that is taken out of the converter by (possibly other) carriers.
>
> The problem with simply using: [...] is that the input and output are all expressed in energy but contain no information about the carriers.

I think this implies that all the input and output slots need a carrier with a `co2_conversion_per_mj` value? Perhaps it can be assumed that any slot without a `co2_conversion_per_mj` can use the `weighted_co2_conversion_per_mj` from the converter?

**Comment by ChaelKruip** [comment]
> I think this implies that all the input and output slots need a carrier with a co2_conversion_per_mj value?

Right.

> Perhaps it can be assumed that any slot without a co2_conversion_per_mj can use the weighted_co2_conversion_per_mj from the converter?

I think it makes more sense to assign `co2_conversion_per_mj` of zero to those slots.

**Comment by ChaelKruip** [comment]
Another approach (which I'm currently exploring) is to simply use:
```
V(converter, "weighted_carrier_co2_per_mj * demand")
```
for converters which energetically use a CO2-bearing carrier (i.e., burning stuff) and make custom queries for all exceptions (for example a converter where gas is transformed into fertiliser and non-energetic CO2 is emitted).

**Comment by ChaelKruip** [comment]
Closing as this has been resolved by https://github.com/quintel/etengine/commit/7e805d85b167b77a36faa727c6211e33b9e8c11d
