### ISSUE TITLE
[Airbrake] [Production] Could not find a dataset with the key "be"

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etengine#856]
**Airbrake error:** [#7538](https://quintel.airbrake.io/projects/32233/groups/1738354635822767538)
**Airbrake project:** ETE

**Error type:** `Atlas::DocumentNotFoundError`
**Error message:** `Could not find a dataset with the key "be"`
**Where:** `api/v3/areas#show`
**Occurred at:** Jul 26, 2016 11:20:10 UTC
**First seen at:** Jul 26, 2016 11:20:10 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://engine.energytransitionmodel.com/api/v3/areas/be](https://engine.energytransitionmodel.com/api/v3/areas/be)
**File:** `[GEM_ROOT]/bundler/gems/atlas-5077e5609d65/lib/atlas/active_document/finders.rb`

**Backtrace:**

```
[GEM_ROOT]/bundler/gems/atlas-5077e5609d65/lib/atlas/active_document/finders.rb:38:in find
[PROJECT_ROOT]/app/models/etsource/loader.rb:49:in area_attributes
[PROJECT_ROOT]/app/models/area.rb:3:in get
[PROJECT_ROOT]/app/controllers/api/v3/areas_controller.rb:22:in show
```

**Comment by jorisberkhout** [comment]
I assume that `be` is for Belgium. We don't have a Belgian dataset (yet). Assigning myself to look into this.

**Comment by jorisberkhout** [comment]
Un-assigning myself as can't figure out what is going on. Not critical though.

**Comment by antw** [comment]
> as can't figure out what is going on. 

Welcome to my world. :tada:

**Comment by antw** [comment]
I can't figure it out either. None of our apps refer to the `be` region, nor are there any old scenarios in the database using it. Can't find any text in ETModel which refers to the `api/v3/areas/...` addresses either.

**Comment by dennisschoenmakers** [comment]
Perhaps somebody was probing for a `be` dataset? :grinning:
