### ISSUE TITLE
rake etsource:validate doesn't work

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#877]
This process returns a:

````
NoMethodError: undefined method `each_file' for #<Etsource::Topology:0x007fc7737c1f90>
````

I think because `each_file` was removed some long time ago. Can this rake task be removed? Considering that atlas does most of the validation of the graph I can imagine.

**Comment by antw** [comment]
> Can this rake task be removed? 

Yes, I suspect this Rake task was used with the old ETSource, prior to us using `.ad` files and Atlas.
