### ISSUE TITLE
Another approach to creating scaled local datasets

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#883]
I've learned today from @jorisberkhout that a graph can be initialized by using only the `demands` of all converters and some values from a `<area>.ad` file. It currently doesn't work that way, but it might be a way to setup a local dataset and thus the local graph. 

The idea is as follows:

1. From an existing scenario you export all the present demands from all converters to a csv/yml/ad file
2. Than you can scale those demands by simply dividing them by `{ scaling_value }`
3. Than you'd probably create another `.ad` file for a local scenario (for instance: `nl_groningen.ad`).
4. Perform some witchcraft between connecting the `.ad` file to the scaled demands
5. Use `Atlas` (`rake debug`) to calculate the local graph and suggest corrections where needed
...
6. Get rich

**Comment by grdw** [comment]
@antw Me and @jorisberkhout were sort of wondering if this sounds doable?

**Comment by antw** [comment]
This is similar to an idea we had some weeks back; it feels like a step in the right direction, but there is quite a big drawback to storing the demands of *all* converters. Here's a hypothetical subgraph, and we've set the demand of all the nodes somehow (ad, csv, etc):

```
        +--------------------+
Format: | Node name (demand) |
        +--------------------+

- - - - - - - - - - - - - - - - - - - - - - - - - -

+--------+
| A1 (2) |  \
+--------+   \   +--------+
              -  | B1 (3) |
+--------+   /   +--------+  \
| A2 (1) |  /                 \
+--------+                     \   +--------+
                                -  | C1 (7) |
+--------+                     /   +--------+
| A3 (1) |  \                 /
+--------+   \   +--------+  /
              -  | B2 (4) |
+--------+   /   +--------+
| A4 (3) |  /
+--------+
```

If you want to set a custom demand for `B2`, how would we go about doing that? For the graph to still add up correctly, you also have to manually set a value for the child nodes `A3` and `A4`, and the parent node `C1`. If you want to customise `A3` you also have to enter a new values for `B2 and `C1`. In a large graph, with hundreds of nodes, this might border on impossible.

An alternative idea was that instead of storing *all* demands, store only those which are set with queries in `.ad` files, and also store the shares and efficiencies from the full-size dataset (shares and efficiencies should be the same in both the national and local datasets, unless the creator chooses to customise those values as well). That would give you a "sparse graph" which might look like this:

```
+--------+
| A1 (2) |  \
+--------+   \   +--------+
              -  | B1 (?) |
+--------+   /   +--------+  \
| A2 (1) |  /                 \
+--------+                     \   +--------+
                                -  | C1 (?) |
+--------+                     /   +--------+
| A3 (1) |  \                 /
+--------+   \   +--------+  /
              -  | B2 (?) |
+--------+   /   +--------+
| A4 (3) |  /
+--------+
```

*(This assumes that the demands of `A1-4` are set using queries in `.ad` files; Refinery figures out the demands of the other nodes).*

Now you can enter a custom value for `A3` and Refinery will work out the rest.

It would still be possible for you to set an incorrect value (e.g. `C1`=8), but Refinery will complain that the demands don't add up, giving you the chance to correct the mistake. You could enter a custom value for `A3` (e.g. `A3`=4) and Refinery will fill in the blanks:

```
+--------+                     /           +--------+                     /
| A3 (6) |  \                 /            | A3 (6) |  \                 /
+--------+   \   +--------+  /             +--------+   \   +--------+  /
              -  | B2 (?) |        ->                    -  | B2 (9) |
+--------+   /   +--------+                +--------+   /   +--------+
| A4 (3) |  /                              | A4 (3) |  /
+--------+                                 +--------+
```

---

Both of these still suffer another problem (which, to be fair, every solution to local datasets seems to have): what if the *structure* of the graph changes? For example, if we remove `B2` entirely, and connect `A3` and `A4` to `C1`, do all the local datasets have to be recreated? Sadly I don't have any solution to this. 😞 

```
+----+
| A1 |  \
+----+   \   +----+
          -  | B1 |
+----+   /   +----+  \
| A2 |  /             \
+----+                 ---  +----+
                       ---  | C1 |
+----+                /  -  +----+
| A3 |  --------------  /
+----+                 /
                      /
+----+               /
| A4 |  -------------
+----+
```

**Comment by grdw** [comment]
>  Sadly I don't have any solution to this

*This is me thinking out loud:*

Hmmm, [my first solutions](https://github.com/quintel/internal/tree/local-datasets/planning/projects/local-datasets#how-to-accomplish-the-desired-situation) to the local datasets are all based upon the false assumption that people are editing `etsource` directly but that's just all generated from `etdataset`. Than again what people are currently editing for a local scenario are the present values in the graph (which might be an incorrect action to begin with):

So:

````
ETDataset (1)
    |
    v
ETSource (2)
    |
    v
ETEngine (3)
    |
    v
ETModel (4)
````

1. What if I create a local dataset here? -> There's no data, so too bad
2. What if I create a local dataset here? -> Nobody edit's those files, so nobody understands them properly. It's all automatically generated. 
3. What if I modify the graph here to make a pretend local dataset? -> That's not maintainable.
4. What if I modify my scenario here to make a pretend local dataset? -> That's the current way of doing things which is causing headaches.

---

So a question: 

In your example you have `A1` which comes directly from ETSource. So an example of an `A1-A4` type box is: `households_new_houses_useful_demand_for_heating` which stems directly from `datasets/nl/shares/residences_useful_demand_for_space_heating_after_insulation_parent_share.csv`. 

- However, I'm now sort of wondering how that share translates to a demand at `households_new_houses_useful_demand_for_heating`? 

---

Still; my idea to automatically generate a scaled dataset inside of ETsource doesn't sound super retarded. I mean, you *generate* a local dataset inside ETSource (nobody reads those files anyways). Than you would still need a way to modify that dataset. That cannot be done in `ETDataset` simply because there's no data (Isn't there really?) 🤔 ... so you go to ETEngine? However, my idea obviously has another flaw. If you have automatically generated 50 scaled datasets and your ETsource looks like...

````
etsource/datasets
..
├── nl
├── nl_alkmaar
├── nl_amsterdam
├── nl_groningen
├── ... (another 46 local datasets)
├── nl_zeeland
..
````

... and some `shares` file changes, would you need to alter them accross every scaled dataset? And than again. To go back to the first sentence of this issue. 

> [..] what people are currently editing for a local scenario are the present values in the graph

Isn't this already an issue on it's own? Why would you alter present values in the graph in the first place? If the graph is changed (for instance a converter is removed) you'd get an error, right? And wouldn't refinery currently complain when your graph is not properly calculated because a `_present / _both` value is not properly altered (relatively)? Or can you now make really weird edits to the graph behind refinery's back?

@antw Sorry, for the rain of questions hopefully somebody else is able to answer these questions aswell? 😆

**Comment by antw** [comment]
> However, I'm now sort of wondering how that share translates to a demand at households_new_houses_useful_demand_for_heating?

Shares are used when you want to split the demand of a node into two or more children (or parents). For example, here we know the demand of `B1`:

```
+--------+
| A1 (?) |  \
+--------+   \   +--------+
              -  | B1 (8) |
+--------+   /   +--------+
| A2 (?) |  /
+--------+
```

... but from this, Refinery has no way to figure out the demands of `A1` or `A2`. In the real graph, `A1` and `A2` might have their own children, and Refinery could figure out the demand from those. When that isn't possible, a "share" is needed to tell Refinery how to split the demand of `B1`:

```
+--------+                                  +--------+
| A1 (?) |  \ (parent_share: 0.25)          | A1 (2) |  \
+--------+   \   +--------+                 +--------+   \   +--------+
              -  | B1 (8) |           ->                  -  | B1 (8) |
+--------+   /   +--------+                 +--------+   /   +--------+
| A2 (?) |  / (parent_share: 0.75)          | A2 (6) |  /
+--------+                                  +--------+
```

--

> If you have automatically generated 50 scaled datasets and your ETsource looks like [...] and some shares file changes, would you need to alter them accross every scaled dataset?

My assumption is that the local dataset would need to store the demands, _and_ the shares and slot conversions ("efficiencies") from the sparse graph. Basically, if you stopped the Atlas+Refinery process [right here](https://github.com/quintel/atlas/blob/1a67953fc974177bad9eb194750d4677b4b99880/lib/atlas/runner.rb#L47) – immediately *before* Refinery is run – you could scale down all the demands and serialise the values in the graph (demands, shares, conversions) to an .ad file (or something else?) which represents the local dataset.

---

> Isn't this already an issue on it's own? Why would you alter present values in the graph in the first place? If the graph is changed (for instance a converter is removed) you'd get an error, right? 

No; in ETEngine if you try to select a node which doesn't exist, you get back an empty array (think of this like jQuery: `$('#does-not-exist') => []`).

> And wouldn't refinery currently complain when your graph is not properly calculated because a _present / _both value is not properly altered (relatively)?

Nope. Inputs (present, both, and future) affect the ETEngine graph *not* Refinery. Remember this diagram from quintel/etsource#1181:

```
      Compile time /
<---- ahead-of-time ---->   <- Runtime ->

ETSource -----> Atlas -----> ETEngine
                  ^     |
                  |     |
            Refinery <--'
```

Inputs happen in the ETEngine part. Atlas+Refinery *are not* re-run when using "present", or "both" inputs (Refinery is too slow to perform in runtime, and there are historic and data-related reasons why we have separate Atlas+Refinery and ETEngine graphs and calculations. However I don't think that's relevant for now.)

**Comment by grdw** [comment]
> [..] you could scale down all the demands and serialise the values in the graph (demands, shares, conversions) to an .ad file (or something else?) which represents the local dataset.

Ok. I'm having an idea. We would change this interface:

![screen shot 2016-11-18 at 11 09 45](https://cloud.githubusercontent.com/assets/2676542/20426475/891120b2-ad7f-11e6-92dc-157dac60f64f.png)

and either let the user choose between preset local datasets or create a new one based on the number of residences (which would be the same interface we're currently looking at + an extra text field for the name of that scaled local dataset). This scaling value would be passed on towards the code [here](https://github.com/quintel/atlas/blob/1a67953fc974177bad9eb194750d4677b4b99880/lib/atlas/runner.rb#L47) together with another attribute the likes of `name_of_local_dataset`. There it will scale down the values relatively the first time and output that to a file called `name_of_local_dataset.ad`. This file will live in ETSource and will be one of the local datasets that a user can choose from inside of ETModel. 

If somebody wants to change that local dataset a user might be able to that inside of ETSource. This will obviously change all the scenarios that make use of that local dataset.

When somebody chooses a preset local dataset in the scaling interface, the values from that file will be used to overwrite the node's input, output etc.

The table `scenario_scalings` will get another optional column called 'local_dataset' which might be `nl_groningen`, `nl_amsterdam` whatever. 

Something like this might do the trick 😅

**Comment by grdw** [comment]
I expanded the idea above a little bit better [here](https://github.com/quintel/internal/blob/local-datasets/planning/projects/local-datasets/README.md#idea-6-hooking-into-atlass-data-runner).

**Comment by dennisschoenmakers** [comment]
> name of that scaled local dataset). This scaling value would be passed on towards the code [here](https://github.com/quintel/atlas/blob/1a67953fc974177bad9eb194750d4677b4b99880/lib/atlas/runner.rb#L47)

The link refers to a line only containing `end`. Probably you meant another line?

**Comment by grdw** [comment]
We still have another question about:

> but from this, Refinery has no way to figure out the demands of A1 or A2. In the real graph, A1 and A2 might have their own children, and Refinery could figure out the demand from those. When that isn't possible, a "share" is needed to tell Refinery how to split the demand of B1:

Through a question @ploh asked. In ETModel you have a scenario which uses two versions of the graph. The present and the future. When dragging a slider you update the future. 

Let's say the situation for the future is like this (in the first example):

```
+--------+
| A1 (2) |  \
+--------+   \   +--------+
              -  | B1 (3) |
+--------+   /   +--------+  \
| A2 (1) |  /                 \
+--------+                     \   +--------+
                                -  | C1 (7) |
+--------+                     /   +--------+
| A3 (1) |  \                 /
+--------+   \   +--------+  /
              -  | B2 (4) |
+--------+   /   +--------+
| A4 (3) |  /
+--------+
```

I drag the slider at B1 resulting in: 

```
+--------+
| A1 (2) |  \
+--------+   \   +--------+
              -  | B1 (5) |
+--------+   /   +--------+  \
| A2 (1) |  /                 \
+--------+                     \   +--------+
                                -  | C1 (7) |
+--------+                     /   +--------+
| A3 (1) |  \                 /
+--------+   \   +--------+  /
              -  | B2 (4) |
+--------+   /   +--------+
| A4 (3) |  /
+--------+
```

How will `A1, A2, C1` be updated? Because this would be exactly the same problem. Unless you are ofcourse unable to update demands and/or shares through sliders in ETModel. 🤔
