### ISSUE TITLE
Technical questions about ETEngine and it's relation with ETSource

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#887]
I am trying to understand how [this](https://github.com/quintel/etengine/blob/master/app/models/gql/gql.rb#L98) works. 

I understand that a dataset is of type `Qernel::Dataset`. That contains the graph. But it's in a bit of a weird format:

````ruby
# If I show the keys for example, I see:
puts @dataset.data[:graph].keys

=> [2938288198,
 1455993528,
 272886772,
 2810745213,
 3067941370,
 1292476556,
 2091677784,
 62505781,
 2167327955,
 3643662458,
 2724930297,
 968679098,
 176352159,
 1495910632,
...
````

But what are those keys, links to nodes? And where do these numbers come from? I'm trying to overwrite the graph ofcourse with the graph we generated in the Atlas local dataset scaling step. Ofcourse this needs some tweaking but the absolute fundamental is, actually loading it in.

**Comment by antw** [comment]
Keys are converted to numerics by [Hashpipe](https://github.com/quintel/etengine/blob/master/app/models/hashpipe.rb). I guess the motivation was that looking up entries (which happens *a lot* in ETEngine) with a numeric key has better performance than a string.

The Qernel classes know what their numeric key is: [Converter](https://github.com/quintel/etengine/blob/48419962a8620114718e7b0eb703c72d28d6c7b9/app/models/qernel/link.rb#L63), [Link](https://github.com/quintel/etengine/blob/48419962a8620114718e7b0eb703c72d28d6c7b9/app/models/qernel/link.rb#L63), [Slot](https://github.com/quintel/etengine/blob/48419962a8620114718e7b0eb703c72d28d6c7b9/app/models/qernel/slot.rb#L64).

**Comment by antw** [comment]
FWIW: The conversion from string keys to numerics happens in [Etsource::Dataset::Import](https://github.com/quintel/etengine/blob/90ef9bc7e9ff45798b3ecd93e77bd73ffe4ef9d5/app/models/etsource/dataset/import.rb). I'm not too sure why you would need to worry about the numeric keys if you import the dataset there?

**Comment by grdw** [comment]
> I'm not too sure why you would need to worry about the numeric keys if you import the dataset there?

Well , I was just probing around the code and trying to see if I could make something of it. I'm now looking at the same file though. Thanks. I'm not sure where I'm after. But I'm trying to understand how the graph is currently imported but I guess that happens in there.

**Comment by antw** [comment]
>  I'm trying to understand how the graph is currently imported but I guess that happens in there.

Yep! All the code for importing from ETSource [is in the Etsource module](https://github.com/quintel/etengine/tree/master/app/models/etsource).
