### ISSUE TITLE
Loading a graph from a yaml file

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#889]
This friday I was busy trying to import the graph from a YAML file as is visible [here](https://github.com/quintel/atlas/pull/64/files) (this is till work in progress). However, I'm having some issues loading that graph into ETEngine. I tried to do it very simple (and a bit hacky) in the `calculate!` step of the `AtlasLoader`: 

````ruby
dataset = Atlas::Dataset.find(dataset_key)
graph   = dataset.try(:graph) || Atlas::GraphBuilder.build
runner  = Atlas::Runner.new(dataset, graph)
````

However this produced some very weird unpredictable errors. Could you give me some advice or some hints at how this would incorporate with ETEngine?

**Comment by antw** [comment]
> However this produced some very weird unpredictable errors.

Can you be more specific about what errors you received?

**Comment by grdw** [comment]
Yes I will be. But first I have a different error which prvents me from showing the actual error 😅 .. which is the one I posted in the local_datasets slack group

**Comment by antw** [comment]
> I tried to do it very simple (and a bit hacky) in the calculate! step of the AtlasLoader:

I wonder if the responsibility for this could be delegated to Atlas, so that ETEngine doesn't have to know that there's a difference between "full" and "derived"? (except for the area.json response)

For full datasets, [`Atlas::Runner@calculate_rubel_attributes!` maps values from CSV files onto the graph](https://github.com/quintel/atlas/blob/master/lib/atlas/runner.rb#L42). For derived datasets, there are no CSV files and these mapped/computed values are already stored in the YAML. Would something like this work?

```ruby
def refinery_graph
  @refinery ||= begin
    if @dataset.derived?
      # Derived dataset; take the pre-computed values from the YAML.
      map_values_from_yaml!(@dataset, graph)
    else
      # Full-size dataset; do the normal thing.
      calculate_rubel_attributes!(graph)
    end

    catalysts = [
      Refinery::Catalyst::FromTurbine,
      ZeroDisabledSectors.with_dataset(dataset),
      SetSlotSharesFromEfficiency.with_queryable(method(:query))
    ]

    # ...
  end
end
```

... then the rest of the process – the calculation of the graph, the loading in ETEngine – can be completely unchanged.

**Comment by grdw** [comment]
````
 2263 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/multibyte/chars.rb
 2264 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/schema_migration.rb
 2265 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/result.rb
 2266 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/associations/preloader.rb
 2267 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/message_encryptor.rb
 2268 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/actionview-4.1.5/lib/action_view/renderer/renderer.rb
 2269 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/actionview-4.1.5/lib/action_view/flows.rb
 2270 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/actionview-4.1.5/lib/action_view/renderer/abstract_renderer.rb
 2271 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/actionview-4.1.5/lib/action_view/renderer/template_renderer.rb
 2272 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/actionview-4.1.5/lib/action_view/template/error.rb
 2273 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/multipart/parser.rb
 2274 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/coders/yaml_column.rb
 2275 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/associations/builder/has_one.rb
 2276 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activemodel-4.1.5/lib/active_model/errors.rb
 2277 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/associations/association.rb
 2278 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/associations/singular_association.rb
 2279 /Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/associations/has_one_association.rb
 2280 /Users/gerard/Projects/etengine/app/models/gql/gql_error.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

[1]    11471 abort      rails s -p 4000
````

This is the bottom of the stack.

**Comment by grdw** [comment]
So what happens is that `rails` just quits, but I'm not sure why.

**Comment by antw** [comment]
I can take a look; how can I reproduce this myself? Are the branches and ETSource data on GitHub?

**Comment by grdw** [comment]
I investigated some more:

The first line in the stacktrace that causes the whole crash is:

`app/controllers/api/v3/scenarios_controller.rb:162:in `new'`

Which trickles down to the performing to the `perform_gqueries!` method in the `ScenarioUpdatePresenter` which is now causing the 'boom'.  :thinking:

**Comment by grdw** [comment]
> I can take a look; how can I reproduce this myself?

To reproduce:

````
<project>(<branch>)
-
etmodel (local-datasets)
etengine (local-datasets-loading-graph-yml)
etsource (local-datasets)
atlas (local-datasets-import-graph)

Note: etsource and etengine both use the local version of atlas.
````

I'm guessing that that's the setup.

**Comment by grdw** [comment]
> I wonder if the responsibility for this could be delegated to Atlas, so that ETEngine doesn't have to know that there's a difference between "full" and "derived"? (except for the area.json response)

>  For derived datasets, there are no CSV files and these mapped/computed values are already stored in the YAML. Would something like this work?

I missed a comment but this sounds doable. 👍

**Comment by antw** [comment]
> This is the bottom of the stack.
> So what happens is that rails just quits, but I'm not sure why.

It looks like Refinery [gets caught in an infinite loop](https://github.com/quintel/refinery/blob/8cc81e91f2a7c7546f6c227208899eda8921a6e9/lib/refinery/slot.rb#L94) trying to figure out the share of a slot. Since the full-size datasets are fine, I *guess* that some part of the graph isn't set up correctly by GraphToYaml, but I'm not sure what.

I think perhaps it's worth trying [my suggestion](https://github.com/quintel/etengine/issues/889#issuecomment-267958739) (where you should be able to be sure that the graph structure is correct), and if the problem persists I can take another look to see if something is missing from the YAML data.

**Comment by grdw** [comment]
Duplicate issue of https://github.com/quintel/atlas/issues/69
