### ISSUE TITLE
Derived datasets: Fix scaling of input ranges

### ISSUE THREAD

**Issue by ploh** [quintel/etengine#896]
In some cases the input ranges are not adjusted for the smaller values, e.g.:

![image](https://cloud.githubusercontent.com/assets/768025/21855908/57e8512e-d820-11e6-84a6-322980e26d38.png)

In this example the range should be [relative to the current number](https://github.com/quintel/etsource/blob/9e497c279596ab1f2157180b675e6e0759fdb95b/inputs/demand/households/households_misc/households_number_of_old_houses.ad#L55-L57)

I do not really have an idea yet, why this is or how to fix it. I only know that for the etengine scenario scaling there is some code to adjust the input ranges as well. Maybe we should make an effort to auto-adjust the inputs (including the `step_value`) better to the current values!? @antw @ChaelKruip

**Comment by grdw** [comment]
I think that this is something which I could manage to do. Considering this a rather high priority problem. I already know in which bits of the code this occurs and how this works therefor I assigned myself to this issue.
