### ISSUE TITLE
Derived datasets: Setup automated integration tests

### ISSUE THREAD

**Issue by ploh** [quintel/etengine#897]
To check the correctness of the creation, scaling and loading of a derived dataset, create a `rake test:derived_datasets` task that does the following:
1. Execute `rake scale` in the etsource directory
1. Prepare a gql runtime each for the new derived dataset and its base dataset (similar to how `rake gql:check:gqueries` does it)
1. Run all gqueries on both gql runtimes (similar to how the [`checks_controller`](https://beta-engine.energytransitionmodel.com/data/latest/checks/gquery_results) does it)
1. Compare the outcomes and report errors, i.e. all the gqueries with a relative output unit, e.g. %, must have identical result and the ones with a scalable output unit, e.g. MJ, must be scaled correctly.
1. Clean up in the etsource directory

This should then be set up on some CI server.

**Comment by ploh** [comment]
@antw @grdw @ChaelKruip Do you think that this is a good test setup for the core derived datasets components?

**Comment by ChaelKruip** [comment]
I think that we should consider this a nice-to-have for now. The estimated time for the deliverables in https://github.com/quintel/atlas/issues/78 (far) exceeds the time we can realistically spend on this project.

**Comment by grdw** [comment]
There's actually a 'nice to have' idea for this for ETLocal. Closing this issue.
