### ISSUE TITLE
Derived datasets: How to deal with typical_input_capacity, electricity_output_capacity?

### ISSUE THREAD

**Issue by ploh** [quintel/etengine#901]
In the [ETE scenario scaling](https://github.com/quintel/etengine/blob/74cb7289d849b411b815a588f38a63b35e28d659/app/models/scenario_scaling.rb#L138) the values of node attributes `typical_input_capacity` and `electricity_output_capacity` are never scaled - which seems to be [right in most cases](https://github.com/quintel/atlas/pull/73#issuecomment-270854806), except for the nodes [`energy_export_electricity`](https://github.com/quintel/etsource/blob/749c8d04d209d1a9c16e992c1c5e8abb86c5dcbe/nodes/energy/energy_export_electricity.ad#L16), [`energy_import_electricity`](https://github.com/quintel/etsource/blob/749c8d04d209d1a9c16e992c1c5e8abb86c5dcbe/nodes/energy/energy_import_electricity.ad#L14) and [`energy_interconnector_imported_electricity`](https://github.com/quintel/etsource/blob/37854341368530bd9afb6990c805902b36774b9e/nodes/energy/energy_interconnector_imported_electricity.converter.ad#L17).

During the [creation of a derived dataset](https://github.com/quintel/atlas/blob/c33304849e7f0aa3c3365532775a4cab47e62b42/lib/atlas/scaler/graph_scaler.rb#L9-L10) they are, however, scaled - for exactly the above 3 nodes, for which the attributes are set with the gquery `AREA(interconnector_capacity)`.

This leads to differences in the graphs / gquery results produced for a "traditional" scaled scenario and a scenario based on a scaled derived dataset.

Possible solutions:
1. Deactivate the scaling of the 2 attributes during the creation of a derived dataset.
Pro: Very easy to implement.
Con: Erroneous outcome from old scaling continues with new scaling.

1. Repair the old scenario scaling, so that the 2 attributes are scaled, but only for the nodes where they are set dynamically from the `interconnector_capacity`.
Pro: Everything correct.
Cons: a) I have no idea how to find out in `ScenarioScaling#scale_graph_dataset!` for a node's attribute whether it was dynamically set.
b) The criterion "attribute is set dynamically" might not always be correct for determining whether the attribute needs to be scaled for this node.

**Comment by ploh** [comment]
cc @grdw

**Comment by ChaelKruip** [comment]
For me this is of lesser priority either way (so option 1 is acceptable). The reasons are that
* interconnectors are not that realistic/meaningful for scaled scenarios anyway
* the user can decrease the interconnector with the sliders after scaling if needed

**Comment by ploh** [comment]
> * interconnectors are not that realistic/meaningful for scaled scenarios anyway

It does, however, seem to influence other gqueries as well.

> * the user can decrease the interconnector with the sliders after scaling if needed

:+1:

**Comment by ploh** [comment]
Relates to #80 - although solving that is probably _not_ gonna solve this automatically.

**Comment by ChaelKruip** [comment]
> It does, however, seem to influence other gqueries as well.

Which ones? This might tell me if it's important or not.

**Comment by ploh** [comment]
> > It does, however, seem to influence other gqueries as well.

> Which ones? This might tell me if it's important or not.

https://gist.github.com/ploh/61da97c13fb12559724107eb32095b6e

This is from trial-migrating scenario 530759 (GEA QI (voor)Beeld 2050 V6).
It shows 74 GQueries having different results for the scaled scenario and the scenario based on a newly created derived dataset.

All of these differences disappear when I disable scaling the dynamically-set node attributes  `typical_input_capacity` and `electricity_output_capacity` in Atlas.

**Comment by ChaelKruip** [comment]
> All of these differences disappear when I disable scaling the dynamically-set node attributes typical_input_capacity and electricity_output_capacity in Atlas.

I think we should not scale the interconnector capacity for now. Make sure to note this in the documentation though!

**Comment by ploh** [comment]
> > All of these differences disappear when I disable scaling the dynamically-set node attributes typical_input_capacity and electricity_output_capacity in Atlas.

> I think we should not scale the interconnector capacity for now. Make sure to note this in the documentation though!

@ChaelKruip I would suggest to re-enable scaling of the interconnector capacity in `Atlas::Scaler`, since it gives the more correct solution. The price is some inconsistency with ETE scaled scenarios, but that does not seem to bad a problem anymore: Only Paddepoel is proposed for migration now, and even there it is probably ok if the outcome is a little different from what it is now - especially if it becomes better.

**Comment by ChaelKruip** [comment]
> All of these differences disappear when I disable scaling the dynamically-set node attributes typical_input_capacity and electricity_output_capacity in Atlas.

> @ChaelKruip I would suggest to re-enable scaling of the interconnector capacity in Atlas::Scaler, since it gives the more correct solution. 

I'm confused now... Did your earlier comment say that *disabling* the scaling of interconnector capacity solved the differences?

**Comment by ploh** [comment]
> > > All of these differences disappear when I disable scaling the dynamically-set node attributes typical_input_capacity and electricity_output_capacity in Atlas.

> > @ChaelKruip I would suggest to re-enable scaling of the interconnector capacity in Atlas::Scaler, since it gives the more correct solution. 

> I'm confused now... Did your earlier comment say that *disabling* the scaling of interconnector capacity solved the differences?

Yes, that is correct. But I think we should rather aim for correctness of the new system than for zero differences against the old system. And in this case the old system behaves incorrect.

**Comment by michieldenhaan** [comment]
Closing, scaling option has been removed.
