### ISSUE TITLE
Is the expected demand check valid for local datasets?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#912]
![item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0](https://cloud.githubusercontent.com/assets/1303760/23015783/62f6057c-f434-11e6-8013-c26a9306bee6.png)

**Comment by antw** [comment]
The `expected_demand` value will not account for changes made by initializer inputs. A derived dataset with no initializer inputs passes the checks:

<img width="914" alt="screen shot 2017-02-16 at 15 37 30" src="https://cloud.githubusercontent.com/assets/4383/23027985/ef5df7ee-f45d-11e6-858f-7a5ef966134d.png">

I don't think there's any way to remedy this; this page provides a sanity check that Refinery and ETEngine are in agreement, and that cannot be the case when initializer inputs are involved. If you think this might cause confusion, we could add a message to this page when viewing values for a derived dataset.

**Comment by ChaelKruip** [comment]
> If you think this might cause confusion, we could add a message to this page when viewing values for a derived dataset.

I think nobody ever looks at that page but me 😆 

Thanks for clearing this up @antw!
