### ISSUE TITLE
Scaled scenario's population slider doesn't scale properly when loaded from /scenarios/:scenario_id 

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#913]
If you load a scenario with "Open this scenario" the scaling factor is not used for the population slider (and probably others):

<img width="707" alt="screen shot 2017-02-17 at 12 41 38" src="https://cloud.githubusercontent.com/assets/2676542/23064128/7db1fa4e-f50e-11e6-96c9-e80e361c4b01.png">

<img width="451" alt="screen shot 2017-02-17 at 12 42 20" src="https://cloud.githubusercontent.com/assets/2676542/23064139/8d23741c-f50e-11e6-80c0-47af8b9bf904.png">

However if you start a scenaro directly from the menu without saving, all is fine.

I can remember this being an issue 🤔 and that we've (@antw and I managed to solve it). However it's broken now.

**Comment by DorinevanderVlies** [comment]
Starting the local dataset and adjusting sliders is no problem.
The "mln" occurs when the scenario is saved (in the interface) and opened again

**Comment by grdw** [comment]
@DorinevanderVlies yes, exactly. I managed to fix it locally fairly quick though 😅 

There's a pull request up on etmodel.

**Comment by DorinevanderVlies** [comment]
> I managed to fix it locally fairly quick though 😅

Nice
