### ISSUE TITLE
Scaled derived regions have incorrect change in CO2, bio-footprint

### ISSUE THREAD

**Issue by antw** [quintel/etengine#918]
For example:

#### Drenthe, full-size:

![drenth-full](https://cloud.githubusercontent.com/assets/4383/25231012/1217b2b0-25ce-11e7-99a2-9f20ebd26121.png)

#### Drenthe, 1000 residences (0.47% original size):

![drenthe-scaled](https://cloud.githubusercontent.com/assets/4383/25231025/1de14764-25ce-11e7-8b05-e656fffd5597.png)

#### Drenthe, 7,000,000 residences (~3000% original size):

![drenthe-scaled2](https://cloud.githubusercontent.com/assets/4383/25231198/dff3dbbe-25ce-11e7-99e8-ff3864354952.png)

"Normal" regions (non-derived) do not appear to be affected.

---

Including @ChaelKruip.

**Comment by ChaelKruip** [comment]
Could this be because the reference value (1990) is not scaled properly?

**Comment by antw** [comment]
> Could this be because the reference value (1990) is not scaled properly?

I think it goes beyond that. Looking at the bio-footprint query, there's a calculation of the [area footprint](https://github.com/quintel/etsource/blob/129c4526011d9ede4a99e4559d96cdc3c9cc487e/gqueries/general/area/bio_footprint.gql#L1) which looks at the [demand of converters in the "bio_footprint_calculation" group](https://github.com/quintel/etengine/blob/8a32f96a02a494cf10259c499aabdcc144fdbfdd/app/models/qernel/graph_api.rb#L58). I ran this query:

```ruby
SUM(V(GROUP(bio_footprint_calculation), demand))
```

In a full-size Drenthe scenario, their demand is `	
3,981,639,219` (3.9B). In a scenario scaled to 1000 households with all sectors enabled, their demand is `4,873,200,966` (4.8B)!

Here are the CO2 emissions compared. It looks like the 1990 figure is scaled correctly; but the actual demands are far too high:

| Full-size | Scaled to 1000 households |
| --- | --- |
| ![co2-dr-full](https://cloud.githubusercontent.com/assets/4383/25231994/c985c498-25d1-11e7-91ea-0e1251ba2fa7.png) |  ![co2-dr-scaled](https://cloud.githubusercontent.com/assets/4383/25232000/d0d27c00-25d1-11e7-8f59-794e0738e6c9.png) |

Strangely, industry CO2 does seem to be scaled, while everything else isn't.

| Gquery | Full-size | Scaled | Change |
| :---: | ---: | ---: | ---: |
| primary_co2_of_agriculture | 0.112 | 0.112 | — |
| primary_co2_of_buildings | 0.297 | 0.358 | 120% |
| primary_co2_of_energy | 0.049 | 0.267 | 544% |
| primary_co2_of_households | 0.615 | 0.674 | 109% |
| primary_co2_of_industry | 0.814 | 0.005 | 0.6% |
| primary_co2_of_other | 0 | 0 | — |
| primary_co2_of_transport | 1.172 | 1.174 | 100% |

**Comment by antw** [comment]
I think this problem can be summarised more simply as:

| Full-size | Scaled to 0.47% original |
| --- | --- |
| ![screen shot 2017-04-20 at 14 19 53](https://cloud.githubusercontent.com/assets/4383/25232790/8bc59a68-25d4-11e7-9961-181ee3d76f49.png) | ![screen shot 2017-04-20 at 14 20 52](https://cloud.githubusercontent.com/assets/4383/25232800/935211a8-25d4-11e7-9513-3d8b0f3c7646.png) |

**Comment by grdw** [comment]
I did a little debugging myself and found that (for instance):

This:
```
V(buildings_final_demand_steam_hot_water, primary_demand)
```

Returned the same value for scaled (to 1000 households) - and unscaled Drenthe. This would almost seem like the demands from the graph.yml remain unscaled when scaling for derived datasets 🤔

**Comment by grdw** [comment]
I went a little further - tracking down the high increase percentage of Co2 emissions:

Query of : `dashboard_reduction_of_co2_emissions_versus_1990.gql`:

```
SUM(-1,DIVIDE(Q(total_co2_emissions), AREA(co2_emission_1990_billions)))
```

This value: `AREA(co2_emission_1990_billions)`, is actually scaled 👍 However the `Q(total_co2_emissions)` returns almost similar results for unscaled and scaled scenarios resulting in the high percentage. When looking further to the query 

```
Q(total_co2_emissions)
- Scaled:  2,588,430,802.740026
- Unscaled: 3,659,502,132.211776
```

Content of `total_co2_emissions.gql`:

```
Content:
- query =
    SUM(
     Q(co2_emissions_of_final_demand_excluding_imported_electricity) [1],
     Q(co2_emissions_of_imported_electricity)
    )
```

The imported electricity and the final demand electricity are almost equal for unscaled vs scaled. 

```
Q(co2_emissions_of_final_demand_excluding_imported_electricity) [1]
- Scaled: 2,241,368,372.1673512
- Unscaled: 2,951,903,275.2326574
```

Query for `co2_emissions_of_final_demand_excluding_imported_electricity` [1]:

```
V(G(final_demand_group),primary_co2_emission).sum
```

Right now my guess is that these `primary_co2_emission` are all somewhat equal between scaled and unscaled scenarios. Only I don't know why, do you have an idea @ChaelKruip ?

**Comment by grdw** [comment]
I created two lists with all `primary_co2_emissions` for every carrier in the `final_demand_group`. This is the difference between the two lists(red = scaled, green = unscaled):

```diff
1,3c1,3
< "agriculture_final_demand_crude_oil------------------------>0.0",
< "agriculture_final_demand_network_gas---------------------->0.0",
< "agriculture_final_demand_steam_hot_water------------------>0.0",
---
> "agriculture_final_demand_crude_oil------------------------>4000203.92156862",
> "agriculture_final_demand_network_gas---------------------->863304328.4315952",
> "agriculture_final_demand_steam_hot_water------------------>923332618.4282885",
5c5
< "agriculture_final_demand_electricity---------------------->0.0",
---
> "agriculture_final_demand_electricity---------------------->901209177.3532319",
8,9c8,9
< "buildings_final_demand_steam_hot_water-------------------->127331550.01412052",
< "buildings_final_demand_network_gas------------------------>4232027454.761348",
---
> "buildings_final_demand_steam_hot_water-------------------->127370921.93859546",
> "buildings_final_demand_network_gas------------------------>4233336031.1927686",
12,13c12,13
< "buildings_final_demand_electricity------------------------>4939613928.948516",
< "energy_power_sector_own_use_electricity------------------->34423.222760211705",
---
> "buildings_final_demand_electricity------------------------>5053434723.208313",
> "energy_power_sector_own_use_electricity------------------->755219493.1644033",
17,18c17,18
< "households_final_demand_network_gas----------------------->10368609244.477703",
< "households_final_demand_electricity----------------------->4509533036.133386",
---
> "households_final_demand_network_gas----------------------->10371815300.636122",
> "households_final_demand_electricity----------------------->4502724103.637426",
28,30c28,30
< "industry_final_demand_coal_non_energetic------------------>0.0",
< "industry_final_demand_for_other_crude_oil_non_energetic--->0.0",
< "industry_final_demand_network_gas_non_energetic----------->0.0",
---
> "industry_final_demand_coal_non_energetic------------------>93077329.81692371",
> "industry_final_demand_for_other_crude_oil_non_energetic--->169654507.61779723",
> "industry_final_demand_network_gas_non_energetic----------->627386828.1445926",
32,37c32,37
< "industry_final_demand_coal-------------------------------->0.0",
< "industry_final_demand_crude_oil--------------------------->0.0",
< "industry_final_demand_electricity------------------------->0.0",
< "industry_final_demand_network_gas------------------------->0.0",
< "industry_final_demand_steam_hot_water--------------------->0.0",
< "industry_final_demand_wood_pellets------------------------>0.0",
---
> "industry_final_demand_coal-------------------------------->866100601.9998047",
> "industry_final_demand_crude_oil--------------------------->917289516.1674168",
> "industry_final_demand_electricity------------------------->7334176755.546616",
> "industry_final_demand_network_gas------------------------->5847890196.59511",
> "industry_final_demand_steam_hot_water--------------------->4625665244.58039",
> "industry_final_demand_wood_pellets------------------------>70019997.40868413",
45c45
< "energy_heat_network_unused_steam_hot_water---------------->3339392701.350891",
---
> "energy_heat_network_unused_steam_hot_water---------------->0.0",
48c48
< "transport_final_demand_crude_oil_non_energetic------------>2424.4163678241894",
---
> "transport_final_demand_crude_oil_non_energetic------------>51373867.71746814",
52c52
< "transport_final_demand_compressed_network_gas------------->23108765.197682563",
---
> "transport_final_demand_compressed_network_gas------------->23189786.667399254",
55c55
< "transport_final_demand_electricity------------------------>164685003.23942816",
---
> "transport_final_demand_electricity------------------------>169374430.72779316",
```

---

Ignoring all the industry and agriculture (since I left them out) it leaves me with this list: 

```diff
8,9c8,9
< "buildings_final_demand_steam_hot_water-------------------->127331550.01412052",
< "buildings_final_demand_network_gas------------------------>4232027454.761348",
---
> "buildings_final_demand_steam_hot_water-------------------->127370921.93859546",
> "buildings_final_demand_network_gas------------------------>4233336031.1927686",
12,13c12,13
< "buildings_final_demand_electricity------------------------>4939613928.948516",
< "energy_power_sector_own_use_electricity------------------->34423.222760211705",
---
> "buildings_final_demand_electricity------------------------>5053434723.208313",
> "energy_power_sector_own_use_electricity------------------->755219493.1644033",
17,18c17,18
< "households_final_demand_network_gas----------------------->10368609244.477703",
< "households_final_demand_electricity----------------------->4509533036.133386",
---
> "households_final_demand_network_gas----------------------->10371815300.636122",
> "households_final_demand_electricity----------------------->4502724103.637426",
45c45
< "energy_heat_network_unused_steam_hot_water---------------->3339392701.350891",
---
> "energy_heat_network_unused_steam_hot_water---------------->0.0",
48c48
< "transport_final_demand_crude_oil_non_energetic------------>2424.4163678241894",
---
> "transport_final_demand_crude_oil_non_energetic------------>51373867.71746814",
52c52
< "transport_final_demand_compressed_network_gas------------->23108765.197682563",
---
> "transport_final_demand_compressed_network_gas------------->23189786.667399254",
55c55
< "transport_final_demand_electricity------------------------>164685003.23942816",
---
> "transport_final_demand_electricity------------------------>169374430.72779316",
```

**Comment by grdw** [comment]
I think I've found the problem. The initializer inputs are performed after the scaling of the graph. Which means that you apply demands and units for the 'whole of Drenthe' to a scaled version of Drenthe. Which obviously makes no sense and causes the co2 to spike etc. I'll check how easy this is to fix.
