### ISSUE TITLE
Menu should get a sub-menu

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#922]
![screen shot 2017-05-18 at 15 52 14](https://cloud.githubusercontent.com/assets/2676542/26205438/03003ed0-3be2-11e7-849d-12941d48dbce.png)

Electricity, cooking, cooling, lightning, gas shoud live under Households.

**Comment by ChaelKruip** [comment]
Not sure what you mean by sub-menu. Would it be fair to say that we are looking for a way to make it clear to the user what the work-flow of this interface is?

In that case, perhaps it is worthwhile to zoom out a bit and consider other options to achieve that?

**Comment by grdw** [comment]
> Not sure what you mean by sub-menu. Would it be fair to say that we are looking for a way to make it clear to the user what the work-flow of this interface is?

Yes, but this is just a small issue detected by @BerendSmits. Not something major. We already discussed the bigger work-flow of the interface but would like to further discuss that monday.

**Comment by grdw** [comment]
Oops, wrong project.
