### ISSUE TITLE
Add UI to edit scenario user values

### ISSUE THREAD

**Issue by antw** [quintel/etengine#928]
I think we should add a UI to the ETEngine admin section allowing an authenticated user to edit the values of a scenario.

With the current system it's too easy to make mistakes such as:

* YAML syntax errors
* Failing to balance groups
* Specifying values already in the `balanced_values` column
* Exceeding the min/max values, making it impossible to correctly update the scenario through the ETM
* Possible accidental deletion of other data

---

Including @dennisschoenmakers and @ChaelKruip.

**Comment by grdw** [comment]
Very much in favor! 

> With the current system

The current system actually consists of two systems: 

1. Editing a scenario through [for example here](https://beta-engine.energytransitionmodel.com/data/latest/scenarios/695888/edit) (which is the 'somewhat' correct way 😅). 
2. Editing through Sequelpro (which gives me nightmares). I can't stress this enough: **editing scenarios (especially on beta or production environments) directly in Sequelpro is a really bad idea**. The reason why I'm telling this - is that when things get destroyed by accident or somebody mistypes a comma, or a number - is that debugging becomes really really hard (timestamps don't update, there are no logs, etc.). Also I think the people who use this to edit their scenario aren't aware that there is option number 1.

**Comment by ChaelKruip** [comment]
> Editing a scenario through for example here 

I was not aware that we had this option! 😬
