### ISSUE TITLE
Users should be able to generate a dump of values of the graph

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#929]
We get more third parties which need to extract data from the ETM which is not in the charts. 

We could provide CSV dumps of queries like
```
TXT_TABLE(G(final_demand_group), key, demand, primary_demand, primary_co2_emission)
```
and
```
TXT_TABLE(ALL(), key, demand, primary_demand, primary_co2_emission)
```
for both the present and future year. This will cover most data-requests IMO.

CC: @jorisberkhout @AlexanderWirtz

**Comment by antw** [comment]
So the choice is between [arbitrary code execution](https://en.wikipedia.org/wiki/Arbitrary_code_execution)† or making some CSV files available? 😆 

In the short-term I think we should support exporting those CSVs which would be useful. Once there are too many such files, we could switch to a more fully-featured export whereby you enter your e-mail address and we e-mail a link to a ZIP file containing everything.

---

† In all seriousness, it's not *impossible* – [there are plenty](https://repl.it/) [of online REPLs where](http://tryruby.org/)  [you can execute code](https://play.golang.org) – it's just too much effort for something almost no-one will use (who's going to learn GQL just to export some data?).

* `$SAFE=4` hasn't existed in Ruby for four major versions ([it was dropped in 2.1](https://bugs.ruby-lang.org/issues/8468#note-18), we're now at 2.4).
* There's already plenty of libraries used in ETEngine which could provide possible attack vectors – we need to consider all of them and lock them down. We only have to forget one, for example `Scenario.destroy_all`. We'd have to audit every library we use for stuff like this.
* Future Ruby versions may introduce new features which we'd have to be very careful to lock down – which creates an inertia against upgrading.

Sorry, but a public GQL sandbox just isn't going to happen. 😞  If our visitors want something which is currently only possible with the sandbox, let's figure out how to expose that feature in a more user-friendly manner.

**Comment by ChaelKruip** [comment]
> In the short-term I think we should support exporting those CSVs which would be useful.

I think we should go for that than! 

What about a link in the options menu?
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://user-images.githubusercontent.com/1303760/28326256-907c7750-6be0-11e7-994b-50bdba8adee8.png)

**Comment by antw** [comment]
How about putting it in the (proposed) "Information" tab? See https://github.com/quintel/etmodel/issues/2432#issuecomment-314403771. The report section would feel less lonely.

**Comment by ChaelKruip** [comment]
> How about putting it in the (proposed) "Information" tab? See quintel/etmodel#2432 (comment). The report section would feel less lonely.

I like it! 👍

**Comment by AlexanderWirtz** [comment]
> How about putting it in the (proposed) "Information" tab? See quintel/etmodel#2432 (comment). The report section would feel less lonely.

Or... we could make this be part of the actual report: have a section that offers you and extensive download etc etc. Seems like it would fit there just fine.

**Comment by ChaelKruip** [comment]
> Seems like it would fit there just fine.

I kindly disagree. This would force users who want to download data from the ETM to create a scenario first. 
Moreover, it breaks with the current choice that data from the Merit Order is available from the normal front-end:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/1303760/28462762-0092f314-6e1d-11e7-9f86-19f22cc46a1b.png)

We could move these download links to the [suggested tab of @antw](https://github.com/quintel/etengine/issues/929#issuecomment-316425872) IMO

**Comment by ChaelKruip** [comment]
After talking to an interested client, they came up with the following wishes: 
* Energy data from useful demand (UD), to final demand (FD) to primary demand (PD)
* If possible, combine all data in one big table/matrix to be easily copied into Excel
* A separate table could give technical and financial specs of technologies
* A separate table could give carrier specs so the user can use the energy table to calculate CO2 etc.

The above suggests a format for the first 'energy table' which looks like this (using dummy values):


Sector | UD node | UD carrier | FD carrier | PD carrier | Useful Demand [MJ] | Final Demand [MJ] | Primary Demand [MJ]
-- | -- | -- | -- | -- | -- | -- | --
Sector 1 | Node 1 | useable_heat | biodiesel | greengas | 3.621170564 | 6.354093218 | 8.982722065
Sector 1 | Node 1 | useable_heat | biodiesel | biodiesel | 5.149438677 | 5.861593781 | 0.611755857
Sector 1 | Node 1 | useable_heat | biodiesel | bio_ethanol | 0.987967373 | 3.626385099 | 4.550201508
Sector 1 | Node 1 | useable_heat | biodiesel | bio_lng | 0.53588592 | 1.433192527 | 9.548751956
Sector 1 | Node 1 | useable_heat | biodiesel | bio_oil | 9.75227628 | 7.366879763 | 3.153366149
Sector 1 | Node 1 | useable_heat | biodiesel | torrified_biomass_pellets | 4.378710205 | 1.118834729 | 4.934073057
Sector 1 | Node 1 | useable_heat | biodiesel | wood_pellets | 1.239172386 | 2.04009141 | 0.147892455
Sector 1 | Node 1 | useable_heat | biodiesel | woody_biomass | 6.530097752 | 3.868151908 | 3.660865947
Sector 1 | Node 1 | useable_heat | biodiesel | corn | 8.295309452 | 0.728789176 | 6.358259062
Sector 1 | Node 1 | useable_heat | biodiesel | manure | 7.719098762 | 1.114840395 | 4.265399094
Sector 1 | Node 1 | useable_heat | biodiesel | wood | 1.550694281 | 9.351203349 | 0.964242997
Sector 1 | Node 1 | useable_heat | biodiesel | coal | 0.371213661 | 4.361017152 | 8.078828536
Sector 1 | Node 1 | useable_heat | biodiesel | lignite | 3.472612084 | 1.141553945 | 2.960435001
Sector 1 | Node 1 | useable_heat | biodiesel | coal_gas | 7.615541243 | 5.40625938 | 1.866073718
Sector 1 | Node 1 | useable_heat | biodiesel | cokes | 0.318667176 | 9.379162562 | 2.675761974
Sector 1 | Node 1 | useable_heat | biodiesel | electricity | 6.81182504 | 4.776983516 | 3.382532189
Sector 1 | Node 1 | useable_heat | biodiesel | ambient_heat | 7.808657078 | 7.652316855 | 8.306431676
Sector 1 | Node 1 | useable_heat | biodiesel | ambient_cold | 1.732797558 | 9.2294981 | 6.08499973
Sector 1 | Node 1 | useable_heat | biodiesel | wind | 3.295576809 | 3.098477836 | 4.914621964
Sector 1 | Node 1 | useable_heat | biodiesel | water | 3.219970624 | 3.737270839 | 3.593262449
Sector 1 | Node 1 | useable_heat | biodiesel | solar_radiation | 7.629733944 | 7.465557943 | 6.272390547
Sector 1 | Node 1 | useable_heat | biodiesel | solar_thermal | 3.167283818 | 5.070204012 | 9.133539297
Sector 1 | Node 1 | useable_heat | biodiesel | geothermal | 7.536811038 | 0.081884991 | 4.418943492
Sector 1 | Node 1 | useable_heat | biodiesel | imported_electricity | 0.181616812 | 3.710270017 | 7.606997672
Sector 1 | Node 1 | useable_heat | biodiesel | non_biogenic_waste | 1.931726774 | 2.459575148 | 3.621690017
Sector 1 | Node 1 | useable_heat | biodiesel | biogenic_waste | 6.477726088 | 4.800304632 | 8.087108519
Sector 1 | Node 1 | useable_heat | biodiesel | natural_gas | 2.005647178 | 7.207840183 | 5.059768074
Sector 1 | Node 1 | useable_heat | biodiesel | compressed_network_gas | 4.747783355 | 8.960277258 | 4.811027259
Sector 1 | Node 1 | useable_heat | biodiesel | lng | 6.469111699 | 9.055360098 | 1.488456375
Sector 1 | Node 1 | useable_heat | biodiesel | uranium_oxide | 3.870401375 | 0.684509164 | 1.914355404
Sector 1 | Node 1 | useable_heat | biodiesel | crude_oil | 4.171694327 | 0.462096205 | 1.036348923
Sector 1 | Node 1 | useable_heat | bio_ethanol | greengas | 2.704256489 | 6.187860076 | 2.175406694
Sector 1 | Node 1 | useable_heat | bio_ethanol | biodiesel | 5.685578388 | 4.380818554 | 1.303980456
Sector 1 | Node 1 | useable_heat | bio_ethanol | bio_ethanol | 5.790357324 | 6.494495945 | 8.780310898
Sector 1 | Node 1 | useable_heat | bio_ethanol | bio_lng | 6.833056161 | 5.25175385 | 8.311652182
Sector 1 | Node 1 | useable_heat | bio_ethanol | bio_oil | 4.863699247 | 0.5478027 | 7.063854847

...

@antw I know that it is possible to use `final_demand_of(:carrier)` and `primary_demand_of(:carrier)` on nodes. This would not give you the information on how much primary demand (per carrier) is due to a certain final demand (per carrier) though right?
In other words, they would like to know for the UD node `cooking in households` how much FD of `network_gas` and `electricity` there is used. Next, they would like to know how much of primary demand of `natural_gas`, `green_gas` and `hydrogen` is resulting from that `network_gas`. Similarly, they would like to know all primary demands resulting from the `electricity` used in the cooking UD node.

@jorisberkhout Do you think this is actually a useful thing for the power-user to have? I am particularly worried that the `useful_demand` group includes other uses than the `final_demand_group`. I have checked and the primary demand of UD is a (much) higher number than primary demand of FD. Also, UD does not include all own use in energy sector and industry etc.

**Comment by jorisberkhout** [comment]
> @jorisberkhout Do you think this is actually a useful thing for the power-user to have?

From talking to Berenschot and Gasunie I get the impression that this would be a very useful thing.

> I am particularly worried that the useful_demand group includes other uses than the final_demand_group. I have checked and the primary demand of UD is a (much) higher number than primary demand of FD. Also, UD does not include all own use in energy sector and industry etc.

Those worries are well-grounded and I have looked into them in great detail. First up, the extent of the issue.


| **Sector** | **Primary demand of useful demand group (MJ)** | **Primary demand of final demand group (MJ)** | **Difference (MJ)** |
|:-- | --:| --:| --:|
| buildings | 496,997,122,224.05 | 485,129,805,013.20 | 11,867,317,210.85 |
| industry | 3,817,025,705,636.46 | 1,551,282,335,346.08 | 2,265,743,370,290.37 |
| households | 561,016,106,739.61 | 544,256,062,990.46 | 16,760,043,749.16 |
| other | 1,662,030,000.00 | 1,662,030,000.00 | 0.00 |
| agriculture | 142,872,314,144.98 | 142,872,314,144.98 | 0.00 |
| energy |   | 138,342,657,086.19 | -138,342,657,086.19 |
| transport | 499,824,531,504.13 | 499,710,739,318.38 | 113,792,185.75 |
| **total**  | **5,519,397,810,249.24** | **3,363,255,943,899.29** | **2,156,141,866,349.95** |

Most of the difference is explained by the fact that `industry_useful_demand_for_chemical_refineries_crude_oil_non_energetic` is included in the useful demand group, but no counterpart is included in the final demand group. This results in a `2.27 EJ` difference. Therefore it does show of in the primary demand of useful demand, but not in the primary demand of final demand.

Let's discuss how to solve this, @ChaelKruip .

**Comment by jorisberkhout** [comment]
Interestingly I found more differences, which I will document here.

- `buildings_useful_demand_after_insulation_cooling` is not included in the useful demand group, but should be as its final demand counterparts are
- `buildings_useful_demand_for_space_heating_after_insulation` is not included in the useful demand group, but should be as its final demand counterparts are

**Comment by antw** [comment]
> This would not give you the information on how much primary demand (per carrier) is due to a certain final demand (per carrier) though right?

Sorry, I missed this question when it was posted. 😊

I think you're right to say it would not give you this information. To do this I expect we'd need recursive factor to not only return the final demand, but also the nodes from which the final demand was calculated. Then we'd have to compute the primary demand from those final demand nodes and weigh the result accordingly (i.e., if cooking is 1% of final demand, then "primary demand × 1%" = primary demand of *x* for cooking).

**Comment by jorisberkhout** [comment]
The issue with the UD of cooling and space heating in buildings is solved by the changes https://github.com/quintel/etsource/pull/1305.

**Comment by antw** [comment]
Since this was suggested, we've added many kinds of CSVs to ETEngine which allow users to download data about the graph. This isn't as flexible as allowing them to build their own CSVs with a query, but I still don't see any way to do that securely.

There always remains the option to allow QIs to add queries to ETSource which would be converted to a CSV, however many of the CSVs we have are, I think, too complex to be expressed as a gquery. I think I'll close this, and we can create a more specific issue in the future if the need is there.
