### ISSUE TITLE
Sign in troubles local ETEngine environment

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#932]
@karimelbana isn't able to sign in locally to his ETengine development environment. It's a bit odd. 

The behavior is as follows:

1. Create a user locally (for instance: `test@test.com` with password: `testtest`)
2. Sign in as that user
3. Click any page in ETSource
4. Get redirected to home page (with the message that you're already signed in) (from `Devise::SessionsController`).
5. 💢 

We've tried clearing the sessions, using incognito mode in the browser also doesn't work. What else could cause the redirect?

**Comment by antw** [comment]
Is `role_id` set to `1`?

```ruby
User.find_by_email('test@test.com')
  .update_attributes!(role: Role.find_by_name('admin'))
```

**Comment by jorisberkhout** [comment]
> Is role_id set to 1?

No, my bad. I created an account for Karim on Beta ETEngine, but forgot to set his role.

**Comment by jorisberkhout** [comment]
Could you fix this, @grdw ? I cannot change Karim's role from the ETEngine interface and I wouldn't let myself touch the database 😉

**Comment by grdw** [comment]
> Is role_id set to 1?

No 😄 and that was it! Thanks @antw!
