### ISSUE TITLE
Behaviour of P2H in paper sub-sector seems different from other sectors

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#933]
For Chemical, Refineries and Food, the maximum application of P2H results in about 98% of the heat demand being fulfilled with P2H. Example: Chemical has a total heat demand of 151.41 PJ and P2H can take care of about 149 PJ of that:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/1303760/28875892-8d9ed524-7797-11e7-87b6-64f9ab7a3dac.png)

For Paper, however, the maximum slider setting while resulting in the expected installed capacity and storage volume, only delivers about 50% (9 PJ) of the heat demand (17 PJ):
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/1303760/28876031-06187bea-7798-11e7-8724-62bce003b956.png)

**Comment by antw** [comment]
[Chemical](https://github.com/quintel/etsource/blob/068235c6ab93a6e6d139deef540692da8a225296/nodes/industry/industry_chemicals_other_flexibility_p2h_electricity.ad#L7), [refineries](https://github.com/quintel/etsource/blob/068235c6ab93a6e6d139deef540692da8a225296/nodes/industry/industry_chemicals_refineries_flexibility_p2h_electricity.ad#L7), and [food](https://github.com/quintel/etsource/blob/068235c6ab93a6e6d139deef540692da8a225296/nodes/industry/industry_other_food_flexibility_p2h_electricity.ad#L7) all define their demand sources to be a "something_**useable_heat**" node. Paper defines [a "something_**electricity**" as its demand source](https://github.com/quintel/etsource/blob/068235c6ab93a6e6d139deef540692da8a225296/nodes/industry/industry_other_paper_flexibility_p2h_electricity.ad#L7). Might this be the reason?

**Comment by ChaelKruip** [comment]
> Might this be the reason?

Well spotted @antw! That's it. Fixed with a49fd81a44b77d1fd86d2e925c1ae583280cd81b

**Comment by ChaelKruip** [comment]
One remaining question (low priority) I have is how it can be that the exact percentage of heat demand for the different sub sectors can actually differ when the technologies are dimensioned based on the total demand and their efficiencies are equal. 

In other words: If the excess events are sufficient to produce 98% of the heat demand in a big sector, why does it only deliver 87% in a smaller sector?

@DorinevanderVlies @antw do you know why this can be? Is there any decay modelled?
