### ISSUE TITLE
Ruby internship needs to be removed more thoroughly

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#939]
I removed the link a while ago but the page [https://quintel.com/jobs/dev_internship](https://quintel.com/jobs/dev_internship) can still be found through Google. Can we hide this page without throwing it away completely?

**Comment by grdw** [comment]
We can remove the actual page, so google doesn't pick it up anymore (and sees it as a 404) I guess. 👍 To clearify, if we want to retrieve it we can simply do a git revert.

**Comment by ChaelKruip** [comment]
I could swear I opened this in the quintel.com repo 😖

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/quintel.com/commit/948aef04bcbd0f4bd55b7f94ab3ae91cb6e12fd4
