### ISSUE TITLE
Nitpicking: new node positions of heat

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#942]
How about if we move the deficit nodes from here:

![screen shot 2017-08-30 at 16 11 46](https://user-images.githubusercontent.com/2676542/29876861-2cd57d70-8d9e-11e7-8ff2-397dda5a2715.png)

To here:
![screen shot 2017-08-30 at 16 12 40](https://user-images.githubusercontent.com/2676542/29876860-2c8393d4-8d9e-11e7-9007-31f60bccc595.png)

I'm not a big fan of the overlapping edges.

**Comment by ChaelKruip** [comment]
👍

**Comment by DorinevanderVlies** [comment]
I agree that it looks a lot better like that!
There is a lack of space below the water heater technologies. How about the change as shown below?

![image](https://user-images.githubusercontent.com/19907658/29881444-cb63f5aa-8daa-11e7-9f0a-b4ff45198eee.png)

![image](https://user-images.githubusercontent.com/19907658/29881407-bf1ab194-8daa-11e7-9211-026a8db0983c.png)

**Comment by grdw** [comment]
You can also move all the other nodes down a notch, but I guess that's a bit hard to do with the current interface. It would be great if you could select all nodes with a "square" selection tool (instead of Alt+Click) and drag them down some way. 

That position is fine by me though, as long as it is consistent with the water heater.

**Comment by DorinevanderVlies** [comment]
I agree that it would be nicer to move the other nodes down a notch.

> That position is fine by me though, as long as it is consistent with the water heater.
 
It is
