### ISSUE TITLE
Graph filters are broken

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#946]
![screen shot 2017-09-04 at 11 50 45](https://user-images.githubusercontent.com/2676542/30021339-556932be-9167-11e7-979d-1891f4e3364f.png)

Graph filters are broken. Clicking on any of the 'show' or 'hide' buttons result in:

![screen shot 2017-09-04 at 11 51 43](https://user-images.githubusercontent.com/2676542/30021372-74bf68d6-9167-11e7-8e60-6989316c09f0.png)

**Comment by antw** [comment]
Seems to be specific to Firefox. Chrome (v60) and Safari (10.1.2) are both okay.
