### ISSUE TITLE
Using 100% gas-part of HHP should be the same as using 100% combi boilers

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etengine#947]
If I set the COP-threshold to the max in a new scenario and HHP to 100% I get this for space heating:
![cursor_and_energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/1303760/30029715-9d65a0f2-918a-11e7-9a9f-c45731666836.png)

Using 100% combi-boilers instead reduces the gas demand:
![cursor_and_energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/1303760/30029745-beb66bba-918a-11e7-9018-0aebd7ac438b.png)

**Comment by ChaelKruip** [comment]
For hot water the situation is reversed!
* HHP: 67.95 PJ gas
* Combi boiler: 73.13 PJ gas

**Comment by antw** [comment]
Different output conversions.

* Hot water combi-boiler: 90% of energy is output as useable heat.
* Hot water HHP: 96.67% of energy is output as useable heat.

Combi boiler: 73.13 PJ × 90% = **65.82 PJ** useable heat output from the converter
HHP: 68.08 PJ × 96.67% = **65.81 PJ** useable heat output from the converter

This is also true on production:

**100% combi boilers**, combi-boiler flows:

| Producton | Beta |
| :---: | :---: |
| ![combi-production](https://user-images.githubusercontent.com/4383/30031457-75fa8dda-9189-11e7-83fa-085e7ab93193.png) | ![combi-beta](https://user-images.githubusercontent.com/4383/30031459-78b3e2ba-9189-11e7-9861-5b3a2b74c172.png) |

**100% HHPs**, HHP edge flows:

| Producton | Beta |
| :---: | :---: |
| ![hhp-production](https://user-images.githubusercontent.com/4383/30031633-385aa8c4-918a-11e7-9c9a-86e048019385.png) | ![hhp-beta](https://user-images.githubusercontent.com/4383/30031637-3ad152b0-918a-11e7-9ba5-c03fa8d35c9c.png) |

**Comment by ChaelKruip** [comment]
> Different output conversions.

Ah! I think I understand what goes wrong here (but not yet why)...

On Production, the 96.67% efficiency is for the *whole* HHP technology (electric heat pump plus combi-boiler part averaged over the year). On Beta, the HHP is modelled as two separate technologies (in Fever). The combi-boiler part should be exactly equal to the combi-boiler as a separate technology. Consequently, it should use 90% as efficiency.

Does that make sense @antw?

@DorinevanderVlies do you agree with my interpretation?

**Comment by DorinevanderVlies** [comment]
> Ah! I think I understand what goes wrong here (but not yet why)...

I am also not sure why... What confuses me is that the output useable heat is defined similarly for HHP and combi boilers:

HHP has:`- output.useable_heat.network_gas = 0.9`
Combi boiler has: `- output.useable_heat = 0.9`

> The combi-boiler part should be exactly equal to the combi-boiler as a separate technology. Consequently, it should use 90% as efficiency.

I agree that this is what should be happening

**Comment by antw** [comment]
> HHP has:- output.useable_heat.network_gas = 0.9

If I remember correctly, this feature is supported in Atlas+Refinery only. It is used to compute the shares for the `present` graph (and therefore the initial state of the `future` graph).

ETEngine never sees the original `output.useable_heat.network_gas` attribute; it only receives the final, computed `useable_heat` share given to it by Atlas. I appreciate that this is not at all clear by looking at the ".ad" file alone, and it's not obvious that ETE won't *dynamically* update the share based on the inputs.

---

... which is not to say this cannot be done, but ETE cannot do it *today*. It seems to me that with the HHP we're trying to do the work of two nodes with only one. 🤔

**Comment by ChaelKruip** [comment]
> It seems to me that with the HHP we're trying to do the work of two nodes with only one.

Nicely put! Indeed we are... and possibly we should change that at some point. 

> ... which is not to say this cannot be done, but ETE cannot do it today

What would it take for this to be done @antw?

**Comment by antw** [comment]
A temporary fix has been pushed to beta.

"Temporary" because it involves reading the raw attributes `output.useable_heat.electricity` from Atlas, which is a bit of a no-no in ETEngine. In the clean-up phase I'll try to improve this with a more generic solution which we could use elsewhere in the graph (i.e. not limited to only the HHP).

**100% space heating HHP, CoP cutoff = 6.0**

<img width="619" alt="screen shot 2017-09-05 at 11 51 52" src="https://user-images.githubusercontent.com/4383/30057922-ac045a30-9230-11e7-912e-11acdbc43c47.png">

**Comment by ChaelKruip** [comment]
😍 😍 😍
