### ISSUE TITLE
[Airbrake] [Production] Git::GitExecuteError: git log "--pretty=raw" "-1" "datasets/barendrecht"  2>&1:fatal: ambiguous argument 'datasets/barendrecht': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like t...

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#951]
**Airbrake error:** [#1536](https://quintel.airbrake.io/projects/32233/groups/2053572731447711536)
**Airbrake project:** ETE

**Error type:** `Git::GitExecuteError`
**Error message:** `` Git::GitExecuteError: git log "--pretty=raw" "-1" "datasets/barendrecht"  2>&1:fatal: ambiguous argument 'datasets/barendrecht': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]' ``
**Where:** `api/v3/inputs#index`
**Occurred at:** Oct 04, 2017 09:22:26 UTC
**First seen at:** Oct 04, 2017 09:22:26 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [https://engine.energytransitionmodel.com/api/v3/scenarios/337766/inputs.json?include_extras=false](https://engine.energytransitionmodel.com/api/v3/scenarios/337766/inputs.json?include_extras=false)
**File:** `[GEM_ROOT]/bundler/gems/ruby-git-de8e04d4e37a/lib/git/lib.rb`

**Backtrace:**
```
[GEM_ROOT]/bundler/gems/ruby-git-de8e04d4e37a/lib/git/lib.rb:704:in command
[GEM_ROOT]/bundler/gems/ruby-git-de8e04d4e37a/lib/git/lib.rb:676:in command_lines
[GEM_ROOT]/bundler/gems/ruby-git-de8e04d4e37a/lib/git/lib.rb:92:in full_log_commits
[GEM_ROOT]/bundler/gems/ruby-git-de8e04d4e37a/lib/git/log.rb:108:in run_log
```

**Comment by grdw** [comment]
Removed 'Barendrecht' scenarios from the databases (both staging and production). They live as backups on my Mac (if anybody needs them, talk to me).
