### ISSUE TITLE
[Airbrake] [Production] NoMethodError: undefined method `with_indifferent_access' for nil:NilClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#957]
**Airbrake error:** [#1738](https://quintel.airbrake.io/projects/32233/groups/2074630972600391738)
**Airbrake project:** ETE

**Error type:** `NoMethodError`
**Error message:** `` NoMethodError: undefined method `with_indifferent_access' for nil:NilClass ``
**Where:** `data/scenarios#create`
**Occurred at:** Nov 02, 2017 10:41:24 UTC
**First seen at:** Nov 02, 2017 10:41:24 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [https://engine.energytransitionmodel.com/data/latest/scenarios](https://engine.energytransitionmodel.com/data/latest/scenarios)
**File:** `[PROJECT_ROOT]/app/models/scenario/user_updates.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/scenario/user_updates.rb:82:in user_values_as_yaml=
[GEM_ROOT]/gems/activerecord-4.1.5/lib/active_record/attribute_assignment.rb:45:in public_send
[GEM_ROOT]/gems/activerecord-4.1.5/lib/active_record/attribute_assignment.rb:45:in _assign_attribute
[GEM_ROOT]/gems/activerecord-4.1.5/lib/active_record/attribute_assignment.rb:32:in block in assign_attributes
```

**Comment by grdw** [comment]
Closed due to https://github.com/quintel/etengine/issues/961#issuecomment-342754660
