### ISSUE TITLE
Add total_investment_over_lifetime_per(:converter) to data export

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etengine#959]
For one of our customers I would like to add the outcome of the following query to the datadump:
TXT_TABLE(V(G(heat_production),G(electricity_production)),   key, total_investment_over_lifetime_per(converter))

I think this can be done by adding `total_investment_over_lifetime_per(:converter)` to the data export production parameters. However, d787a88 does gives errors when I try to export.

@antw can you help me with this?

**Comment by antw** [comment]
I've pushed a commit to that branch. Not all converters in the three groups ("heat_production", "electricity_production", and "cost_other") have costs assigned. Therefore, calling total_initial_investment would fail:

**Comment by DorinevanderVlies** [comment]
Thanks @antw! This will save us a lot of time as we will have to run far less queries 😄
