### ISSUE TITLE
[Airbrake] [Production] NoMethodError: undefined method `with_indifferent_access' for false:FalseClass

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#961]
**Airbrake error:** [#8430](https://quintel.airbrake.io/projects/32233/groups/2078921985934398430)
**Airbrake project:** ETE

**Error type:** `NoMethodError`
**Error message:** `` NoMethodError: undefined method `with_indifferent_access' for false:FalseClass ``
**Where:** `data/scenarios#update`
**Occurred at:** Nov 08, 2017 08:46:52 UTC
**First seen at:** Nov 08, 2017 08:46:52 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [https://engine.energytransitionmodel.com/data/latest/scenarios/340450](https://engine.energytransitionmodel.com/data/latest/scenarios/340450)
**File:** `[PROJECT_ROOT]/app/models/scenario/user_updates.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/scenario/user_updates.rb:82:in user_values_as_yaml=
[GEM_ROOT]/gems/activerecord-4.1.5/lib/active_record/attribute_assignment.rb:45:in public_send
[GEM_ROOT]/gems/activerecord-4.1.5/lib/active_record/attribute_assignment.rb:45:in _assign_attribute
[GEM_ROOT]/gems/activerecord-4.1.5/lib/active_record/attribute_assignment.rb:32:in block in assign_attributes
```

**Comment by antw** [comment]
Was closed by 671fa7a9. I've cherry-picked it to production and it'll be deployed momentarily.
