### ISSUE TITLE
[Airbrake] [Production] No Atlas data for "baarland" at /var/www/etengine/releases/20171108090526/tmp/atlas/baarland.pack

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#965]
**Airbrake error:** [#7333](https://quintel.airbrake.io/projects/32233/groups/2084175345612657333)
**Airbrake project:** ETE

**Error type:** `RuntimeError`
**Error message:** `` No Atlas data for "baarland" at /var/www/etengine/releases/20171108090526/tmp/atlas/baarland.pack ``
**Where:** `api/v3/inputs#index`
**Occurred at:** Nov 15, 2017 14:44:21 UTC
**First seen at:** Nov 15, 2017 14:44:21 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [https://engine.energytransitionmodel.com/api/v3/scenarios/341461/inputs.json?include_extras=false](https://engine.energytransitionmodel.com/api/v3/scenarios/341461/inputs.json?include_extras=false)
**File:** `[PROJECT_ROOT]/app/models/etsource/atlas_loader.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/etsource/atlas_loader.rb:33:in load
[PROJECT_ROOT]/app/models/etsource/dataset/import.rb:77:in load_graph_dataset
[PROJECT_ROOT]/app/models/etsource/dataset/import.rb:65:in load_dataset_hash
[PROJECT_ROOT]/app/models/etsource/dataset/import.rb:42:in import
```

**Comment by grdw** [comment]
This was me trying out if it worked, a little too soon.
