### ISSUE TITLE
[Airbrake] [Production] param is missing or the value is empty: flexibility_order

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#972]
**Airbrake error:** [#7042](https://quintel.airbrake.io/projects/32233/groups/2088485758449917042)
**Airbrake project:** ETE

**Error type:** `ActionController::ParameterMissing`
**Error message:** `` param is missing or the value is empty: flexibility_order ``
**Where:** `api/v3/flexibility_orders#set`
**Occurred at:** Nov 21, 2017 13:28:22 UTC
**First seen at:** Nov 21, 2017 13:28:22 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [https://engine.energytransitionmodel.com/api/v3/scenarios/342028/flexibility_order/set](https://engine.energytransitionmodel.com/api/v3/scenarios/342028/flexibility_order/set)
**File:** `[GEM_ROOT]/gems/actionpack-4.1.5/lib/action_controller/metal/strong_parameters.rb`

**Backtrace:**
```
[GEM_ROOT]/gems/actionpack-4.1.5/lib/action_controller/metal/strong_parameters.rb:183:in require
[PROJECT_ROOT]/app/controllers/api/v3/flexibility_orders_controller.rb:33:in flexibility_params
[PROJECT_ROOT]/app/controllers/api/v3/flexibility_orders_controller.rb:8:in set
[GEM_ROOT]/gems/actionpack-4.1.5/lib/action_controller/metal/implicit_render.rb:4:in send_action
```

**Comment by grdw** [comment]
This was me trying out some things with `curl`. Closing.
