### ISSUE TITLE
When running the migration for the CO2 emission sliders, the memory of my Mac runs full.

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#991]
Relevant migration: https://github.com/quintel/etengine/blob/migration-for-co2-emissions/db/migrate/20180104152128_correct_co2_emission_sliders.rb

When running this migration for ~3200 scenarios, after 1600 - 1700 scenarios my machine is running out of memory.

I tried removing instance variables like:

```ruby
# After save:

scenario.gql.remove_instance_variable :@present_graph
scenario.gql.remove_instance_variable :@future_graph
scenario.remove_instance_variable :@gql
```

But this doesn't seem to really help that much (maybe it will get to 1950 but not any further).

I think it's just not doable doing a migration which requires calculating the full graph for each scenario.

**Comment by antw** [comment]
I'm guessing that [`scenario.gql`](https://github.com/quintel/etengine/blob/0f6dad57e3357d7f554924861597eb2d46284430/db/migrate/20180104152128_correct_co2_emission_sliders.rb#L22) is the culprit but it's not clear why that would cause the migration to *run out* of memory.

If I run `Scenario.default.gql` the memory used increases to about 400MB and then garbage collection kicks in and keeps it at about 400-600MB.

Just to sanity check: would you try adding `GC.enable` to the top of the `up` method and perhaps force Ruby to run GC every ten iterations?

```ruby
GC.enable
# ...

scenarios.find_each.with_index do |scenario, index|
  # ...
  GC.start if (index % 10).zero?
end
```

If that doesn't work we might have to try [perftools](https://github.com/tmm1/perftools.rb) to find out where all the memory is going.

---

Another possibility is to do something like the fuel prices migration: get the CO2 emission for a default scenario and just use that. It's not as accurate, but it may be preferable to calculating thousands of scenarios.

**Comment by antw** [comment]
Forcing GC to run had no effect for me. I've had some success with specifying the batch size for `find_each`.

```ruby
scenarios.find_each(batch_size: 5) do |scenario|
  next unless scenario.valid?
  # ...
end
```

For me the process now stabilises somewhere around 600MB; without the batch_size option it keeps growing. This makes some sense as the default batch size is 1000. I'm guessing that ActiveRecord is [holding a reference to all the scenarios](https://github.com/rails/rails/blob/d25c2e7c4c88440154087a08fa79ba0bf3038ba3/activerecord/lib/active_record/relation/batches.rb#L70) while processing each batch, and more memory is being consumed with each scenario calculated.
