### ISSUE TITLE
Mistake in technology shares motorcycles IABR scenario probably due to migration

### ISSUE THREAD

**Issue by MartLubben** [quintel/etengine#993]
The IABR scenario https://beta-pro.energytransitionmodel.com/scenarios/597150 has a technology share which does not count up to 100, but is 5.9% and 0.2%.

![screen shot 2018-01-24 at 10 39 14](https://user-images.githubusercontent.com/33415156/35325052-e8d136f0-00f2-11e8-90e8-171a1f2184d8.png)

@grdw Could it be possible that something went wrong during the below migration?

[etengine/db/migrate/20171130103516_add_transport_motorcycle_using_electricity_share_to_user_values.rb](https://github.com/quintel/etengine/blob/master/db/migrate/20171130103516_add_transport_motorcycle_using_electricity_share_to_user_values.rb)

**Comment by grdw** [comment]
No, the migration isn't suppose to cause this behavior. The idea behind that migration was that if (and only if) at the time of that migration a `transport_motorcycle_using_gasoline_mix_share` share was present in the sliders - the corresponding `transport_motorcycle_using_electricity_share` would also be set. Somehow it didn't do this 😨 

It could be that something went wrong with that migration - similarly to: https://github.com/quintel/etengine/issues/991 . Hmm. I'll rerun it, see what happens.

**Comment by grdw** [comment]
I rewrote it to be using only using the requirements from the migration debate [here](https://3.basecamp.com/3797409/buckets/4288548/messages/843023681#__recording_871463322) . This seems to solve it. I do remember the migration taking up a really long time on the `beta` server, just due to the size of the amount of scenarios to migrate. It did finish (since the corresponding `schema_migration` id (20171130103516) is actually in the database). But I don't know if it actually 'just gave up' or really finished naturally. Anyway, I tested the new migration and that seems to do the job in 55 seconds.

**Comment by MartLubben** [comment]
@grdw good news :)

**Comment by MartLubben** [comment]
@grdw 
I checked  https://beta-pro.energytransitionmodel.com/scenarios/663150 and it still shows:
![screen shot 2018-01-24 at 14 55 20](https://user-images.githubusercontent.com/33415156/35335756-b9128576-0116-11e8-8946-57ab98275f3f.png)



I merged your migration, but I guess it still needs to run? 
--

**Comment by grdw** [comment]
# I merged your migration, but I guess it still needs to run?

Yes. You can always check at: https://semaphoreci.com/quintel/etengine/branches/master

**Comment by grdw** [comment]
It still didn't go - for this particular scenario - as far as I can see.

**Comment by grdw** [comment]
<img width="467" alt="screen shot 2018-01-24 at 15 17 48" src="https://user-images.githubusercontent.com/2676542/35336780-c2971ef6-0119-11e8-8add-100e0ca5efb3.png">

The migration did run - checking for example - scenario id 763399

**Comment by grdw** [comment]
Okay, I did the unorthodox and edited the scenario manually through: https://beta-engine.energytransitionmodel.com/data/latest/scenarios/597150/edit - since I don't know why the scenario didn't migrate 🤷‍♂️

**Comment by MartLubben** [comment]
I won't tell anyone. :)
